### ISSUE TITLE
Sandbox-friendly?

### ISSUE THREAD

**Issue by librehome** [TypeScriptToLua/TypeScriptToLua#1004]
The current lualib_bundle is not sandbox-friendly, for obvious reasons.

For example, the exposed types such as Map, Set etc can be modified. The __TS__New randomly takes the content of metastable.

I suggest a sandbox-friendly syntax. We can start from __TS_New_type and __TS__Delete_type to hide the target. The modification shall be minimum.

**Comment by librehome** [comment]
[Proposal: Lualib override plugins](https://github.com/TypeScriptToLua/TypeScriptToLua/issues/973) should be able to solve the problem because we can control the generation of the Lua code so that we can add safe wrappers.

**Comment by Zamiell** [comment]
With Glass' PR in 2022 that removed all global variables from a bundle output, this issue may no longer be relevant, as no other programs could ever modify your Map/Set.

Perhaps this should be closed?

**Comment by librehome** [comment]
Yes. It all looks good. thanks for the fantastic work.
