### ISSUE TITLE
Add generated file header to bundle same as regular transpiled files

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1005]
Greetings,

In the configuration management world (e.g. Puppet, Chef), it is best practice for the tool to append a comment to the beginning of the file.

Something like:

```bash
# DO NOT EDIT THIS SCRIPT - THIS SCRIPT IS MANAGED BY PUPPET AND ANY CHANGES WILL BE OVERWRITTEN
mkdir foo1
mkdir foo2
mkdir foo3
```

Currently, this is the top 5 lines of my "main.lua" file that was generated by TypeScriptToLua:

```lua

local ____modules = {}
local ____moduleCache = {}
local ____originalRequire = require
local function require(file)
```

I propose that TypeScriptToLua should do the same thing for the lua files it outputs:

```lua
--[[

This file was automatically generated with TypeScriptToLua.
https://typescripttolua.github.io/
DO NOT EDIT THIS FILE, as any changes will be overwritten.

--]]

local ____modules = {}
local ____moduleCache = {}
local ____originalRequire = require
local function require(file)
```

I think this would be valuable for various reasons. For example, someone just submitted a pull request to one of my projects that edited the generated Lua file instead of the actual TypeScript files, and maybe this header would have prevented that.

Thoughts?

**Comment by lolleko** [comment]
We already print a header by default, you can even see it in the playground: https://typescripttolua.github.io/play

`--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]`

Can you confirm that you do not have the `noHeader` options set in your tstl config.

There is a chance that this header is not added for bundles (looks like your example is from a bundle), this is something we should be able to fix.

**Comment by Zamiell** [comment]
This is my tsconfig.json:

```jsonc
{
  // https://www.typescriptlang.org/docs/handbook/compiler-options.html
  "compilerOptions": {
    // Recommended as per TypeScriptToLua
    // https://typescripttolua.github.io/docs/getting-started/
    "target": "ESNext",
    "lib": ["ESNext"],
    "moduleResolution": "Node",
    "types": ["isaac-typescript-definitions"],
    "rootDir": "./src",

    // We want the compiler to be as strict as possible to catch all the things
    // By default, these flags are false
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
  },

  "include": [
    "./src/**/*.ts",
  ],

  "tstl": {
    "luaTarget": "5.3",
    "luaBundle": "./mod/main.lua", // Will bundle all output Lua files into a single file
    "luaBundleEntry": "./src/main.ts",
  },
}
```

So as you can see, I do not have the "noHeader" option set. But yes, I am bundling everything into a single file.

**Comment by Perryvw** [comment]
So we should add the header to the bundle output, respecting the noHeader flag if set.

**Comment by Zamiell** [comment]
Yup, sounds like it. Thanks Perry. ><
