### ISSUE TITLE
Implement array.entries

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1028]
Hi, this is a feature request for `array.entires()`. (The TSTL VSCode extension currently reports that it is unimplemented.)

I think this would be relatively quick to add!

**Comment by Perryvw** [comment]
What is the use case for array.entries?

**Comment by Zamiell** [comment]
Currently, I think I am forced to write code like this:

```ts
const poop = [
  "poop1",
  "poop2",
  "poop3",
];

for (let i = 0; i < poop.length; i++) {
  const entry = poop[i];
  // Do something with both i and entry
}
```

This would be better written as:

```
const poop = [
  "poop1",
  "poop2",
  "poop3",
];

for (let [i, entry] of poop.entries()) {
  // Do something with both i and entry
}
```

**Comment by Zamiell** [comment]
Woo hoo, thanks perry!
