### ISSUE TITLE
Bundle output path is relative to source dir instead of projectRoot, if no rootDir is provided

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1036]
```
git clone git@github.com:Zamiell/racing-plus.git
cd racing-plus
npm i
npx tstl
```

**Comment by Zamiell** [comment]
Is this a regression in version 0.40.0? Or does it have to do with @noResolve?

**Comment by Perryvw** [comment]
Output path resolutoin changed in 0.40.0 so likely related. I don't see how this would be related to `@noResolution` at all.

**Comment by Zamiell** [comment]
I think it has to be related, because everything worked fine until I added the @noResolution tag.
