### ISSUE TITLE
Top level [...$vararg] in bundled file not resolving to command line arguments

### ISSUE THREAD

**Issue by 7coil** [TypeScriptToLua/TypeScriptToLua#1048]
I'm trying to grab the command line arguments using `[...$vararg]`, which gets resolved to `{...}` in Lua.
Unfortunately, using `[...$vararg]` in the top level of the Lua bundle file results in the `{...}` to be placed inside a function, and no longer resolve the command line arguments.

![image](https://user-images.githubusercontent.com/13886925/126261196-9f4c9172-3e6d-4bd0-a385-d65458140da1.png)

As a temporary fix, I instead created a new global variable at the top of the generated file with the contents of `{...}`, and using that variable to access the argv's.

I'm not an avid Lua user, but I might suggest somehow passing the command line arguments to (only?) the main module.

![image](https://user-images.githubusercontent.com/13886925/126261840-79350032-c76a-46a6-b621-d1da4e79a64e.png)

### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "esnext"
    ],
    "moduleResolution": "node",
    "types": ["lua-types/5.1"],
    "strict": true,
    "outDir": "dist/"
  },
  "tstl": {
    "luaTarget": "5.1",
    "luaBundle": "output.lua",
    "luaBundleEntry": "src/index.ts"
  }
}
```

**Comment by lolleko** [comment]
Not sure that is easy to fix because the way bundles work.

But irrc there is an _arg_ table that holds the command line arguments. Try using that instead via `declare var arg: Array<string>`.

**Comment by 7coil** [comment]
I've been seeing the _arg_ table around but I didn't know this was implemented too in Computercraft!
I will probably add this to my own declarations file.

Thanks for the workaround.
