### ISSUE TITLE
Lua Modules don't work if they have a default export

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1057]
For example, say that I have a Lua module that is just an "array". (Well, in Lua everything is tables, but hopefully you get what I mean.)

```lua
return {
  -- Thing 1
  {
    foo = 1,
    bar = 2,
  },
  -- Thing 2
  {
    foo = 1,
    bar = 2,
  },
}
```

TSTL will not handle this correctly. It will compile the code without any errors, but during runtime the array will be equal to nil because the transpiled code will be something along the lines of:

```lua
local foo = require("myDir.foo")
local ___foo = foo.default -- ".default" doesn't exist, obviously
```

See this minimal repository that reproduces the problem:

https://github.com/Zamiell/tstl-test

**Comment by hazzard993** [comment]
The default export is just an export you can access using the `default` key and import with a special syntax

Try out the `export = <expression>` syntax to specify that a module exports `<expression>` ONLY

I usually do something like this:

```ts
// module.d.ts
declare const contents: Array<{ foo: number; bar: number; }>;
export = contents;
```

And then import it like this

```ts
import * as contents from "./module"; // from module.d.ts, assuming "module.lua" is accessible at runtime
const x = contents[0]; // { foo: number; bar: number }
```

TypeScript may try to import it like this with the "esModuleInterop" flag

```ts
import contents from "./module"; // TypeScript will allow this syntax with "esModuleInterop", this 
```

But this syntax tells TypeScriptToLua that you can access this value via the `default` key which you can't for this case

**Comment by Zamiell** [comment]
> Try out the export = <expression> syntax to specify that a module exports <expression> ONLY

Thanks Hazzard. This syntax is a little arcane. I think this should be documented on the TSTL website, since you would likely never have to write code this way if you were just doing normal TypeScript.

**Comment by Perryvw** [comment]
Double checked with TS documentation: https://www.typescriptlang.org/docs/handbook/modules.html This is indeed working as intended.

Feel free to open a pull request to [the docs](https://github.com/TypeScriptToLua/TypeScriptToLua.github.io) with further clarification.
