### ISSUE TITLE
Maps are instantiated N times, one for each .ts source code file

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1061]
steps to reproduce:

1) clone this repo https://github.com/Zamiell/tstl-test
2) run the lua file without rebuilding the project, as it contains hand-crafted print statements that were added to demonstrate the problem

**Comment by Zamiell** [comment]
Other things:

### LuaBundle

When I disable the LuaBundle feature in tsconfig.json, the compiled Lua just fails to run **at all**.
Not sure what is going on there, maybe that is a separate bug altogether?

### instanceof Failing

The Lua file correctly prints "MAP DETECTED".
However, if this code was in a Lua module imported from NPM, it would fail and say "MAP NOT DETECTED".
That's the *real* bug that I'm trying to troubleshoot here and need fixed in order for my NPM module to function correctly.

**Comment by Perryvw** [comment]
Bundling issue: We directly add the return value of a module to the module cache. In case of modules that have a nil return this causes the cache to never get any value, and the module is re-evaluated for every require.
