### ISSUE TITLE
@NoResolution prefix is removed from require in library mode, causing clients to try to resolve NoResolution modules

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1062]
I have the following simple definition for a "json.lua" file:

```ts
/** @noResolution */
declare module "json" {
  function encode(this: void, data: unknown): string;
  function decode(this: void, data: string): unknown;
}
```

I use the `@noResolution` compiler flag to tell TSTL that the Lua file exists already.

This allows me to use these functions in a normal way, e.g.:

```ts
import * as json from "json";

const jsonString = json.ecode(myTable);
```

Normally, the above code works great.
However, if I stick this code inside of a Lua module, and then import the Lua module in another TSTL project, the compiler will scream:

```
$ ./build.sh
error TSTL: Could not resolve require path 'json' in file node_modules\isaacscript-common\dist\jsonHelper.lua.
```

**Comment by Perryvw** [comment]
Issue was not that the noResolution annotation was ignored, but rather that it was removed after resolving it, even in library mode. When the client application would then inspect the file it would have no indication this require should not be resolved. Solution is to not remove the internal @NoResolution prefix in requires when building in library mode.
