### ISSUE TITLE
Result luaBundle is out of entry point bundled code

### ISSUE THREAD

**Issue by websharik** [TypeScriptToLua/TypeScriptToLua#1065]
Files struct:
```
src/server.ts (with import from file1.ts)
src/file1.ts
src/file2.ts
```

Config:
```
{
  "compilerOptions": {
    "target": "ES6",
    "lib": [
      "es6"
    ],
    "module": "commonjs",
    "strict": true,
    "baseUrl": ".",
    "rootDir": "src",
    "outDir": "dist",
    "types": [
      "lua-types/5.1"
    ],
    "forceConsistentCasingInFileNames": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true
  },
  "tstl": {
    "luaTarget": "5.1",
    "noImplicitSelf": true,
    "luaLibImport": "none",
    "sourceMapTraceback": false,
    "luaBundle": "server.lua",
    "luaBundleEntry": "src/server.ts"
  }
}
```

Expected: dist/server.lua with injected file1.lua

Working now: dist/server.lua with injected all files from src (server + file1 + file2)

**Comment by Perryvw** [comment]
This is intended behavior as far as I'm concerned, we do not do any checking if TS files are actually used, we just include all files TypeScript tells us is part of the program. You can avoid this using `include` or `exclude` in your tsconfig.json, or by moving the extra ts files to some other location.

**Comment by websharik** [comment]
"file2" is not part of the "server" program. Low level api working fine:
```javascript
function makeBundleFile(filePath, conf) {
  return new Promise(async (resolve, reject) => {
    try {
      let result = await tstl.transpileFiles([filePath], {
        //original from tsconfig.json
        ...conf.compilerOptions,
        ...conf.tstl,
        //if not . then put out to src
        rootDir: ".",
        //same name from src
        luaBundle: path.basename(filePath).replace('ts', 'lua'),
        //entry point
        luaBundleEntry: filePath
      })
      resolve(result)
    } catch (e) {
      reject(e)
    }
  })
}

(async (filePath) => {
  let config = JSON.parse(fs.readFileSync(path.resolve('tsconfig.json'), {encoding:'utf8'}))
  let result = await makeBundleFile(filePath, config);
  console.log(result)
})("src/server.ts")
```

Its working fine and return "server" with only "file1". But if i try luaBundle just in config its working wrong. I think its a some bug.

include/exclude not my way becouse i have N entry points (server, client...) and i want separate bundles per point.

**Comment by Perryvw** [comment]
There is a difference between transpiling a project (a tsconfig.json) where TypeScript gathers all files to translate, and transpileFiles where you supply the file list. I would suggest you split your server and client files into two different directories with their own tsconfig files, and then add a common directory that you can include  in both like so: https://github.com/ModDota/TypeScriptAddonTemplate/blob/master/src/vscripts/tsconfig.json
