### ISSUE TITLE
LuaIterable and sol2 containers

### ISSUE THREAD

**Issue by ihm-tswow** [TypeScriptToLua/TypeScriptToLua#1069]
Trying to set up [sol2 containers](https://sol2.readthedocs.io/en/latest/containers.html), which uses a special `pairs` method when iterating in lua5.1. In lua, the way to iterate them would be:

```ts
for a,b in my_container:pairs() do
end
```

I noticed this is just how iterator syntax is described in the [documentation](https://typescripttolua.github.io/docs/advanced/language-extensions/#luaiterable-type). I have the following declaration: 

```ts
declare class vert_array {
    // This is correct, pairs is a special member necessary in 5.1/jit
    pairs(): LuaIterable<LuaMultiReturn<[number,vert]>>
}
```

With the following code:

```ts
// where some_verts: vert_array
for(const [a,b] of some_verts.pairs()) {} 
```

Which produces:
```ts
    for ____, ____value in __TS__Iterator(
        some_verts:pairs()
    ) do
        local a = ____value[1]
        local b = ____value[2]
    end
```

Since pairs() isn't actually an iterator, this will break and I can't find a way to hack the lualib bundle to extract the correct values, meaning for now I can't find any way to iterate them through typescript at all. Is there any way to get this to transpile to something compatible with the above example instead?

**Comment by Perryvw** [comment]
This is exactly what the point behind the `LuaIterable` type is. It seems to work as expected on [this little playground example I made](https://typescripttolua.github.io/play#code/CYUwxgNghgTiAEkoGdnwG4hgF3gbwF8AoI0JORaVDLbAfVhigE98j4P4B6L+AFQAWASzQjEAexhww2ADTwADlCExRaKPGQLwQqBHgBbEAYBGWeADtwIVLFZCL8AKwA6AIxcAVkOztOSlWQACgBKAC54ABkAVygASWwsKBMIEAAeGKgAWWiIbCEAJRBsaJgLNIBtC2jTLFlMHABdAD5momIiMHELZFxkcSM6Buw0AF5LEAB3GhwGKRZQgG4SHnhJgSwEfsHh5AjhuaZmIgAzSSCuntwKqFkTRvhxE80BkCHaZBcA1VCQ-AJ4EA).

I'm not sure why your resulting code is different, did you add language extensions to your tsconfig.json like the docs describe? any other errors?

**Comment by ihm-tswow** [comment]
We switched from using those containers for other reasons. I didn't save my config but I can no longer reproduce this so I likely had some misconfiguration. Thanks for looking!
