### ISSUE TITLE
Could not resolve require path `./some-file` in file ...

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/TypeScriptToLua#1070]
**Description**

When I try to compile file with linked `.d.ts` file, I receive an error. 
That's an unexpected behaviour for me, because [this case is described in docs](https://typescripttolua.github.io/docs/advanced/writing-declarations/#export-keyword).

```
> tstl

error TSTL: Could not resolve require path './another' in file index.ts.
```

**How to reproduce**

1. Install `typescript-to-lua >= 0.40.1`
2. Create files: `index.ts`, `another.d.ts`, empty `tsconfig.json`

`another.d.ts`:

```typescript
export const foo: () => number;
export let x: number;
```

`index.ts`:

```typescript
import {foo, x} from "./another";

function helloWorld() {
    return `Hello ${foo()} World`;
}
```

3. Run `tstl`
4. Receive `Could not resolve require path './another' in file index.ts`

Documentation reference: https://typescripttolua.github.io/docs/advanced/writing-declarations/#export-keyword

**Tested versions**

|Version| Result|
|---|---|
|`0.41.2`|Not working|
|`0.40.1`|Not working|
|`0.39.6`|**Working**|

**Workaround**

Create the lua file in the same directory with the same name. 
For example, for `another.d.ts` create `another.lua`

**Comment by websharik** [comment]
`src/another`
`Cannot find module 'src/another' or its corresponding type declarations.`

`from "src/another.d.ts"`
`An import path cannot end with a '.d.ts' extension.`

Compiler may know about `another.d.ts` but not use it becouse its declarations ?
Its bug or docs about import declarations upgrade required ?

**Comment by Perryvw** [comment]
This looks like expected behavior, you are calling a function from your imported file, it must get this function's code somewhere. I don't see how your listed workaround actually fixes this, because you will just get a runtime error saying `foo` is nil. Where are you expecting to get `foo`'s implementation from?

**Comment by websharik** [comment]
@Perryvw I think `foo` and `x` is global from lua environment (from game engine). And @Toliak  trying to remove `foo` and `x` "require" from compiled files.

**Comment by Toliak** [comment]
Ok, I see.
I agree with @Perryvw about local located file. But what about packages that provides the types for existing lua package? 
I believe, types and lua-files can be located in separated folders.. If they can, maybe make this "check" disable-able for packages? 

@websharik ,

> foo and x is global from lua environment

Unfortunately, Its true only for MTASA, not for general Lua. So, for local-scoped file I'm wrong, however, I think types package and lua-sources package can be stored seaparately **(I'm not sure about this, so it can be my delusion)**

**Comment by Perryvw** [comment]
@Toliak you are correct, they can be separate, but in that case the lua files in the lua package should be able to be resolved. Have a look at this this directory in our tests: https://github.com/TypeScriptToLua/TypeScriptToLua/tree/master/test/transpile/module-resolution/project-with-node-modules

This project has 4 lua node_modules packages, 2 with types and 2 without types (the types for those without types are provided as .d.ts files in the project root).

To complete this thread: If you just want to declare the types for global objects provided by the environment **that you do NOT need to require**, you can declare them like you did but without using any imports or exports. TypeScript will then treat them as if they are globally available, and you do not have to import them. (If they are not in your project root you might have to include the .d.ts files in the `include` of your tsconfig.json. For example, see the dota 2 types: https://github.com/ModDota/TypeScriptDeclarations/blob/master/packages/dota-lua-types/types/api.generated.d.ts

**Comment by Toliak** [comment]
Thank you, I will see provided directory a bit later

---

> If you just want to declare the types for global objects provided by the environment that you do NOT need to require, you can declare them like you did but without using any imports or exports

I expected that answer. The problem for MTASA is that all Lua files divides on two categories: **client** and **server**. And global-scope for script depends on its side.

Moreover, in MTASA [`require` is disabled](https://forum.mtasa.com/topic/113918-use-more-lua-files-require/), hence, I cannot use "import" even for local files :c
