### ISSUE TITLE
`noImplicitSelf` option does not works in `transpileFiles` function

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/TypeScriptToLua#1084]
**Description**
If I call:
```ts
import { transpileFiles } from 'typescript-to-lua';

// ...

transpileFiles(
    [path.join(rootPath, subPath, `index.ts`)],  // existing filename
    options, // options contains noImplicitSelf=true
    writeData,  // writes data info a file with provided file path
);
```

I expect to receive global functions without the `self` argument in all compiled files. However, I receive another result instead.

`index.ts` content:
```ts
function something() {
  return 1;
}
```

I expect, that the function `something` will have no `self` argument in the output file.

**Moreover, ** if I use CLI command `tstl src/test/resource_example/index.ts` I receive the same, incorrect, output.

But if I will execute `tstl` -- everything works correctly...

**Dive into TSTL sources**

I have debbuged the compiled sources a bit and I saw the pipeline like this (point numbers are ordered by breakpoints flow):

1. The compiler option `noImplicitSelf` determines correctly, `noImplicitSelfTransformer` is being added [here ](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/transformers.ts#L28)  
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/transformers.ts#L28
2. ~~Comment `/** @noSelfInFile */` is being checked [here](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transformation/utils/function-context.ts#L87) for file `index.ts`. Result -- **false negative**~~ See comment below  
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transformation/utils/function-context.ts#L87
3. ~~**!!!** The transformer acts [here](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/transformers.ts#L48). It adds a leading comment to the `index.ts`~~ (update: see comment below)

**Workaround**
- Specify `/** @noSelfInFile */` manually

**Comment by Toliak** [comment]
**Update**
I have found the bug in [this line](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transformation/utils/function-context.ts#L82)

`program.getRootFileNames()` contains: `Array(1) [C:\Users\Toliak\WebstormProjects\mtasa-lua-utils\src\test\resource_example\index.ts]`

`signatureDeclaration.getSourceFile().fileName` contains `signatureDeclaration.getSourceFile().fileName`

As you can see, there is a difference in the slashes

**Comment by Perryvw** [comment]
Nice find, we already have a `normalizeSlashes` function we can just use to solve this
