### ISSUE TITLE
Access/calls on nonexistent properties in optional chaining does not raise error

### ISSUE THREAD

**Issue by GlassBricks** [TypeScriptToLua/TypeScriptToLua#1085]
In an optional chain, if a nonexistent property (`nil`) later in the chain is called or accessed, it silently fails and returns `nil`.
In typescript, these gives a runtime error instead.

https://typescripttolua.github.io/play#code/PTAEEMBtNAXALApgZ0aADgJwJYDtbKjLwD2ArpACagDm2AbmoppiZsgFAcDGJuysUCQBGAKwBcEXAE9QAXlABvAL5cseWAAoRogPwA6AGYkSmgJRm1OfNrEHh4TPocAvSzz4ChYgEzylHKBBoMYkkioQhOAyHKoc6jY6Pgahzo7m7kA

**Comment by Toliak** [comment]
Maybe I am missing something, how TypeScript would determine nonexistent properties if all determined types are `any`?..

https://typescripttolua.github.io/play/#code/PTAEEMBtNAXALApgZ0aADgJwJYDtbKjLwD2ArpACagDm2AbmoppiZsgFAd6zMBm4AMZoA8gCMAVgBUAnujQBvDqBWg+JEgC5QACgCUoALwA+UPRLZKAbmWqx4TNqWqXoewC9tZXAGtcJAHdcGxcAXw5w7nx+IVFJACZZeVBnVXUSAH5tcWk5RAiuQRJcZFhQEklsySS0AB9Qb0pEPjxEakMU2xV07X0jUwVQgBoutwcnUZcPbQBGAAY5kbCCjiweHQqJDIA6dP09LjX8Dckd+0xtjwOOIpKyzfiqiUS8o06XHvLJEcij2BPnjt0pcHNcgA

**Comment by Perryvw** [comment]
Indeed if you do not give these `any` types then TS will disallow all of your examples: 

https://typescripttolua.github.io/play/#code/PTAEEMBtNAXALApgZ0aADgJwJYDtbKjLwD2ArpACagDm2AbmoppiZsgFAcDGJuysUCQBGAKwBcoAN6gAZiRIB+SQAoAlKAC8APlD0S2agF8t0o1yx5YKkaMUA6eSXVqLOfDbEPh4TPZ8AXq48fAJCYgBMplIcoHFyCpJSJuCEMj6YyqDqWrr6hqDm5hyWHrYRDk7+vi5cQA

That said, I do think we might want to indeed throw in these cases, like javascript does. Same code in TS playground:

https://www.typescriptlang.org/play?#code/PTAEEMBtNAXALApgZ0aADgJwJYDtbKjLwD2ArpACagDm2AbmoppiZsgFAcDGJuysUCQBGAKwBcoAN6gAZiRIB+SQAoAlKAC8APlD0S2agF8t0o1yx5YKkaMUA6eSXVqLOfDbEPh4TPZ8AXq48fAJCYgBMplIcoHFyCpJSJuCEMj6YyqDqWrr6hqDm5hyWHrYRDk7+vi5cQA

**Comment by GlassBricks** [comment]
There are some cases where this can arise without `any`: such as not null assertions, or (how I first found out about this), flawed type definitions. I used `any` in the examples for simplicity's sake.
