### ISSUE TITLE
Bundle mode with sourceMapTraceback does not replace `{#SourceMapTraceback}`

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/TypeScriptToLua#1109]
# Description

Enabling bundle-mode (`luaBundle` and `luaBundleEntry`) with `sourceMapTraceback`) will cause to appear `{#SourceMapTraceback}` in the result file.

## Steps to reproduce

1. Create a project with dependencies:
```json
{
  "typescript": "^4.4.2",
  "typescript-to-lua": "^1.0.0"
}
```
2. Create `tsconfig.json` with listed content:
```json
{
  "$schema": "https://raw.githubusercontent.com/TypeScriptToLua/vscode-typescript-to-lua/master/tsconfig-schema.json",
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "tstl": {
    "luaTarget": "JIT",
    "sourceMapTraceback": true,
    "luaBundleEntry": "src/index.ts",
    "luaBundle": "dist/index.lua"
  }
}
```
3. Create an empty `src/index.ts` file
4. Run `tstl`
5. Check the received `dist/index.lua`. It looks like:
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]

local ____modules = {}
local ____moduleCache = {}
local ____originalRequire = require
local function require(file)
    --- require code here, ok .....
end
____modules = {
["lualib_bundle"] = function() 
    --- lualib code here, ok .....
end,
["index"] = function() --[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
require("lualib_bundle");
{#SourceMapTraceback}     -- <<--- Look here
 end,
}
return require("index")
```

# Why does it happen

The "macro-string" `{#SourceMapTraceback}` should be replaced here:
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/LuaPrinter.ts#L150-L153

## Debugging

I will try to debug the compiler and list the ideas below. I believe it will help to determine the problem,

1. Debugger says, that `print` function from [LuaPrinter.ts](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/LuaPrinter.ts#L131) successfully replaces the macro-string
2. Correct version is being added into the `transpiledFiles` array https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/transpile.ts#L62-L74
3. I think error is in this line (especially, in `getEmitPlan` function). Because `freshFiles` contains correct code (with replaced macro-string)
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/transpiler.ts#L38
4. On this line: `resolutionResult.resolvedFiles` contains correct code, `bundleFile` -- does not
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/transpiler.ts#L72
5. Here. The `moduleSourceNode` function. Returns array of strings for `lualib_bundle` and array with incorrect SourceNode for `index`
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/bundle.ts#L52
![image](https://user-images.githubusercontent.com/25643405/131215994-5f1112cc-9c42-4004-9330-144fdce8dce6.png)
6. Finally, this line. The function `moduleSourceNode` contains `code` (with correct code) and `sourceMapNode` with child with incorrect code.
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/bundle.ts#L84

# Suggestion

I have replaced the line (p. 6) by `return joinSourceChunks([tableEntryHead, code, tableEntryTail]);` and it works.

Moreover, here specified, that code always exists. So, what about to put `code` instead of `sourceMapNode ?? code`?
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/691c9cc7bde8dfd89f44e61cf0777e4bdfbd3fcd/src/transpilation/utils.ts#L17-L21

**Comment by Perryvw** [comment]
Believe this should be fixed in #1110
