### ISSUE TITLE
static method call

### ISSUE THREAD

**Issue by kenkinky** [TypeScriptToLua/TypeScriptToLua#1112]
hey, guys!

```ts
// *.d.ts
declare namespace CS {
    namespace UnityEngine {
         class Application extends System.Object {
             public static Quit(exitCode: number): void;
         }
    }
}
```

```lua
 // lua
 CS.UnityEngine.Application:Quit(0) //error

 CS.UnityEngine.Application.Quit(0) //I need this
```

> error between "." & ":", I known this way to fix it

```ts
// *.d.ts
declare namespace CS {
    namespace UnityEngine {
         class Application extends System.Object {
             public static Quit(this:void, exitCode: number): void;
         }
    }
}
```

but, this declare codes are generated by scripts, to much methods to fix.

I just want to known, is there another way?

**Comment by tomblind** [comment]
You can put `@noSelfInFile` at the top, or use the `noImplicitSelf` compiler option.

[Doc](https://typescripttolua.github.io/docs/the-self-parameter#noselfinfile)

**Comment by Perryvw** [comment]
You can also put [@noSelf](https://typescripttolua.github.io/docs/the-self-parameter/#noself) on the class, it will apply to all methods in it.

**Comment by kenkinky** [comment]
thinks.
