### ISSUE TITLE
Support for unicode identifiers (on LuaJIT)

### ISSUE THREAD

**Issue by Cheatoid** [TypeScriptToLua/TypeScriptToLua#1117]
### Problem description
Looks like TSTL is replacing unicode identifiers with some random gibberish (or is probably using unicode hexadecimal code-point format).

### Practical example
A (game) engine may expect Lua script to define a global function called `开始` (Start), depending on whether or not the function is defined, an engine would invoke aforementioned function.  
The problem is that (global) function name is changed during transpilation (from `开始` to `_____5F00_59CB`), which is obviously unwanted behavior in this scenario, because it means that function would never be executed.

Sample TypeScript snippet:
```typescript
function 开始(): void { print("Starting..."); }
```

| Expected Lua | Actual Lua |
|:------ |:-------- |
|<pre lang="lua">function 开始() print("Starting...") end</pre>|<pre lang="lua">function _____5F00_59CB() print("Starting...") end</pre>|

### Suggested solution
Unicode identifiers should be preserved when `luaTarget` is set to `JIT` (since this feature is only supported on LuaJIT of course, so far).

### Justification
LuaJIT allows unicode in identifiers, TypeScript (and Javascript) allows them as well.  
Therefore, there is really no reason why this should be left behind, or unsupported.

**Comment by baidwwy** [comment]
lua5.4也支持
Lua5.4 defines LUA_UCID also supports
https://github.com/lua/lua/blob/eadd8c7178c79c814ecca9652973a9b9dd4cc71b/lctype.c#L20

**Comment by nanchengjiumeng** [comment]
你解决了么？

**Comment by nanchengjiumeng** [comment]
Thanks, your changed branch runs well.
