### ISSUE TITLE
Lua require C lib paths are replaced to resolved path

### ISSUE THREAD

**Issue by pilaoda** [TypeScriptToLua/TypeScriptToLua#1118]
_lib/utils/LuaPanda.lua_
`require("socket.core")`

this code is replaced to 
`require("lib.utils.socket.core")`

There is also an error:

> Could not read content of resolved dependency xxx\lib\utils\socket\core.lua.

I don't want such check and replacement for lua. Module "socket.core" is just a C Library but not a source code in my project.
[LuaSocket](https://github.com/diegonehab/luasocket)

Please at least provide a configuration to turn off such behaviors.

**Comment by Perryvw** [comment]
We have the `@noResolution` compiler annotation for exactly this: [see the docs here](https://typescripttolua.github.io/docs/advanced/compiler-annotations#noresolution)

**Comment by pilaoda** [comment]
> We have the `@noResolution` compiler annotation for exactly this scenario: [see the docs here](https://typescripttolua.github.io/docs/advanced/compiler-annotations#noresolution)

`@noResolution` is only for typescript source code. 
My `require` source code is in a pure lua file: _./lib/utils/LuaPanda.lua_, and it is required by another pure lua file _./lib/utils/debugger.lua_

Finally, a typescript source code do `import "./lib/utils/debugger";`.

**Comment by Perryvw** [comment]
Aha, I see what you mean. I'm thinking we could probably add some list of non-resolve libraries to the configuration, and check those when a require inside a .lua file cannot be resolved. (and adjust the diagnostic message in this case to mention this setting)

**Comment by pilaoda** [comment]
> Aha, I see what you mean. I'm thinking we could probably add some list of non-resolve libraries to the configuration, and check those when a require inside a .lua file cannot be resolved. (and adjust the diagnostic message in this case to mention this setting)

Or we can just ignore those pure lua files that have no ts source file.

**Comment by Perryvw** [comment]
Even if the lua file has no TS source, we still need to make sure that the files it requires exist, there is no way to tell from an included lua file or lua npm package if the required file is missing or if it is not supposed to be imported.

**Comment by pilaoda** [comment]
ok
