### ISSUE TITLE
about ts common require

### ISSUE THREAD

**Issue by kenkinky** [TypeScriptToLua/TypeScriptToLua#1124]
各位大佬们好, 晚上(也许是早上或中午)好:
Hello everyone, good evening (maybe morning or noon):

我现在的情况是这样, 因为我前些日子职位调动, 现在在维护一个常规的大量使用lua的项目. lua的诟病我就不一一赘述了.
My current situation is like this, because I was transferred a few days ago, and now I am maintaining a regular Lua project. I will not repeat the criticisms of Lua.

由于我除了维护之外, 还是需要写一些新的脚本(也是lua), 我考虑使用TypeScriptToLua来做, 但是我现在遇到一个问题:
In addition to maintenance, I still need to write some new scripts (also lua), I consider using TypeScriptToLua to do it, but I now encounter a problem:

如果我使用编译选项` "luaLibImport": "require"`, 那么生成的lua代码`require("lualib_bundle")`将会污染整个lua环境(可能影响到旧的代码).
If I use the compilation option `"luaLibImport": "require"`, then the generated lua code `require("lualib_bundle")` will pollute the entire lua environment (may affect the old code).

我大概想要的是这样的东西:
What I probably want is something like this:

```ts
// A.ts
export default class A {

}
```
```lua
// A.lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
require("lualib_bundle");
local ____exports = {}
____exports.default = (function()
    ____exports.default = __TS__Class()
    local A = ____exports.default
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    return A
end)()
return ____exports
```

这是我想要的样子:
This is what I want:

```lua
// A.lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local lualib_bundle = require("lualib_bundle");  -- 重点在这里 The point is here
local ____exports = {}
____exports.default = (function()
    ____exports.default = lualib_bundle.__TS__Class()  -- 重点在这里 The point is here
    local A = ____exports.default
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    return A
end)()
return ____exports
```

我能有办法做到它吗?
Is there a way I can do it?

**Comment by Perryvw** [comment]
This is not possible at the moment. I have been considering something like this, also because it would help deal with version differences between packages. At the moment this is not possible however.

**Comment by GlassBricks** [comment]
Could we add a new `luaLibImport` option to support this? `lualib_bundle` could be refactored to instead export, and we can add `Object.assign(_G, lua_lib)` to maintain previous behavior.

**Comment by kenkinky** [comment]
好吧! 期待新的改进! 我现在使用的是`"luaLibImport": "inline"`, 目前还好, 当我不使用TS的特性时, 它几乎不生成任何代码.
ok Look forward to new improvements! I'm using ` "lualibimport": "inline". At present, it's OK. When I don't use the feature of TS, it hardly generates any code
