### ISSUE TITLE
Regression on v1.0.1 with outDir

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1134]
I think there is a regression in 1.0.1, because "outDir" stopped working for my Lua bundles.
Specifically, I mean to say that the compiled "main.lua" file now goes to the root of my project instead of a subdirectory.
I noticed the change when upgrading from 1.0.0 to 1.0.1.
I was able to work around the bug by deleting "outDir" entirely from my tsconfig.json and then prefix the directory into the "luaBundle" option.

**Comment by thejustinwalsh** [comment]
Interesting I don’t bundle and those loose files are still going to outDir on my project setups. This must be specific to bundeling?

**Comment by Perryvw** [comment]
I cannot seem to reproduce this, bundles seem to be output to the outdir just fine. What is the tsconfig that is giving you problems?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/racing-plus/blob/42a178557229837789a64da4690e01db7302fd5d/tsconfig.json

for reference, the repo on this commit is at tstl v1.0.0, and when i upgraded to v1.0.1, i noticed the bug

**Comment by Perryvw** [comment]
Not able to reproduce this, cloning your repository at the commit you linked and running tstl outputs the bundle in the outdir as expected.

**Comment by Zamiell** [comment]
yeah, that's because the repository at the commit I linked is at tstl v1.0.0, so you have to upgrade to tstl v1.0.1

**Comment by Perryvw** [comment]
I made sure to run with 1.0.1 of course, still works as expected.

**Comment by Zamiell** [comment]
hrm, weird
I'm happily running my software now without using "outDir" at all, so I'll just close this issue for now
