### ISSUE TITLE
The plugin example in the documentation does not work

### ISSUE THREAD

**Issue by nazo6** [TypeScriptToLua/TypeScriptToLua#1141]
I tried to create tstl plugin and I copied `example` 
```ts
import * as ts from "typescript";
import * as tstl from "typescript-to-lua";

const plugin: tstl.Plugin = {
  // `visitors` is a record where keys are TypeScript node syntax kinds
  visitors: {
    // Visitor can be a function that returns Lua AST node
    [ts.SyntaxKind.ReturnStatement]: () => tstl.createReturnStatement([tstl.createBooleanLiteral(true)]),
  },
};

export default plugin;
```
from plugin section of docs (https://typescripttolua.github.io/docs/api/plugins) but I got unexpected result.

I thought this
```ts
function a() {
  return "foo";
}
```
will be compiled to
```lua
function a(self)
    return true
end
```
but I got
```lua
function a(self)
    return "foo"
end
```

However, `Example 2` returns
```lua
function a(self)
    return "bar"
end
```
and this is code I was expected.

Is this the expected behavior?

**Comment by Perryvw** [comment]
Make sure the typescript version in your project matches the TypeScript version used by tstl (4.3), otherwise you will run into weird issues.

**Comment by nazo6** [comment]
Oops, I was using Typescript 4.4. Downgrading typescript solved the problem. Thanks!
