### ISSUE TITLE
Allow noResolvePaths to be a pattern

### ISSUE THREAD

**Issue by GlassBricks** [TypeScriptToLua/TypeScriptToLua#1161]
In some environments (e.g. factorio mods) you want entire libraries to have no resolution (and just use typescript's resolution instead). It would be nice if we could specify something such as `noResolvePaths: ["someLib/*"]` to no-resolve all imports that starts with `someLib`.

**Comment by takegine** [comment]
Hope to support regular expressions，beause of some diff.  "someLib/*"

**Comment by Curve** [comment]
@Perryvw apologies for the ping, is there any progress on this / Are Pull-Requests for this issue welcome?

If so, would a regex-based approach be applicable, or should something like [glob-matching](https://www.npmjs.com/package/glob) be used?

**Comment by Perryvw** [comment]
> @Perryvw apologies for the ping, is there any progress on this / Are Pull-Requests for this issue welcome?
> 
> If so, would a regex-based approach be applicable, or should something like [glob-matching](https://github.com/isaacs/minimatch) be used?

Pull requests are welcome, I would prefer to just support glob patterns. Unless there is any reason to use the others, I would prefer to limit our nr of dependencies as much as possible and therefore use https://github.com/micromatch/picomatch rather than any of the other suggested libs, which all have several recursive dependencies.

**Comment by Curve** [comment]
> > @Perryvw apologies for the ping, is there any progress on this / Are Pull-Requests for this issue welcome?
> > 
> > If so, would a regex-based approach be applicable, or should something like [glob-matching](https://github.com/isaacs/minimatch) be used?
> 
> Pull requests are welcome, I would prefer to just support glob patterns. Unless there is any reason to use the others, I would prefer to limit our nr of dependencies as much as possible and therefore use https://github.com/micromatch/picomatch rather than any of the other suggested libs, which all have several recursive dependencies.

Alright thanks for the insight, I'll give it a go tomorrow
