### ISSUE TITLE
Ability to overwrite the bundle template / Ability to customize the comment header

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1178]
I want to automatically add a comment to the top of a "main.lua" file that is transpiled with TSTL's `luabundle` flag.
The idea is to explain to readers that this file was generated with a tool and is not intended to be read by humans, and that the actual source code for the file is available on GitHub and people should go there to read the source code.

Unfortunately, it sounds like performing this simple task is currently impossible, because:

1) TSTL does not support overwriting the bundle template.
2) TSTL does not support customizing the comment header that says: `--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]`

I would love the ability to do one of these two things (preferably both!), either through a TSTL plugin, or through a TSTL compiler flag, or some other mechanism.

**Comment by Zamiell** [comment]
I think that with the new features in TSTL 1.4.0, this should be possible now, so I'll close

**Comment by Zamiell** [comment]
According to Perry, the `afterPrint` hook won't work with bundles, so this issue is still not resolved; I'll re-open.

**Comment by Perryvw** [comment]
This is now somewhat possible with a `beforeEmit` plugin ([see docs](https://typescripttolua.github.io/docs/api/plugins#beforeemit)).
