### ISSUE TITLE
Multiple return types in async coroutines.

### ISSUE THREAD

**Issue by roobscoob** [TypeScriptToLua/TypeScriptToLua#1188]
Parent issue: https://github.com/cc-tweaked/CC-Tweaked/issues/983

Hello! I'm using TSTL to create code to run on CC-Tweaked's computers. CC:T treats coroutine yielding and resuming as an event system, where passing multiple arguments are valid. That said, when firing these events in an async function, the multiple arguments seem to be lost.

More info can be found from @Lupus590 and the parent issue where the issue was initially discovered.

**Comment by Lupus590** [comment]
> That said, when firing these events in an async function, the multiple arguments seem to be lost.

That should say, when pulling the events.

It should be noted that ComputerCraft (CC) can filter for these events (which are passed to the coroutine manager via coroutine.yield's argument). Events are passed back to the coroutine via coroutine.resume usually have multiple values.

When I was testing (in response to cc-tweaked/CC-Tweaked#983 ) I noted that TSTL seems to want to run async functions as fast as possible, resuming the coroutine frequently. This causes issues for CC as some of the functions that user code can call need to pull specific events to know when when animations have finished. (I perhaps should mention that CC is a Minecraft mod.) Given that TSTL never feeds these events to its child coroutine on a TypeScript async function, CC's code has no way of knowing when the animation is finished and thus the code hangs until a watchdog timer expires and kills the script (part of making sure that CC doesn't use too many server resources),

**Comment by roobscoob** [comment]
Closing this. the initial issue described is a subissue of a deeper problem.
