### ISSUE TITLE
array.length doesn't transpile to #array if array comes as function argument.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [TypeScriptToLua/TypeScriptToLua#1203]
EXAMPLE
```typescript 
export function SetAtIndices(this:Grid, pos: number[], value:number){
	let w = this.width
	let n: number
	let l = pos.length
	for(const i of $range(1,l)){
		n = pos[i]
		this.data[floor(n / w) + 1][(n % w) + 1] = value
	}
}
```
translates to 

```lua
function ____exports.SetAtIndices(self, pos, value)
    local w = self.width
    local n
    local l = pos.length
    for i = 1, l do
        n = pos[i]
        self.data[floor(n / w) + 1][n % w + 1] = value
    end
end
```

**Comment by Perryvw** [comment]
What TSTL version are you on? This seems to work fine on the playground:
https://typescripttolua.github.io/play#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwMrAwCCMAkigCaZrADOAFDABaa0BcA4lJhQDRyR2cFEgC2AI2BQA2gF1+ANwCGAGyTA2IiVICUAbwBQASBWE4AdzgBeOM1YA6cz2bHT8FG2FjJUV2ZXWAhC09qYoAOYuRgjQ9Gg4tPCYcBAIcAAkUEoRwPQAjLwqOvrGRrg2gtKYsqV2IRRKMErSCCoQsbgA9BY6cADUcHmy0vS4AKQ9-YOygcpqwMYAvgaLQA

**Comment by Paolo-Oliverio** [comment]
in my package.json "devDependencies": { ..."typescript-to-lua": "^1.3.0",}

**Comment by Perryvw** [comment]
We cannot do anything if we cannot reproduce it, we need more information.

**Comment by Paolo-Oliverio** [comment]
> We cannot do anything if we cannot reproduce it, we need more information.

ok as soon I'll upload my project on github I'll update this issue for further investigation.

**Comment by Paolo-Oliverio** [comment]
Ok I have found the issue and it's not typescript to lua fault .
the actual code i'm transpiling has it's types deleted from a previous pass (babel) that I use for macros.
