### ISSUE TITLE
Calling a function of locally declared interface gives var.function() while the same function of the same interface when imported gives var:function()

### ISSUE THREAD

**Issue by Paolo-Oliverio** [TypeScriptToLua/TypeScriptToLua#1205]
in Utils.ts I have `export declare interface Utils {Work(this: void): void}`
while in otherscript.ts I have `import {Utils} from "Utils" ` If I get a var of type Utils and call Work() in lua I obtain `var:Work()` while if I do not import and declare the same interface locally to otherscript.ts I will get `var.Work()` that is what I'm trying to obtain as Work has "this" set to void.

**Comment by Paolo-Oliverio** [comment]
the difference is in the import path if you import with "Utils" it does `var:Work()` but if I use the relative path "./Utils" it transpiles to `var.Work()`

**Comment by Perryvw** [comment]
We are simply relying on TypeScript here. The correct way to import is "./Utils", without a correct import the type cannot be determined. Without the function we cannot determine if it has `this: void`.
