### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by dmarcuse** [TypeScriptToLua/TypeScriptToLua#121]
It would be nice to be able to use the spread operator. For arrays, it's pretty straightforward:

```typescript
const example = [ "a", ...[ "b", "c" ] ];
print(...example);
```

can be compiled to

```lua
local example = { "a", table.unpack("b", "c" }
print(table.unpack(example))
```

Objects, on the other hand, can't easily be implemented in a way that emulates their behavior in JS - the easiest way to implement it might be to add a function to `typescript_lualib`, so that something like this could be done:

```typescript
const example = { a: 1, ...{ a: 2, b: 3 } }
```
...might be compiled to...
```lua
-- typescript_lualib.lua
function TS_spreadobj(a, b)
	local c = {}

	for k,v in pairs(a) do c[k] = v end
	for k,v in pairs(b) do c[k] = v end

	return c
end

-- somewhere else
local example = TS_spreadobj({a = 1}, {a = 2, b = 3})
```

This introduces a bit of extra complexity - we'd need to separate the literal keys in the object from the spread operator and transpile them to separate expressions, and finally wrap it all in a call.

**Comment by apemanzilla** [comment]
Actually, even for arrays it seems a bit more complex than I thought. In Lua, `{ "a", table.unpack({ "b", "c" }), "d" }` results in `{ "a", "b", "d" }` for some reason.

**Comment by apemanzilla** [comment]
I've come up with an idea for how this could be implemented. Two new methods would be added to the lua library:

First, `TS_mergeArray`. It would take in lists as parameters (vararg) and output a new list with the concatenated results. An expression like `["a", "b", ...["c", "d"], "e"]` would be transpiled to `TS_mergeArray({"a"}, {"b"}, {"c", "d"}, {"e"}): all elements in the array literal would be passed wrapped in a table; except for cases where the spread operator is used, in which case the target is transpiled and passed directly. This should result in identical behavior with the spread operator in JS/TS.

The second method, `TS_mergeObject`, would operate almost identically, taking in tables as parameters and outputting a table combining all the values. The expression `{a: 1, ...{b: 2}, c: 3}` would be transpiled to `TS_mergeObject({a=1}, {b=2}, {c=3})`. This may require extra work to extract the necessary keys to construct the tables with.

Let me know if this approach sounds reasonable, and I can start working on implementing it.

**Comment by lolleko** [comment]
This is implemented for arrays in #176

**Comment by zaoqi** [comment]
@lolleko 
It won't work for String.
```
$ node
> [..."abc"]
[ 'a', 'b', 'c' ]
$ lua
> print(unpack{0,1})
0	1
> print(unpack("aa"))
nil	nil
```

**Comment by apiel** [comment]
I am still get an issue with spread operator:
```ts
const myvar = [{ VIEW: "hello" }, ...[{HELLO: 'world'}]];
```
Is generating: attempt to call a nil value (global 'unpack')

**Comment by Perryvw** [comment]
> I am still get an issue with spread operator:
> 
> ```ts
> const myvar = [{ VIEW: "hello" }, ...[{HELLO: 'world'}]];
> ```
> 
> Is generating: attempt to call a nil value (global 'unpack')

Sounds like your environment does not have the expected unpack function. What lua runtime are you running your code in, and did you configure your luaTarget to correctly match it?

**Comment by apiel** [comment]
Ooh, might be possible :-/ 
```sh
$ pkg-config --cflags --libs lua
-I/usr/include/lua5.4 -llua5.4
```
I am using lua5.4 embedded in my C++ app. 

and this is my `tsconfig`:
```json
{
    "$schema": "https://raw.githubusercontent.com/TypeScriptToLua/TypeScriptToLua/master/tsconfig-schema.json",
    "include": ["src/**/*"],
    "exclude": [],
    "compilerOptions": {
        "outDir": ".",
        "rootDir": "src",
        "target": "ESNext",
        "lib": ["ESNext", "DOM"],
        "moduleResolution": "Node",
        "jsx": "react",
        "types": [],
        "strict": true,
        "paths": {
            "@/*": ["./src/config/*"],
        },
        "baseUrl": ".",
    },
    "tstl": {
        "luaTarget": "5.4",
        "noImplicitSelf": true
    }
}
```

**Comment by Perryvw** [comment]
@apiel Translating this:
```ts
const myvar = [{ VIEW: "hello" }, ...[{HELLO: 'world'}]];
```
Should result in
```lua
myvar = {
    {VIEW = "hello"},
    table.unpack({{HELLO = "world"}})
}
```
for luaTarget 5.4. From your error it sounds like you have a global `unpack` instead of `table.unpack`. Are you sure your tsconfig is used correctly during your build? I tested locally and I'm getting expected output.
([playground link](https://typescripttolua.github.io/play#code/MYewdgzgLgBAtgTwG4EMBOMC8MDaBvGANQEkBRAdQC4YAiACwFMAbJkGmAXwBoYA6f-AAlSAGREB5agHIA7iDRMAJlI4BdVQG4AUAAc0ASzBQAFIlRocABlW8SFHmfQ4AjDeFjxASg1A))

**Comment by apiel** [comment]
Alright, I have some inconsistency between my lua cli and what I am using is the my C++ app. My cli is on 5.1 :-( Sorry for that.
