### ISSUE TITLE
where is LuaMultiReturn define？

### ISSUE THREAD

**Issue by qq1053831109** [TypeScriptToLua/TypeScriptToLua#1221]
error TS2304: Cannot find name 'LuaMultiReturn'

i dont have LuaMultiReturn , i find it in lua-types but not find

**Comment by Perryvw** [comment]
LuaMultiReturn is part of the [tstl language extensions](https://typescripttolua.github.io/docs/advanced/language-extensions), however they should automatically be included if you use lua-types. What project is having issues finding them?
