### ISSUE TITLE
Investigate why LuaLib doesn't build correctly without build-lualib.js

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#1232]
> I have no clue why it's not working tbh, it seems like only node build-lualib.js builds the correct dependency json, if I run `node dist/tstl.js` or `ts-node src/tstl.ts` it seems that the module dependency list is not being built correctly. My guess is that it's because for lualib modules we use a constant map at module level, and I'm afraid node might somehow be reloading it when we don't want to, but the way build-lualib is set up now somehow makes it work

[Perry on Discord](https://discord.com/channels/515854149821267971/600291243523702805/953397250971815976)

**Comment by GlassBricks** [comment]
I did a bit of debugging, the problem somehow has to do with the global Map being used in `transformations/utils/lualib.ts` (for getting used lualib features). 
Moving usedLuaLibFeatures to a property of TransformationContext itself somehow avoids the issue.

**Comment by GlassBricks** [comment]
Yep, that's whats happening. Changing lualib/tsconfig.json to use the built js file for the plugin instead of the ts file fixes it:
```
"luaPlugins": [{ "name": "../../dist/lualib-build/plugin.js" }]
```
