### ISSUE TITLE
can transform function into class ?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1242]
i have many function no in class,like this:
```typescrpit  unit.d.ts
    declare global {
        interface unit extends handle {  __unit: never; }
    }
    export function CreateUnit():unit;
    export function SetUnitColor( whichUnit:unit, WhatColor:number ):bool
```

in usually, i had to code this like:
```typescript
    let a_unit = CreateUnit()
    SetUnitColor(a_unit,225)
```

but,i want code like this:
```typescript
    let a_unit =  CreateUInit()
    a_unit .SetUnitColor(255)
```

how should I write *.d.ts ，then I can code like class , but build without class ?

**Comment by Perryvw** [comment]
Don't think this is supported by TypeScript. Maybe you could somehow make a TS transformer to help you do this, for now this is also out of scope for TypeScriptToLua.
