### ISSUE TITLE
Transpile _delete to delete

### ISSUE THREAD

**Issue by pjalsGit** [TypeScriptToLua/TypeScriptToLua#1248]
TSTL should transpile _delete to delete because Lua supports having table keys and variables that are named "delete".

For example:
```ts
// _G.d.ts

declare namespace fs {
	...
	export function delete(path: string): void;
	...
}
```
will error in JavaScript, but with this feature, you can replace delete with _delete like:
```ts
declare namespace fs {
	...
	export function _delete(path: string): void;
	...
}
```

Sorry if this is already implemented, it isn't mentioned in the docs.

**Comment by Cheatoid** [comment]
TSTL can't transpile `delete` to `_delete` out of blue; `delete` is reserved keyword in TS.

> it isn't mentioned in the docs

You're looking at wrong place. [Use this workaround](https://www.typescriptlang.org/docs/handbook/modules.html#export-statements).

**Comment by pjalsGit** [comment]
> You're looking at wrong place. [Use this workaround](https://www.typescriptlang.org/docs/handbook/modules.html#export-statements).

I'm not using imports or exports in the example I gave.

**Comment by Cheatoid** [comment]
> I'm not using imports or exports in the example I gave.

You actually are, `export function _delete(path: string): void;`
Don't export it like that, so remove `export`, and then use export statement to export _delete as delete.

**Comment by pjalsGit** [comment]
> You actually are, `export function _delete(path: string): void;`

Oh sorry, I guess I was tired or something lol

**Comment by pjalsGit** [comment]
Apparently you can replace `delete` with `'delete'`.
