### ISSUE TITLE
declare interface Object { } breaks standard lib functions

### ISSUE THREAD

**Issue by RobinKa** [TypeScriptToLua/TypeScriptToLua#1250]
Declaring an Object interface, eg.

```ts
declare interface Object {
}
```

will cause the standard library functions to transpile incorrectly.

Example: `Object.entries` transpiles to `Object:entries`

TSTL Version: `1.4.2`

**Comment by Zamiell** [comment]
try adding @noSelf annotation?

**Comment by Perryvw** [comment]
Cannot reproduce this one, need more info. I tried this:
```ts
declare interface Object {}

const entries = Object.entries({ a: 5, b: "6" });
```
[Playground link](https://typescripttolua.github.io/play/#code/CYUwxgNghgTiAEBLAdgFxDAZlMCDyARgFbirwDeAvgFDVgD2yAzmSGjIiE-ALzyEkwqAHRtUHLgApy8KAC54AVgA08AgoBEANg3xKASgDcQA)

And that code correctly translates `Object.entries` to `__TS__ObjectEntries()` as expected. I also tried to take your tsconfig from the aoemods template as I suspected something to be wrong there, but that also had no issue.

If you run into this issue again could you please set up an example repo somewhere I could check out and debug?

**Comment by RobinKa** [comment]
Couldn't reproduce it now either, but did happen in the past:
![image](https://user-images.githubusercontent.com/2614101/162619388-81ac535a-0b4f-45c9-9a8d-9400fae09ae8.png)
The cause might have been something else then, but closing for now.
