### ISSUE TITLE
如何创建新的基础类型并配置翻译？how create new type with transfrom?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1255]
I need create new base type like Array，useful but dont real in lua. new type has some function , i can write into flie like lualib_bundle.lua. but how can i use it in ts2l ? Had related configuration items ?
sorry for my poor English!
我需要创建多个新的基础的类，就像 Array 的数组一样，并不在lua原生中存在。我可以写出对应的声明文件，包括像 lualib_bundle.lua这样的转译文件。但是如何能让我写的东西在ts2l运行的时候使用呢？

打个比方：
```typescript 在ts中使用 array.push
let a:number[] = [1,2,3,4,5]
a.push(6)
```
```lua 编译成lua后 会变成
local a = {1,2,3,4,5}
__TS__ArrayPush(a,6)
```

这个 `a.push(6)` 并没有被翻译成 `a:push(6)`，而是`__TS__ArrayPush(a,6)`。 其中 函数`__TS__ArrayPush` 是在`lualib_bundle.lua`中定义的方法。我可以写所有类似于 `__TS__ArrayPush` 的函数，但如何能在ts2l后，自动使用我写的函数？
有相关的配置项吗？

**Comment by takegine** [comment]
special Handle

**Comment by Perryvw** [comment]
This is not really supported. You can just write new TS helper classes and use those. If you want custom transforms you can have a look at our transformer plugins: https://typescripttolua.github.io/docs/api/plugins

**Comment by takegine** [comment]
> This is not really supported. You can just write new TS helper classes and use those. If you want custom transforms you can have a look at our transformer plugins: https://typescripttolua.github.io/docs/api/plugins

Thanks for your answer, it looks like I need to write a plugin. But I'm not sure I need to write all the functions in the documentation, or just some of them? Whether to write `visitors` or `beforeTransform` ?
