### ISSUE TITLE
Could not resolve lua source files for require path?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1274]
![image](https://user-images.githubusercontent.com/64788603/169786433-2833be24-cfba-40af-9cb5-6c6daf851026.png)

the file ‘jass' is Engine built-in directory.So I create jass/*.d.ts only, without jass/*.lua.  How to cancel the prompt: Could not resolve lua source files for require path  jass/*.lua ?

**Comment by Zamiell** [comment]
Are you using TSTL for Warcraft 3?
I think the solution is that you have to make definitions with `declare`. 
Look how they define the API in [Dota2](https://github.com/TypeScriptToLua/Dota2Declarations) or [World of Warcraft](https://github.com/wartoshika/wow-declarations).

**Comment by Perryvw** [comment]
**Do you have to require these modules when writing regular Jass Lua?**

**If yes:** Your declarations should declare the Jass modules with `/** @noResolution */` as documented here: [noResolution compiler annotation](https://typescripttolua.github.io/docs/advanced/compiler-annotations#noresolution)

**If no,** add your types to your project via tsconfig.json, for example if the declarations come from a npm package:
```json
{
  "compilerOptions": {
    "types": ["@moddota/dota-lua-types"]
  }
}
```
Or if they are local you can just globally include them:
```json
{
  "compilerOptions": {
  },
  "include": ["declarations/**/*.d.ts"]
}
```

---
Alternatively, you can add the paths it is trying to resolve to your tsconfig.json with `noResolvePaths`, see [Configuration](https://typescripttolua.github.io/docs/configuration), but if you plan on distributing the declarations I would recommend against this method, it would force all your users to add this to their configuration.

**Comment by takegine** [comment]
> Are you using TSTL for Warcraft 3? I think the solution is that you have to make definitions with `declare`. Look how they define the API in [Dota2](https://github.com/TypeScriptToLua/Dota2Declarations) or [World of Warcraft](https://github.com/wartoshika/wow-declarations).

yes.i'm doing types for war3. and i had end the enum in commonJ。 i dont have the same mine with you about `declare`，because all the api are not global.
