### ISSUE TITLE
Namespace transpilation incorrect #bug

### ISSUE THREAD

**Issue by santutu** [TypeScriptToLua/TypeScriptToLua#1297]
It seems to  happen again when refactoring.

https://github.com/TypeScriptToLua/TypeScriptToLua/issues/94

![1](https://user-images.githubusercontent.com/28470293/176596758-aa0268c7-ce3f-460d-92cd-e7d2d5982bbb.PNG)
![2](https://user-images.githubusercontent.com/28470293/176596762-be30c679-61ab-411d-83a1-325ac214b2d4.PNG)

**Comment by lolleko** [comment]
This works as expected and matches TS behaviour. If you want to use a function from a namespace you have to export it.

https://typescripttolua.github.io/play#code/HYQwtgpgzgDiDGEAEAXaKkG8BQS9IDMBXYeFASwHtgkAPACgEotd82AnCFI9mgRgDcrPAF9swpBFoxK7DMVIVqSAJ5MWbDlx40ATELZix2GO3LAU9NFBQA6NY0ZDsAeheT27WSbMWr6WwZHZyA
