### ISSUE TITLE
can import module from npm ?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1305]
i want to public some module to npm , let the develop easily next time. i have no idea how to import the module ,and where it will be builtted.

**Comment by Perryvw** [comment]
You can `npm install` Lua packages from npm and use them as normal. Importing TypeScript or JavaScript npm packages is currently not supported. See https://typescripttolua.github.io/docs/external-lua-code for more info

**Comment by takegine** [comment]
do you mean then npm should inculde `aa.lua` with `aa.d.ts`  but `aa.ts` 。 so i need use ts2l transform aa.ts to aa.lua befor public. can ts2l output dts auto?

**Comment by Perryvw** [comment]
Yes, npm packages with `aa.lua` and `aa.d.ts` will work. See [our tests](https://github.com/TypeScriptToLua/TypeScriptToLua/tree/master/test/transpile/module-resolution) for examples. `Packages with just `aa.ts` will **not** work. You can get tstl to ouput declarations by setting `"declaration": true` in your tsconfig.json compilerOptions
