### ISSUE TITLE
findRequiredPaths match require keyword in comment of external lua code

### ISSUE THREAD

**Issue by pilaoda** [TypeScriptToLua/TypeScriptToLua#1330]
bad match pattern:
https://github.com/TypeScriptToLua/TypeScriptToLua/blob/7f1d4a55c9c742dc692f3b94e70e34755b884cd1/src/transpilation/resolve.ts#L307

comment example:
https://github.com/Egor-Skriptunoff/pure_lua_SHA/blob/6adac177c16c3496899f69d220dfb20bc31c03df/sha2.lua#L36

**Comment by Zamiell** [comment]
Looks like the regex needs to be updated to filter out comments.
In the case of the above provided link, it's just a single line comment with leading `--` characters.
But using a regex to detect the general case of a multiline comment with `--[` might be more tricky.

**Comment by pilaoda** [comment]
> Looks like the regex needs to be updated to filter out comments. In the case of the above provided link, it's just a single line comment with leading `--` characters. But using a regex to detect the general case of a multiline comment with `--[[` might be more tricky.

I have two ideas now:
1. Consider parse the lua code with some parser(https://github.com/fstirlitz/luaparse) other than plain text pattern match.
2. Remove all comments in lua code before pattern match.

**Comment by pilaoda** [comment]
https://github.com/Egor-Skriptunoff/pure_lua_SHA/blob/6adac177c16c3496899f69d220dfb20bc31c03df/sha2.lua#L129
This kind of require semantics is not matched, btw.

**Comment by Perryvw** [comment]
Workaround for now: add require path to noResolvePaths in tsconfig. For missed requires there is unfortunately no real workaround other than copying the lua files yourself manually/with a build pipeline/with a TSTL plugin.
