### ISSUE TITLE
Is there any way to generate "function xx()" instead of "local function xx()"?

### ISSUE THREAD

**Issue by jsyishan** [TypeScriptToLua/TypeScriptToLua#1335]
Hi, I'm making a Dota2 custom game, and I had some trouble in converting ts2lua.
Dota2 unit kv contains "vscripts" key, and it can be assigned to a lua script file, and we can write lua code like this: 
```lua
function Spawn( entityKeyValues )
    -- do something
end
```

Dota2 will call it when the unit is spawned.

So I want to do something like it but using TypeScript.
```TypeScript
// test.ts
function Spawn(entityKeyValues: any) {
    // do something
}
```
what I want is exactly like the code above

but I got
```lua
-- test.lua
local function Spawn(entityKeyValues)
    -- do something
end
```
As result, Dota2 won't call this local `Spawn` function.
And I tried add `export` keyword in TypeScipt, and I got
```lua
-- test.lua
function ____exports.Spawn(entityKeyValues)
    -- do something
end
```

It doesn't work as well

**Comment by Perryvw** [comment]
The functions will be global if you do not put any imports or exports in the file: https://typescripttolua.github.io/play#code/PTAEBcFMGdwOnNAUAMwK4DsDG4CWB7DUAZQAcBDAdwwApIM9wBPAaUiYDVyAbNGALlDkMTAJSgA3klAzQIUABN8oaPgC2kcAAtcGAOZIAvkA

If you do want to import/export stuff from the file, you can use the [registerEntityFunction](https://github.com/ModDota/TypeScriptAddonTemplate/blob/master/src/vscripts/lib/dota_ts_adapter.ts#L104) function from the tstl addon template. (See https://github.com/ModDota/TypeScriptAddonTemplate if you hadn't already).

With that you can import it and write:
```ts
registerEntityFunction("Spawn", (entityKeyValues: any) => {
    // do something
});
```
