### ISSUE TITLE
Docs: Configuration: tsconfig : Schema Link Broken

### ISSUE THREAD

**Issue by hepiyellow** [TypeScriptToLua/TypeScriptToLua#1352]
The following schema link in [this documentation page](https://typescripttolua.github.io/docs/configuration) is broken: 

 
 
 https://raw.githubusercontent.com/TypeScriptToLua/vscode-typescript-to-lua/master/tsconfig-schema.json",

I get "Not Found"

**Comment by Zamiell** [comment]
It's here: https://raw.githubusercontent.com/TypeScriptToLua/TypeScriptToLua/master/tsconfig-schema.json

**Comment by hepiyellow** [comment]
I tried you link, it exists, but I get this VScode warning:

"Problems loading reference 'https://json.schemastore.org/tsconfig': Unable to load schema from 'https://json.schemastore.org/tsconfig': getaddrinfo ENOTFOUND json.schemastore.org."

**Comment by Zamiell** [comment]
then your work is blocking that url or something

**Comment by Perryvw** [comment]
Fixed broken link in docs
