### ISSUE TITLE
Question: Can I hook into the watch mode - and listen on re-transpile event?

### ISSUE THREAD

**Issue by hepiyellow** [TypeScriptToLua/TypeScriptToLua#1355]
Hi,

I looking for a way to run `tstl --watch`, and to be able to trigger an action (notify another app that the bundle have changed) each time the code is re-transpiled (after the target bundle is updated).

Is there an API for this?

(I guess I can write an external watch for the target bundle)

**Comment by Perryvw** [comment]
Currently we do not have support for this, although there are plans to add an `afterEmit` plugin hook. For the currently supported hooks, see: https://typescripttolua.github.io/docs/api/plugins

**Comment by DoctorGester** [comment]
`tsc-watch` works. You can specify a custom compiler there like `typescript-to-lua/dist/tstl` and an `onSuccess` script

**Comment by Perryvw** [comment]
This should be supported nowadays by our current plugin system
