### ISSUE TITLE
Can I compile a single ts file

### ISSUE THREAD

**Issue by oayx** [TypeScriptToLua/TypeScriptToLua#1356]
There are several thousand files in total, and it will take 2-3 minutes to convert them all. So I want to do an incremental conversion, which is to convert only the modified files

**Comment by Perryvw** [comment]
If you run `tstl --watch` it will compile everything at the start, but then it will keep watching for file changes and only change the changed files. 

We do support translating single files, but if that file is referring to to some extra dependencies it will not work out of the box. You can use our API (see https://typescripttolua.github.io/docs/api/overview) to set up a custom build pipeline.
