### ISSUE TITLE
typeof Objject.keys error?

### ISSUE THREAD

**Issue by takegine** [TypeScriptToLua/TypeScriptToLua#1357]
```typescript
const enum AA {
    z = 1,
    x = 2,
    c = 3
}
let q : Record<AA,any> = {}
q[AA.z] = 12344

let w = Object.keys(q)
```
the `typeof w` should be `AA[]` ， but I got `string[]`

**Comment by Zamiell** [comment]
no

https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgQTTA3gKBvmALxgF4YBGAGjwIA9SYAmagmYBgZhwF8cAbOLACOALhgAlOKABOAEwA8GSgEMwATwB8DLLyEBtDADpCAXQblGHACxWc-QTADuDAPIAjAFZSohgNZw1CAAKIQBKHCA

**Comment by Perryvw** [comment]
In JS, all keys are turned into strings, so `Object.keys` always returns a `string[]`. This is just default TypeScript, and not related to tstl.
