### ISSUE TITLE
Can't access "package", it is a reserved keyword

### ISSUE THREAD

**Issue by hepiyellow** [TypeScriptToLua/TypeScriptToLua#1359]
`package` in lua is a table that holds the `path` property.

In TypeScript, `package` is a reserved keyword.

So I can't access `package` global variable, I get a TS error :

```
Identifier expected. 'package' is a reserved word in strict mode.ts(1212)
```

**Comment by Zamiell** [comment]
You can access it with `_G.package`.

**Comment by lolleko** [comment]
Closed as this is something we can't fix and a workaround exists (`globalThis.package` => `_G.package`  or not using strict mode)
