### ISSUE TITLE
Can the generated if statement not be changed to goto

### ISSUE THREAD

**Issue by oayx** [TypeScriptToLua/TypeScriptToLua#1362]
![QQ截图20221031095651](https://user-images.githubusercontent.com/20868119/198915758-3671d49f-0437-4f15-a595-108db758e02b.png)

![QQ截图20221031095555](https://user-images.githubusercontent.com/20868119/198915678-4be74a28-d948-466a-aefb-cb19ddc29177.png)

**Comment by oayx** [comment]
Because I wanted to do secondary development in lua, but now there are so many Gotos generated that it doesn't look intuitive

**Comment by Perryvw** [comment]
no
