### ISSUE TITLE
Modules do not export declarations (or do not import them correctly)

### ISSUE THREAD

**Issue by iliasHDZ** [TypeScriptToLua/TypeScriptToLua#1373]
Say we have 2 files:

`test1.ts`:
```ts
import { print } from "test2";

print("Hello, world!");
```

`test2.ts`
```ts
export declare function print(this: void, ...args: any[]): void;
```

They will transpile into the following:
`test1.lua`
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
local ____test2 = require("test2")
local ____print = ____test2.print
____print("Hello, world!")
return ____exports
```

`test2.lua`
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
return ____exports
```

In the lua code, you can see that `test1.lua` is trying to get a function `print` from `test2.lua` yet `test2.lua` doesn't actually export anything. Is this normal? Is that how TypeScript normally works or is there something wrong here? If so, I would absolutely appreciate it if it could be fixed.

**Comment by Zamiell** [comment]
typically you declare stuff in a declaration file (.d.ts), not a typescript file (.ts)

to start with, look at what the docs do, which is different from what you are doing here: https://typescripttolua.github.io/docs/external-lua-code

merry christmas : )

**Comment by Perryvw** [comment]
Indeed normally declarations are in a `.d.ts` file, indicating that file does not create any output code.

Then the content of your .d.ts file also matters: If you put `export` like you did, that indicates that function needs to also be imported (required). If it is ambiently available in your environment, remove the `export`, and _all_ exports in that file, to indicate this file is _not_ a module to be imported.
