### ISSUE TITLE
Minor Bug that Causes Invalid Lua Code to be Generated

### ISSUE THREAD

**Issue by Feuermurmel** [TypeScriptToLua/TypeScriptToLua#1375]
The following TypeScript…

```typescript
null()
```

Is translated to the following Lua…

```lua
nil(nil)
```

…, which is syntactically incorrect.

(playground: https://typescripttolua.github.io/play#code/HYVwNmAUCUQ)

`null()` is of course senseless code. I found this while trying to provoke a runtime error while debugging. But I still think there is some merit in making sure that the generated code is always syntactically correct.

**Comment by Zamiell** [comment]
> I found this while trying to provoke a runtime error while debugging

use `throw new Error` to provoke a runtime error while debugging, in the exact same way that you would with normal typescript code
