### ISSUE TITLE
Exported `async` function is not behaving the same as local

### ISSUE THREAD

**Issue by Cheatoid** [TypeScriptToLua/TypeScriptToLua#1380]
[Relevant discussion at Discord](https://discord.com/channels/515854149821267971/600291243523702805/1061792332665597972).
**main.ts**
```ts
import { ExportedAsync } from "./other";
function LocalAsync(num: number): Promise<number> {
    return new Promise<number>((resolve, reject) => {
        resolve(num * 2);
    });
}
(async () => {
    print("LocalAsync result:", await LocalAsync(3));
    print("ExportedAsync result:", await ExportedAsync(3));
})();
```
**other.ts**
```ts
export function ExportedAsync(num: number): Promise<number> {
    return new Promise<number>((resolve, reject) => {
        resolve(num * 2);
    });
}
```
Try it yourself... The functions `ExportedAsync` and `LocalAsync` are exactly identical, yet the output is different, because for unknown reason... Why?
> LocalAsync result:      6
> ExportedAsync result:   table: 0x3b97b018

A sample project, including transpiled Lua code in a zip file:
[exported-async-bug.zip](https://github.com/TypeScriptToLua/TypeScriptToLua/files/10369803/exported-async-bug.zip)

**Comment by Perryvw** [comment]
Reason for this is using `"lualibImport": "inline"`, causing multiple definitions of __TS__Promise to exist (one for each file). Passing a promise from one file to another will cause it not to be recognized as a promise, breaking `Promise` and `await` logic for that table.

Accepted solution is to use `"lualibImport": "require"` instead. Inlining should not be used unless you have very good reason to (i.e. if you are the tstl website playground).

I had a look at replacing `x instanceof __TS__Promise` with something that works across files, but that seems to be a nightmare, so unless we find a better reason to fix this, I'm leaving it as is.
