### ISSUE TITLE
@noSelfInFile configuration option is ignored for Function

### ISSUE THREAD

**Issue by Grafu** [TypeScriptToLua/TypeScriptToLua#1387]
`@noSelfInFile` configuration option is ignored for Function

After upgrading typescript-to-lua to never version I noticed that my code broke. I investigated and found out that @noSelfInFile directive is ignored for Function type. I am now unable to use Function type and have to write `(...args: any[]) => any` explicitly everywhere where I used to write `Function`. Please see this reproduction example in Playground:

https://typescripttolua.github.io/play/#code/PQKhAIAEDsHsGUCmAbAZgSWgMQJbMeGMAFDEDGs0AzgC7ioCu0ZAQgJ4BqAhsg4gFzgASogoAnACYAeWmJzQA5gBpwWJmRo5KAPnABecAG9i4U+ABEACxTJY5wQAoAlPt0BGJcQC+AblIVqOkZmfXp1dm5eRABtKxs7AF0-YLIHNyd-Slow5giePgAmQRFxaVl5ZXAHADparjEFKkEuaDZohJc9XRa2XQNjMwtrZFt7Ks73Ty9MwJyyAtCUvKiC2OHRpOIUgrSMoA

**Comment by Grafu** [comment]
![image](https://user-images.githubusercontent.com/11540828/213882528-79440968-194b-4ad1-bf28-4da5b39afde0.png)

**Comment by Z3rio** [comment]
The issue here seems to be in this function: https://github.com/Z3rio/TypeScriptToLua/blob/e697c6e3bc852049e80c5d6bf388c6a103634ca6/src/transformation/visitors/call.ts#L289

The one using the `Function` type returns undefined, whilst the other one returns the actual function 🤨
