### ISSUE TITLE
[TSTL config] TSTL 'extension' config field affects 'require' statements in resulting code

### ISSUE THREAD

**Issue by Neloreck** [TypeScriptToLua/TypeScriptToLua#1394]
Related to: https://github.com/TypeScriptToLua/TypeScriptToLua/pull/1229

## Problem:
When adding custom extension config, resulting code require statements have `*.extension` ending. Lua does not know how to handle custom extensions in this case and tries to load `*.extension` modules instead. Causes runtime exception.

In my case I just used post-build step with file renaming `(*.lua -> *.script)`, but since project compile time started taking more time I wanted to use --watch flag which requires correctly working 'extension' field.

- I have noted that `lualib_bundle` file has correct .script extension and imported in a correct way (without .script part)
- I assume that it may be related to `compilerOptions.paths` aliasing config in `tsconfig.json`

Providing alias config part just in case:
```json
{
  "compilerOptions": {
    "paths": {
      "#/*": ["../../cli/*"],
      "@/*": ["../*"]
    }
  }
}
```

## Details

1) Add extension to the config file (tsconfig.json)

```json
{
  "tstl": {
      "extension": ".script"
    }
}
```

2) Write some import statements
```typescript
import { XR_object_factory } from "xray16";

import { LuaLogger } from "@/mod/scripts/utils/logging";

const logger: LuaLogger = new LuaLogger("register");

register_classes = (object_factory) => {
  logger.info("Register classes:");

  const { registerGameClasses } = require("@/mod/scripts/registering/class_registrator");

  registerGameClasses(object_factory);
};

```

3) Build it and get result:
```lua

local ____lualib = require("lualib_bundle")
local __TS__New = ____lualib.__TS__New
local ____exports = {}
local ____logging = require("scripts.utils.logging.script")

local LuaLogger = ____logging.LuaLogger
local logger = __TS__New(LuaLogger, "register")

register_classes = function(object_factory)
    logger:info("Register classes:")
    local ____require_result_0 = require("scripts.registering.class_registrator.script")
    local registerGameClasses = ____require_result_0.registerGameClasses
    registerGameClasses(object_factory)
end

```

## Expected result / result without extension config field usage:

If I build without extension config, I get following result:
```lua
local ____lualib = require("lualib_bundle")
local __TS__New = ____lualib.__TS__New
local ____exports = {}
local ____logging = require("scripts.utils.logging")

local LuaLogger = ____logging.LuaLogger
local logger = __TS__New(LuaLogger, "register")

register_classes = function(object_factory)
    logger:info("Register classes:")
    local ____require_result_0 = require("scripts.registering.class_registrator")
    local registerGameClasses = ____require_result_0.registerGameClasses
    registerGameClasses(object_factory)
end
```

**Comment by Neloreck** [comment]
@Perryvw 
Thank you for fixes --- checked and it started working.

Small note: probably when statements removal from require happen, it checks extension by raw string from config and slices part  of it. TS config supports both '.ext' and 'ext' variants, but with simple 'ext' build is successful but dots remain in the statement and cause runtime exception

![image](https://user-images.githubusercontent.com/18573775/218895580-a318603c-d56a-4fe9-93a0-af3ef3063d0d.png)

**Comment by Perryvw** [comment]
Oops, thanks for testing. I'll reopen this issue to track this.
