### ISSUE TITLE
sort is not stable

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1403]
See [this TSTL playground snippet](https://typescripttolua.github.io/play#code/GYVwdgxgLglg9mABDAzgORAWwEYFMBOAFAG4CG+Mp2ANrgFyLgDWYcA7mAJQNkVW3IUiMFjz5EAbwBQiRPlxQQ+JFACeAB1wlylGrk6IAvMcQAiETgKmA3FIC+UqaEiwEggMpQKYAOba+egzMrBzciLy6AqiIKF4wvpIycgpKKhpaEfz6Riamsd4+NvaOztDwSKgAKln+kfSMYCzsXDw6WYKIADIgpACypOoAPACCYKpocFBoMNQANA1NHAB8ibLyisqIapq1WQbGhmZQWUUOTuBlbuT4pKqVcJ4FhNe3QY0hYADaALph+fE+VbIYCIZ74G6qAB0tF8UAAFjlDgAGAzSWRrFKbUw-IqyM6yCAIWIxOK+ISHF5QzADQiEXC0TC4MBQfYrKBwf6+OkMpkszi2AlEqCIQmYanuXDqcikKC4AAmjwB5JJBRQkIAVnB4oRTPNTPykutUogAAafAAkElF4sl0tlCtJPhQdm+JtsZ1KriQKDg+Cmvup1Geb0WYHm2BDHzCAFoAIyIAA+iCRicQ8bRwNBAEJUBhLERSAYAGRFxA5lCKrmF1FJWQEfC+nUAMVIM3lWzgMV9wpQ8QguC2cIHwBg+GJZGoIAHbFIQlYwtIwlEBEQvpVAMh+oFiHxmcI5bzYkI2GLpfLlb8J5r6MQ9cbphbbblHa7fpifYH8IHKFwhLAz4nKdEBnOdJkQRcLDEVdxE5HxNwNPFHFkGAQWeRBBkQE8gQxDYkDjbddxQ0FFxWLCMxw41YwIpDklw5N3UcAB6AAqZiZGYxAAAl6U0cRPXKF8fTfUgkEpVcQTgbB1V-KAhGwVRVzAAc4BBL9VykmTECYXBVDVdj2MQJs11wAAPUhMHUWg6H0xAOJNezZIMv9iUwVRhnBW4jEQT4DNkNEOJvMBzPqUxSGoGB+11Xz0VIHx6gAZiRWZorsZLbPRfyb2EYKGFMbBJKi9Kb1i+oACYkpStKOO+AUONc9yIUhISoEIZqAHkNOgBrbgAIVUABpHSdRK-UELs+z2MY84XAE9rOqgbrVD6wbVEIbTVAYWDr1o41gwWD5w0jZoY3jJMUyTeNDBWci93Lao9GeThtpvO8iFrLKTUfWhn3ZV8FyQSTpOgTCFLU9bxLMS11rsUx30gT8h0QEcx2FelcEZZlgNnYQwMXY49EhE00qyhD0V3ZDULumor2w9FXsId6b0+1tvsE7twIB+aQcHAdwZUyGJGh2He3hnmYl-BBnzRjHhRAnGFy2LJCeJm9ScQ97nIXAA1MKgIpSE4pa9a1ZFIVMJ1ycB0ObADYUNadINd6jU2ZqJnwQNngtqdwy9-QCIYqRNcQXoAE0AH1hgAJUj4YQ68ny-PeoLGVy4ZwsilXwLihhYwqvFiZu5OQp6grM5KnO853Auk5yswAGEZThVRCpi7O00r1KkkL2vTAAEQQMK5Rb2Ry8QABWYnO5qxx1G8FrKXuC9CFDiPo9jyFqXUWlpd5Vlbx5ZlISLp6DRXqOY5Dpru1a7sOqBhaPKWgahtCuLRtsWf4nnx-F8dZfw-PuvTe28D4siMCsHeh9j5PVsEAA
), which proves that the transpiled sort method is not [stable](https://stackoverflow.com/questions/1517793/what-is-stability-in-sorting-algorithms-and-why-is-it-important).

```
[Alice, Bob, Cathy, Donald] 
[Donald, Cathy, Bob, Alice] 
```

According to the JavaScript spec, sorting is [supposed to be stable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort), so this is a bug in TSTL.

For example, here's the same code snippet [on the TypeScript playground](https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAgIYCd2oJ4BUEDKM6cEA5gBQZbYBcyAzsaWQNoC6AlPUyecgG9gyZHBDIqmHADoANgFNyMABbIAvBuQAGToOEjk6eTDDoUAIg7mA3PoC+wfVCRNGzcg3Vop2aQFtUAAcKCnkFP0UYXTUAPmQw+QiIGGkYQndKTk5bEWcIV2c-AIJ5QIxUGHkAEyI+Mk81NzqGaQArBFIKcwAaZHNs-SMTM2QAA1YAEgFC4tLyypqMhjt2UdsHUEhYRBQGBHQYADl9gNkqekgAawgEAHcIXoAjC4hru4huZABaAEZkAB9tADkH8hCIxBIYNhAvIEOJUMgAISacwQMB+R7ydDmZAAMlxyChMLhaCRKN4LH6egMhOU6DuyAg8luyAAoph9l0AGKoOAKKqEhCMfYwRikKDyWmSkBwdCuABuqFkYElt1QnhuooRaIxWOQ+yaLGk-RyyA24PEFCJsPEjzJjVR6Mx2LxBOtJLtyIdFPIVLBBhU9JZTJZ7Pp6G5vP5guFBzF0ElKklDHkeQFiuVqvVjIQWsZTr1Bp9ZGNAxE5tEloRAB5kI9dP6RENTChfqaKxCqMg4vXqQZmyMfu3HE3jC3tOtHAB6ABUM+EM+QAAkwjD0MhwNB4EgY3s46gUNQcPrxAhHq1UzBPI9sPqmSepfrz5fkJd5NgWguF8guQb5AAPVA-ECBRaC-ZBF1GKCr2-PJXD8bAAEEfC8VhvxEMFFxpCAgPkehzCVOAJR6dCDFQMg8OQABmLRulIuw6IggxMJpRlcPwx4zxIpiaXIyiACZaPoxjF3YHJFwQ5CaGkPcYAoWSAHln1gKScAAIWwABpd8uj4-oy0gqCFynTYtx2WMYCUi8VJ8DTtOwCg3zoQ1yAbQYxxGc5kCuG57ieF43nuT5fmBLRgT+WI+wtSFoRtUkvT6M9rJgHF-kBBENEaNFZFkNzWNpINGWZNkOQjfR8tGHk+WqXcRTQFAkpfG9Hych9zCmJy7BxBhxUTZRpVlVwEiSUU1Q1XN6qfZLpFGRjWLLAwK2iq1Yo9e1EuUlKAUBO1MvzHK8tYwMGRDErwwocrWMqqMarSCzJsa2A61vJNX3fNqOvfLr4wlR8UzTeJwkiZAxpzLUGs2ma5ppBbyxHAw4K1AA1JUVS8LtswAJVTfYqmrYteh894Yk4VgnLEy7EbrFHM3Ru0sZx9A8YJ7zXl8iASbJ98KcugddhFY50FOKgaZVJ5RfkBa7EnYAqYAWQATQAfUQzHMcQhXUP0Rs2IifDENkIj5G4siKPoH4hPLOadZwvW+jUrjobQM2QUts1rcu23KPMABhCplGwE2RD4823YY7XPfYvoABEkCVKog+dyiAFY5vDnm4IQBQ5AQSgjzwdI6goRWVbVjX-CCEJhsiaI4mr5JpC9rIBhL1X1YVmSRXkkUrMvVTsDsnSCIo-TbEz7PZFzyQaHwWoWGL5W2-LgJglCIHklrwHEkiRvcOb2wgA
):

```
[Alice, Bob, Cathy, Donald]
[Donald, Alice, Bob, Cathy]
```

This is really important because it causes bugs that are extremely difficult to track down and reproduce.

**Comment by Perryvw** [comment]
We simply depend on Lua's table.sort, which is not stable. We have no desire to reimplement something as fundamental as sorting. If you really need a stable sorting algorithm I suggest you implement your own.

**Comment by lolleko** [comment]
We could add this to the limitations in the docs.

**Comment by Zamiell** [comment]
Yeah, that's a pretty huge footgun that should be documented.
