### ISSUE TITLE
error TSTL: Decorator function cannot have 'this: void'.

### ISSUE THREAD

**Issue by pilaoda** [TypeScriptToLua/TypeScriptToLua#1416]
This error throw when I enable the `noImplicitSelf` in tsconfig.json. 
I don't understand why `this` is necessary for decorator functions.
Should we add `this:any` for all decorator function? It may make the `noImplicitSelf` option more inconvenient.

**Comment by Perryvw** [comment]
> Should we add this:any for all decorator function?

Yes

> It may make the noImplicitSelf option more inconvenient.

`noImplicitSelf` was never meant to be convenient. It is a deviation from normal behavior that is not recommended unless you have a really good reason to do so.
