### ISSUE TITLE
Is there any method to use ORM like TypeORM?

### ISSUE THREAD

**Issue by zeroxer** [TypeScriptToLua/TypeScriptToLua#1432]
Or any other methods to use database.

**Comment by Zamiell** [comment]
from [the docs](https://typescripttolua.github.io/docs/external-code):

> Importing JavaScript or TypeScript packages from npm will not work. This means that it is impossible to use common JavaScript/TypeScript libraries like [Underscore.js](https://underscorejs.org/) and so on.

your best option is to try to find a lua library that does it, or you could write it yourself from scratch

**Comment by developer239** [comment]
@zeroxer It probably doesn't make sense to do anything more complicated than write (frontend) scripts. Everything else should be handled from inside C++.

**Comment by Perryvw** [comment]
Indeed you will need to write declarations for your database library (depends on your environment), or use declarations that someone else already wrote for you. If you really want an ORM, your best bet is finding a Lua ORM (google gave me this: https://github.com/wesen1/LuaORM - haven't looked into it deeper), and then writing declarations for that library.
