### ISSUE TITLE
can't make imports work

### ISSUE THREAD

**Issue by developer239** [TypeScriptToLua/TypeScriptToLua#1433]
**Info**:

```
libc++abi: terminating with uncaught exception of type sol::error: sol: runtime error: ...not/IdeaProjects/project-folder/dist/index.lua:6: module 'custom-module' not found:
	no field package.preload['custom-module']
	no file './custom-module.lua'
	no file '/usr/local/share/lua/5.4/custom-module.lua'
	no file '/usr/local/share/lua/5.4/custom-module/init.lua'
	no file '/usr/local/lib/lua/5.4/custom-module.lua'
	no file '/usr/local/lib/lua/5.4/custom-module/init.lua'
	no file './custom-module.lua'
	no file './custom-module/init.lua'
	no file './custom-module.lua'
	no file '/usr/local/lib/lua/5.4/custom-module.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './custom-module.so'
	no file './custom-module.so'
```

```
// src/custom-module.ts
export const helloWorld = () => 'Hello World!'

// src/index.ts
import { helloWorld } from './custom-module'

const main: IMain = {
  onRender: () => {
    helloWorld()
    console.log('done')
  },
  screen: {
    width: 600,
    height: 600,
    x: 0,
    y: 0,
  },
}
```

This is how it compiles:

```
-- dist/custom-module.lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.helloWorld = function() return "Hello World!" end
return ____exports

-- dist/index.lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
local ____custom_2Dmodule = require("custom-module")
local helloWorld = ____custom_2Dmodule.helloWorld
local main = {
    onRender = function()
        helloWorld(nil)
        print("done")
    end,
    screen = {width = 600, height = 600, x = 0, y = 0}
}
return ____exports
```

**Question:**

From what I just learned it seems that even though Lua is scripting language - by default it doesn't look for "modules" (required files) inside modules directory (dist) (I can't imagine how is that a good idea like do people really write all of their scripts inside `usr/local/lib/lua/5.4/` 🤣) 

How do I make this work? Is there some `tstl` config that I missed? 🙏

**Comment by developer239** [comment]
I set `luaBundle` to generate single file but now I get a different error:

```
"tstl": {
    "luaTarget": "JIT",
    "luaBundleEntry": "src/index.ts",
    "luaBundle": "bundle.lua"
}
```

```
[sol2] An error occurred and panic has been invoked: attempt to index a nil value
libc++abi: terminating with uncaught exception of type sol::error: lua: error: attempt to index a nil value
```

**Comment by developer239** [comment]
I have this code in C++:

```
int screenWidth = lua["main"]["screen"]["width"];
int screenHeight = lua["main"]["screen"]["height"];
int screenX = lua["main"]["screen"]["x"];
int screenY = lua["main"]["screen"]["y"];
```

It seems that TSTL makes the `main` variable local and inaccessible. 

`noImplicitGlobalVariables` doesn't have any effect. Any ideas how do I access the `main` variable?

**Comment by Perryvw** [comment]
> libc++abi: terminating with uncaught exception of type sol::error: sol: runtime error: ...not/IdeaProjects/project-folder/dist/index.lua:6: module 'custom-module' not found:
> 	no field package.preload['custom-module']
> 	no file './custom-module.lua'
> 	no file '/usr/local/share/lua/5.4/custom-module.lua'
> 	no file '/usr/local/share/lua/5.4/custom-module/init.lua'
> 	no file '/usr/local/lib/lua/5.4/custom-module.lua'
> 	no file '/usr/local/lib/lua/5.4/custom-module/init.lua'
> 	no file './custom-module.lua'
> 	no file './custom-module/init.lua'
> 	no file './custom-module.lua'
> 	no file '/usr/local/lib/lua/5.4/custom-module.so'
> 	no file '/usr/local/lib/lua/5.4/loadall.so'
> 	no file './custom-module.so'
> 	no file './custom-module.so'

It lists all the locations it looks for the file. I'm guessing it cannot find custom-module because it is in the `dist` directory? Make sure you figure out what the root directory of the lua project is where these paths are relative to. LuaBundle would indeed also resolve this issue because there are no more  imports.

I am not sure why the bundle is giving you a nil index error, the code looks alright as far as I can tell. It's hard to see without knowing the line number where the error happens.

> I have this code in C++:
> 
> ```
> int screenWidth = lua["main"]["screen"]["width"];
> int screenHeight = lua["main"]["screen"]["height"];
> int screenX = lua["main"]["screen"]["x"];
> int screenY = lua["main"]["screen"]["y"];
> ```
> 
> It seems that TSTL makes the `main` variable local and inaccessible.
> 
> `noImplicitGlobalVariables` doesn't have any effect. Any ideas how do I access the `main` variable?
> 
> Or how do I make the `main` variable `global`?

You have to somehow tell TS that this variable exists globally and can be assigned to. You will usually use declarations for this that describe your lua environment. See: https://typescripttolua.github.io/docs/advanced/writing-declarations

I would expect a declaration file like:
```ts
declare var main: {
    screen: { x: number; y: number}
}
```
and code like:
```ts
main = { screen: { x: 10, y: 20 } };
```

[See example in playground](https://typescripttolua.github.io/play#code/CYUwxgNghgTiAEA3W8C2UCWA7AXPA3gFDwnwDOYcIuB8AHnlgK6oBGIMA3PAJ6MvsYAX0IjC6bPAC8tClRr56eAIwAGADS88AJlXwh+zoSA).
