### ISSUE TITLE
@tupleReturn does not work anymore

### ISSUE THREAD

**Issue by 3axap4eHko** [TypeScriptToLua/TypeScriptToLua#1443]
[Here is the playground link](https://typescripttolua.github.io/play/#code/PQKhCgAIUglBTALgVwE4DsDOkC2yA2iAlgA77yQBuAhvsvJlDAAIpnwIoZPDgAm8AMb5qqCgDNk6QcQD26SG3IAKAJQAuSAG10yHACN4qADSRdBowF0A3OHDlE26qf2XIAXkXJ2a2+FAQ0HBIaFiQ1IrU+uThqKjUAJ6QgvKI1EToGQDmigDusmZ6hqiM0LwCwqISUjJE8rHxCWqaOkVGpubFNnYO2oKmfG6eoo2+-sCQ+LKCtMkDHpBSJNSCANbKI4lqqkA)

**Comment by lolleko** [comment]
@tupleReturn was deprecated in #1075 and removed in #1090 use LuaMultiReturn instead https://typescripttolua.github.io/docs/advanced/language-extensions#luamultireturn-type
