### ISSUE TITLE
Static blocks in classes are skipped

### ISSUE THREAD

**Issue by rhazarian** [TypeScriptToLua/TypeScriptToLua#1447]
https://www.typescriptlang.org/docs/handbook/2/classes.html#static-blocks-in-classes

Static blocks are skipped when the code is transpiled to Lua.

Ex.
```
class A {
    static {
        console.log("Hello world")
    }
}
```
The code doesn't output anything in TSTL while it prints "Hello world" in TS.

TSTL playground: https://typescripttolua.github.io/play/#code/MYGwhgzhAECC0G8BQ1XQgFzBglsRKaRwA9gHYQkgCmAdCCQOYAUARABLUgPQDuJAJxAATVgEpCqAL5IZQA

TS playground: https://www.typescriptlang.org/play?ssl=6&ssc=1&pln=1&pc=1#code/MYGwhgzhAECC0G8BQ1XQgFzBglsRKaRwA9gHYQkgCmAdCCQOYAUARABLUgPQDuJAJxAATVgEpCqAL5IZQA

**Comment by Perryvw** [comment]
References:
* https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-runtime-semantics-evaluateclassstaticblockbody
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks
