### ISSUE TITLE
BUG/CAVEAT: Object.keys ignores keys with undefined values

### ISSUE THREAD

**Issue by hepiyellow** [TypeScriptToLua/TypeScriptToLua#1448]
#### In TypeScript (and Javascript)

```typescript
Object.keys({ a: 1, b: undefined }).length // equals 2
```

#### With TSTL

```typescript
Object.keys({ a: 1, b: undefined }).length // equals 1
```

## Analysis

The transpiled Object.keys function is defined as:
```lua
local function __TS__ObjectKeys(obj)
    local result = {}
    local len = 0
    for key in pairs(obj) do
        len = len + 1
        result[len] = key
    end
    return result
end
```

In LUA, `pairs` which uses `next` skips keys that have `nil` values.

This seems like a Caveat that should be mentioned in [Caveats section](https://typescripttolua.github.io/docs/caveats) of TypescriptToLua Docs.

### Or Maybe We Should Solve it
I found this page ["Storing nils in Tables"](http://lua-users.org/wiki/StoringNilsInTables) that suggests a few solutions.

Should we implement the **"`nil` Placeholder"** solution ?

**Comment by hepiyellow** [comment]
@Zamiell The Docs section you mentioned is mainly about that `null` and `undefined` are indistinguishable.

It does mention iteration over a table with `null` and `undefined` values. And does say that in the example, we would get only `someProp1`. I missed that. 
There is actually a mistake there, since it says:
> instead of both someProp1 and someProp2 like we would in a JavaScript/TypeScript program.

Which is wrong, in Javascript we would get all 3 keys.

**So I think that the fact that you can NOT access keys of object properties with `null/undefined` values is a MAJOR difference between Typescript and LUA, and  deserves a separate subject (headline) in the Docs.**

**Comment by hepiyellow** [comment]
I don't think this is a duplicate of https://github.com/TypeScriptToLua/TypeScriptToLua/issues/614

It needs a different solution.

**Comment by Zamiell** [comment]
#154

**Comment by Perryvw** [comment]
This is expected behavior due to how tables and `nil` work in Lua. Zamiell's update to the caveats section sums it up pretty well.

There are currently no plans to distinguish between `undefined` or `null`, if you really want some kind of special null-ish value, I suggest you define it yourself.
