### ISSUE TITLE
Decorated methods disappear from class definition in 1.16.0 experimentalDecorators

### ISSUE THREAD

**Issue by Perryvw** [TypeScriptToLua/TypeScriptToLua#1453]
Decorated methods are no longer defined in output lua when using experimentalDecorators in 1.16.0. Probably due to the refactor of how decorators work.

Exmple code:
```ts
function decorator<Class>(
  target: Class,
  propertyKey: keyof Class,
): void {}

class Foo {
    @decorator
    public method2() { return 4; }
}

export const result = new Foo().method2();
```

Leads to output:
```lua
local Foo = __TS__Class()
Foo.name = "Foo"
function Foo.prototype.____constructor(self)
end
-- Expecting method 2 implementation here??
__TS__DecorateLegacy({decorator}, Foo.prototype, "method2", true)
____exports.result = __TS__New(Foo):method2()

**Comment by TechArtLife** [comment]
- Environment
```json
  "devDependencies": {
    "lua-types": "^2.13.1",
    "typescript": "^5.1.3",
    "typescript-to-lua": "^1.16.2"
  }
```

TS still compile error.
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/91841856/1e82b29b-ccfa-43d2-8f8e-05cc97f63443)

while output seems right.
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/91841856/b6239e70-b02f-47db-93a4-ce9289e8ebed)
