### ISSUE TITLE
Method decorator compile error while lua ouput seems right

### ISSUE THREAD

**Issue by TechArtLife** [TypeScriptToLua/TypeScriptToLua#1460]
- Environment
```json
  "devDependencies": {
    "lua-types": "^2.13.1",
    "typescript": "^5.1.3",
    "typescript-to-lua": "^1.16.2"
  }
```

TS still compile error.
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/91841856/1e82b29b-ccfa-43d2-8f8e-05cc97f63443)

while output seems right.
![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/91841856/b6239e70-b02f-47db-93a4-ce9289e8ebed)

**Comment by Perryvw** [comment]
Your TypeScript is incorrect, that is why you are getting a TypeScript error. This is not related to TSTL.

Example with correct TypeScript code: https://typescripttolua.github.io/play#code/GYVwdgxgLglg9mABAEwKYTgJwIZSwHgGEAbbAZzID4AKKbTAc1SgC5ETyyAaRDMKVAA9W7UhQCyzABZxkAEXRZcWQggHCAlGwBucGMkQBvAFCIziAA6YY-agCI0AIxANes1HY3GAvseMQxMkQAMTg4I1NzAAE0DBw8TEizCxBHYhgIRABbaVkAJmoNI0RMZhBMJAAWAG5EX28gA
