### ISSUE TITLE
Suggestion: add isEmpty for LuaSet and LuaMap

### ISSUE THREAD

**Issue by rhazarian** [TypeScriptToLua/TypeScriptToLua#1466]
Its possible to check if a table is empty using the `next` function.

Currently I always have to do the following in my TS code when I want to test if a LuaSet/LuaMap is not empty:
```
if (next(luaSet)[0] != undefined) {
    ...
}
```

I think it would be very handy if you could abstract it into a fake `isEmpty` method/getter, which would transpile in the following way:

```
if (luaSet.isEmpty) {
    ...
}
```

should be equal to

```
if (next(luaSet)[0] == undefined) {
    ...
}
```

**Comment by Zamiell** [comment]
have you considered using a normal set/map instead of a lua set/map?
e.g. if you just use the normal ones, then it is trivial to check `size === 0`

**Comment by rhazarian** [comment]
I almost never use normal Sets/Maps due to their horrendous performance, except when I absolutely need their features (fixed element iteration order / size counting) and don’t expect them to contain a lot of elements.

The problem with their performance is that their iterator is set up in a way it spawns a couple of new tables when iterating the collection contents with a for loop. So, when used frequently, it causes the game’s GC absolutely explode and leak gigabytes of RAM. It breaks and never cleans up.

**Comment by Zamiell** [comment]
> The problem with their performance is that their iterator is set up in a way it spawns a couple of new tables for each element (!) when iterating the collection contents with a for loop. So, when used frequently, it causes the game’s GC to absolutely explode and leak gigabytes of RAM.

after iteration is over, the iterator table should be automatically garbage collected, right?
TSTL maps and sets seem to be used throughout a wide variety of games, i wonder if your game's lua implementation might be bugged?

**Comment by lolleko** [comment]
> I almost never use normal Sets/Maps due to their horrendous performance, except when I absolutely need their features (fixed element iteration order / size counting) and don’t expect them to contain a lot of elements.
> 
> The problem with their performance is that their iterator is set up in a way it spawns a couple of new tables for each element (!) when iterating the collection contents with a for loop. So, when used frequently, it causes the game’s GC to absolutely explode and leak gigabytes of RAM. It breaks and never cleans up.

Can you share an example where iterating tstl (lualib) Sets/Maps leads to gigabytes of memory being leaked? I would like to investigate and fix that if possible.

**Comment by rhazarian** [comment]
I think its more specific to the game (Warcraft III Reforged) rather than the library. Whenever you do
```
for (const x of set) {
    ...
}
```
you allocate a new table per each element (here: https://github.com/TypeScriptToLua/TypeScriptToLua/blob/793e7f00566c34aba19281747133e6a77a7e6a4a/src/lualib/Set.ts#L142).

So, if the set contains a couple thousand elements, you allocate two thousand new tables.

When you iterate this set in a response to a game event / on each frame, you're doing it a lot of times per second.

Warcraft III Reforged's Lua GC is running periodically on a timer, not the standard way, (that's how the developers made it and modders can not change it), so that whenever it tries to run, there is already too much tables and it simply dies on it, cleaning only a slight part of it. So the amount of leaked tables continues to grow, and the GC continues to die (however, if you stop producing tables, after a couple of minutes the GC can sometimes catch up).

So I'm kinda forced to use LuaSet/LuaMap for anything that is needed to be iterated frequently.

> could it be the case that your game's lua implementation is bugged?

It is trash, yes.

**Comment by Perryvw** [comment]
I think providing an `.empty()` language extension would be reasonable. I don't think forcing usage of `lua-types` where this would otherwise not be necessary is a nice workaround to have. We do need to figure out if this `next(luaSet)` is a working solution for all lua targets we target, or if some targets need another translation.

Alternatively, maybe we should think of providing a `.size()` method instead to find the current size of the table, becuase I don't think there is really a good way to do that at the moment either. If you have an efficient `size()` you can simply just check if that is 0 too. I do not yet know what simple, optimized Lua that would translate to (for every lua target).

**Comment by Zamiell** [comment]
> When I started doing my mod, I was extensively using default TSTL Set/Map classes and my own Vector2 class (used to describe points). It ended up in a way where over an hour of play the players would see their RAM usage continually grow, never decreasing, and the game would crash because of OOM in the end.

Very interesting, thanks for the writeup. I suspect that for most games and most use-cases, the performance difference between `Map` and `LuaMap` would be pretty negligible and/or difficult to measure.

>  If you have an efficient size() you can simply just check if that is 0 too.

I would be a fan of having both `size()` and `isEmpty()`, as it allows for cleaner code.

**Comment by lolleko** [comment]
I added isEmpty functionality in #1470.

I also considered adding a `size()`, but after a bit of thinking, I would oppose adding a `size()` function for the following reason:

AFAIK the only way to accurately get the size of a vanilla Lua table in all targets is to iterate the whole table with `pairs()` and count.
This is an `O(n)` operation and would contrast with the "lightweight characteristics" of `LuaTable` language extensions.
In addition, this would be hard to translate inline. Existing extensions can be compiled into simple expressions e.g. `table.set({}, "foo", "bar")` => `table["foo"] = "bar"` or `table.isEmpty()` => `next(table) == nil`. However, Iterating with pairs() would require a for loop and I am not sure if that's possible without translating into/calling a function.

If `size()` functionality is still desired I would like to discuss it further in another issue.
