### ISSUE TITLE
noImplicitGlobalVariables should prevent enums using global variables

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1477]
By default, TSTL transpiles the following:

```ts
const fooVariable = 123;

enum FooEnum {
  Value1,
}
```

To the following:

```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
fooVariable = 123
FooEnum = FooEnum or ({})
FooEnum.Value1 = 0
FooEnum[FooEnum.Value1] = "Value1"
```

So far, so good.

Now, let's see what happens when I use the `--noImplicitGlobalVariables` flag.

```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local fooVariable = 123
local FooEnum = FooEnum or ({})
FooEnum.Value1 = 0
FooEnum[FooEnum.Value1] = "Value1"
```

As you can see, it causes the local enum of `FooEnum` to copy the global enum of `FooEnum`, if present, _even though the `--noImplicitGlobalVariables` flag is turned on_.

This behavior exists because TSTL mimics the feature of TypeScript where you can split up enums between different files, and have everything still work as long as you use the same name for them. However, this is a pretty esoteric TypeScript feature. I think that the vast majority of TSTL users will be surprised that the local enums in their project can be broken simply by having other Lua code in the environment overlap with their completely-internal enum names.

Ideally, I propose that TSTL changes its behavior such that it intentionally does not implement the "enum extension" feature of TypeScript. In the trade-off between "perfect emulation of TypeScript" and "providing safe Lua code that meets user's default expectations", I prefer we lean more towards the latter. Such a change would be breaking, but it would be a relatively small breaking change, since I doubt anyone is extending enums in this way.

Failing that, I propose that using the `noImplicitGlobalVariables` flag disables this behavior, as it stands to reason that users who are using this flag _really_ don't want to use any global variables.

**Comment by Perryvw** [comment]
I see no reason nor benefit to implementing this, enum merging is a thing and can be used raegardless of wether global or local variables are used. Disabling this by another seemingly unrelated flag only makes the transpiler behavior more unexpected.
