### ISSUE TITLE
TSTL passes table to error unnecessarily when debug == nil

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1493]
When I do `throw new Error("test")`, I get the following runtime error:

```
[INFO] - Error in "PostRender" call: ...Isaac Rebirth/mods/foo/main.lua:43452: attempt to concatenate a table value (local 'message')
```

Which corresponds to this line:

```lua
message = message .. "\n"
```

So it looks like we forgot to take message being nil into account.

**Comment by Perryvw** [comment]
I am missing some info to reproduce this. I am seeing you pass "test" as error message so how can the message be nil? Neither do I see our code concatenating message with \n anywhere.

Need more of the TS and Lua to understand how this is related to the tstl changes which only really affected the stacktrace

**Comment by Zamiell** [comment]
I'll create a small reprex now.

**Comment by Zamiell** [comment]
I ran this playground:

https://typescripttolua.github.io/play#code/C4CwTg9g7gBAdgU1gUTJMAKARAFWQZRywEoBuAKCA

And I got the following run-time error:

```
[INFO] - There was an error running the lua file: C:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth/mods/test/main.lua
```

Which isn't very helpful I guess. =p

So I tried putting the error inside of a function, like this:

https://typescripttolua.github.io/play/#code/GYVwdgxgLglg9mABFApgZygUQE7btgCgEpEBvAKESuQAs8B3RMFRnPQgIgBVMBlLjkQDc5AL7kgA

And then calling it from the in-game console with `lua testError()`. But that crashed the game.

I'll try doing some more in-depth debugging by commenting stuff out to see exactly where the error happens.

**Comment by Zamiell** [comment]
Ok, I see the problem now.

The normal usage of the built-in `error` function is to pass an error message as a string.
But it also supports the usage of passing it a table with arbitrary data inside of it, which is what TSTL does.
My game supports string messages but seems to choke when passed a table.

So, when TSTL fixed the `debug == nil` bug, I thought I would be able to use `throw new Error` without any issues, but that seems to not be the case. As for fixing it, since I guess TSTL doesn't have any way of knowing whether the upstream thing will support `error` + `table`, I guess there isn't anything actionable to do here.

**Comment by Zamiell** [comment]
If `debug == nil` and the error message is just a string, I propose that TSTL just transpiles `throw new Error("foo")`  to `error("foo")`. Passing a table to `error` in this case doesn't provide any additional benefit AFAIK, it just further obfuscates what the error is.

**Comment by Zamiell** [comment]
Should I open a new issue for the other proposed behavior?

**Comment by Perryvw** [comment]
No need, I have no desire to add that behavior to tstl. You catch what you throw now as it should be. I see no reason to change this and do unexpected extra error translations.
