### ISSUE TITLE
Wrong static super call

### ISSUE THREAD

**Issue by pilaoda** [TypeScriptToLua/TypeScriptToLua#1504]
https://typescripttolua.github.io/play/#code/FAYwNghgzlAECCsDexZtlALhTBLEsA4gKaYAUAlMqurQE6kCudAdrAETzsDcNaAvsEGhIMWACFYxAB6ZiLACZxEKWlhz4ipStVr0mrDIwAOxOgDoS5KgGoO4nn1iDBQA
```
function B.Get(self)
    return A.prototype.Get(self) .. "B"
end
```
shouldn't call super function in prototype, expect result is:
```
function B.Get(self)
    return A.Get(self) .. "B"
end
```

**Comment by Perryvw** [comment]
This does look strange. To judge how important this issue this is: Is the current translation result actually broken or is it just inefficient?

**Comment by pilaoda** [comment]
> This does look strange. To judge how important this issue this is: Is the current translation result actually broken or is it just inefficient?

It is broken and thrown an exception on run time
