### ISSUE TITLE
New warning from Node when compiling project with TSTL library

### ISSUE THREAD

**Issue by Zamiell** [TypeScriptToLua/TypeScriptToLua#1515]
When compiling a TSTL project with an ESM TSTL library, the following warning is generated:

```
(node:17112) [DEP0151] DeprecationWarning: Package D:\Repositories\isaacscript\node_modules\isaac-typescript-definitions\ has a "main" field set to "./dist/index", excluding the full filename and extension to the resolved file at "dist\index.js", imported from D:\Repositories\isaacscript\packages\isaacscript-common\src\arrays\dummy-file.mjs.
 Automatic extension resolution of the "main" field isdeprecated for ES modules.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

In order to try and solve this problem, I tried changing the file extension in the "main" field to both ".js" and ".lua", but TSTL chokes on both versions, complaining that it "failed to find lua source files". I assume that this is because it is manually appending a ".lua" suffix to whatever the path is, so it e.g. fails to find "index.lua.lua".

Perhaps TSTL should be changed such that libraries require a ".lua" extension in the "main" field? And then TSTL wouldn't need to append anything.

**Comment by aleksander-ciesielski** [comment]
if the `"main"` field requires the `.lua` extension, then - I'm pretty sure - it won't be possible to import the package from the standard Node projects - only the TSTL ones

**Comment by Zamiell** [comment]
(The context here is that the `isaac-typescript-definitions` library is a Lua library that uploads both ".lua" and ".js" files to npm, so that it can be used as a Lua library, and can also be used in Jest tests.)

**Comment by Z3rio** [comment]
Could you perhaps provide a repo or playground link for reproducing this issue? Thank you

**Comment by Zamiell** [comment]
Hi Z3rio,

It should be trivial to reproduce, you just make any TSTL library with `"type": "module"` and then consume it in another TSTL package.

**Comment by Zamiell** [comment]
I don't think the playground supports TSTL modules, so you would have to make something locally.

**Comment by Perryvw** [comment]
I would propose publishing two packages from the same source code, one to be consumed by your ESM JS projects, and one to be consumed by TSTL projects.

We have no influence over node and this warning, I see no good reason to complicate our module resolution (which we use a third-party library for) even more to try to resolve .js paths as lua files. I want to avoid pulling the complexity of your individual project setup into the core compiler.

**Comment by Zamiell** [comment]
Perry,

Can you clarify that TSTL will never support ESM? ESM is the common standard for TypeScript code going forward, so that would affect a lot more than just my individual project.

**Comment by Perryvw** [comment]
> Can you clarify that TSTL will never support ESM?

I would not say never, but at the moment I see no reason to do so. Maybe if there were a bunch more people in this issue stating they also somehow need this we could reconsider.

**Comment by Zamiell** [comment]
Having TSTL not support ESM is a foot-gun that will only get worse as time goes on.

You could imagine that in a few years, brand new TSTL users who are setting up a library for the first time will naturally use ESM, since all their other TypeScript code uses ESM. Since they use ESM, they will run into this unsolvable issue, and only after some troubleshooting pain will they hopefully realize that they have to convert their entire library back to the legacy CJS format in order to get it working properly.

Maybe having a TSTL library in CJS that is only consumed by TSTL programs in CJS isn't such a huge issue. But I think the problem gets a lot worse when you consider the wider ecosystem. Say for example I want to make a TypeScript server with a TypeScript client, so that way my entire project shares the same programming language, and I use TSTL to convert the TypeScript client to Lua. Now, because the TSTL part is locked to CommonJS, I have to also lock the server to CommonJS. And if the server is CommonJS, now all of the server libraries have to be CommonJS. So now I have to specifically go out on npm and look for old, legacy libraries that are written in CJS from 10 years ago, making the whole thing a nightmare.

ESM support is a can that we can kick down the road, but I think eventually this is something that needs to be addressed. Hopefully others will chime in here that ESM support is something they want as more time passes.
