### ISSUE TITLE
@noSelf doesn't work with variables

### ISSUE THREAD

**Issue by ProgrammingLife** [TypeScriptToLua/TypeScriptToLua#1516]
Input:
```typescript
/** @noSelf **/
declare const someSDK: any;

someSDK.init("param")
```

Output:
```lua
someSDK:init("param")
```

How to get rid of this ":" character in output? As my someSDK doesn't need to take a self param.

Sure I can declare all my someSDK methods but it's very unnoying thing. In some cases it's easier to just declare some variable as any and forget about it 😀

**Comment by Zamiell** [comment]
[It works fine if you type it properly.](https://typescripttolua.github.io/play#code/PQKhAIAEDsHsGUCmAbAZuMwBQBLaAXRAJ1QEMBjRceWAW0XgBEBpcAby3HDx3wC5wACgAOpIqVoCAzviJ4A5gEpwAXgB84AG6wcAEwDcWAL5YsuxOWRiq5WNBngpdBiwE16TZoaxOPLAHQ8+IIARKLitCGKhkA)

**Comment by Zamiell** [comment]
But then you would be using an untyped SDK. What's the point of using TypeScript if the SDK is untyped? You might as well use Lua then and get rid of the compile step.

**Comment by Perryvw** [comment]
tstl decides between . and : based on the type of the function called. In your initial code the function is `any` and we cannot determine the type. So for this to work  you need to explicitly state that this function exists.

**Comment by Zamiell** [comment]
You could try this: https://typescripttolua.github.io/play/#code/JYOwLgpgTgZghgYwgAgMoHsC2FUBEDSyA3gFDLIDaA1hAJ4BcyAzmFKAOYC6jAFGABbAmjAG7pgAEwA0yAHTy4UdsOQBXEFRDoA7iAqcAlMgC8APjUatugNwkAviRISICADaKUCdCBbMsOAkYMbDx8WxImf1DZUGAwHgAiAAdFOEwEg1sgA

But I would actually type out for real all of the SDK methods that you are actually using. You don't have to type out the entire SDK, but if you type out the ones you are actually using, you get the benefits of using TypeScript in the first place! Don't be lazy. :)
