### ISSUE TITLE
`Number.isInteger()` support

### ISSUE THREAD

**Issue by scarf005** [TypeScriptToLua/TypeScriptToLua#1517]
https://typescripttolua.github.io/play/#code/HIVwtgRgpgTgdASwM4EkB2AXKBzWAKAZgEog

![image](https://github.com/TypeScriptToLua/TypeScriptToLua/assets/54838975/b763fe7a-1976-4be6-b9d1-baa71a84a6b6)

it'd be nice to have 1:1 interop with javascript's `Number`.

**Comment by Z3rio** [comment]
Would love to have a look at this sometime
