### ISSUE TITLE
Request: console.error and console.warn should output stacktraces as well

### ISSUE THREAD

**Issue by BribeFromTheHive** [TypeScriptToLua/TypeScriptToLua#1527]
This request is to append console.trace() at the tail of every console.warn/error call, otherwise they just appear like normal console logs once transpiled to Lua. Browser console errors/warnings will show the traceback when you expand on them, so maybe this can be a configurable option so if users do not want it, they can just adjust their tstl configuration in tsconfig.json.

**Comment by Zamiell** [comment]
Have you tried using `throw new Error` instead of `console.error`?

**Comment by BribeFromTheHive** [comment]
It's a suggestion to get the output Lua code to function like TypeScript. Throwing an error is much different than console.error.

**Comment by Zamiell** [comment]
In a browser, console.error doesn't show the error trace, so I'm not sure what you are referring to.

**Comment by BribeFromTheHive** [comment]
> In a browser, console.error does not show the stack trace, so I'm not sure what you are referring to.

In Edge developer tools, there is an arrow next to console.warn/error logs that you can click onto to reveal the stack trace leading up to that point. It does not do the same for normal console.log calls.

**Comment by Perryvw** [comment]
I don't see any reason to force this. This runs into some issues with environments where there are different (or no) ways to retrieve stack traces. 

The current method allows you to simply make a helper function and append the stack trace yourself.
