### ISSUE TITLE
@customName is ignored if @noSelf is applied

### ISSUE THREAD

**Issue by aabajyan** [TypeScriptToLua/TypeScriptToLua#1528]
I'm currently looking for a solution and if I find anything I will create a pull request

Works without `@noSelf` attribute
Same issue with `@noSelfInFile`

https://typescripttolua.github.io/play#code/PQKhAIAEDsHsGUCmAbAZuEwBQATRBjZAQwCdFxoiBbRAZwAcj9yBzaugFyI-IG8twg8KAiR8AV1odYVAHLtwjWrQzYh4VOOj4OAS1jQNRXcgAUASgBc4AG6xdOLAF8sWNjSndEAOlTGz5gDcQA

```ts
/** @noSelf */
declare namespace gamestate {
    /** @customName pass */
    function fail(): void
}

gamestate.fail();
```

Expected:
```lua
gamestate.pass()
```

Got:
```lua
gamestate.fail()
```

**Comment by Perryvw** [comment]
My guess would be somewhere down the call path of `transformCallAndArguments` we are forgetting a check for customName, as resulting from here: https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/src/transformation/visitors/call.ts#L196

Probably callPath is not created correctly
