### ISSUE TITLE
Using `super` with `__index`-based inheritance returns `nil`

### ISSUE THREAD

**Issue by coDiesIrae** [TypeScriptToLua/TypeScriptToLua#1537]
`__TS__DescriptorGet` uses `rawget`, which ignores `__index`, therefore returning `nil` when trying to access fields or methods of base class

For example, in `dota_ts_adapter`:

```ts
setmetatable(BaseAbility.prototype, {
  __index: CDOTA_Ability_Lua ?? C_DOTA_Ability_Lua,
});
```

Then, extending `BaseAbility` and calling method on `super`

```ts
class SuperAbility extends BaseAbility {
    GetBehavior() {
        const res = super.GetBehavior();
        // ...
    }
}
```

Produces the following lua code:

```lua
local res = __TS__DescriptorGet(self, BaseAbility.prototype, "GetBehavior")(self)
```

Which causes `attempt to call a nil value` error in runtime

**Comment by Perryvw** [comment]
The fix for this was published in 1.24.1
