### ISSUE TITLE
option to have all lualib functions accessed through object

### ISSUE THREAD

**Issue by jake-stewart** [TypeScriptToLua/TypeScriptToLua#1548]
lua only has up to 200 local variables but typescripttolua creates many local variables for the lualib

instead of

    local ____lualib = require("lualib_bundle")
    local Error = ____lualib.Error
    local RangeError = ____lualib.RangeError
    local ReferenceError = ____lualib.ReferenceError
    local SyntaxError = ____lualib.SyntaxError
    local TypeError = ____lualib.TypeError
    local URIError = ____lualib.URIError
    local __TS__New = ____lualib.__TS__New
    
it would make more sense to just have

    local ____lualib = require("lualib_bundle")

and then access the various features with `____lualib.Error`.

**Comment by jake-stewart** [comment]
same applies for named imports

```
import { foo, bar } from './baz'
```

becomes

```
local baz = require("baz")
local foo = baz.foo
local bar = baz.bar
```

but could only declare `baz` and then access properties of baz when used.

**Comment by Z3rio** [comment]
I might be mistaken, but I've seen this done in FiveM forexample, and I'm fairly certain that this is done to improve performance.
Aka, to keep the function "in memory" or whatever.

Dont really know the exact logic behind it, but I'd imagine there's at least some kind of similar thought behind this too.

As for the "lua local variable limit", that anyways seems to be for every individual function, so it should be quite hard to get up to 200

**Comment by jake-stewart** [comment]
> I might be mistaken, but I've seen this done in FiveM forexample, and I'm fairly certain that this is done to improve performance. Aka, to keep the function "in memory" or whatever.
> 
> Dont really know the exact logic behind it, but I'd imagine there's at least some kind of similar thought behind this too.
> 
> As for the "lua local variable limit", that anyways seems to be for every individual function, so it should be quite hard to get up to 200

good point. tstl probably/should keep track of this and handle it automatically regardless.

**Comment by Z3rio** [comment]
> > I might be mistaken, but I've seen this done in FiveM forexample, and I'm fairly certain that this is done to improve performance. Aka, to keep the function "in memory" or whatever.
> > Dont really know the exact logic behind it, but I'd imagine there's at least some kind of similar thought behind this too.
> > As for the "lua local variable limit", that anyways seems to be for every individual function, so it should be quite hard to get up to 200
> 
> good point. tstl probably/should keep track of this and handle it automatically regardless.

That of which I agree with.
We could at least start out with warning if it ever becomes more than 200.

And in the odd situation that someone actually gets up there, we could have a further look at this.

Doubt it'll happen, I've used TSTL to compile & inline import like 10 libraries at a time, leading to tens of thousands of lines of code being inline imported, without ever having said issue.
