### ISSUE TITLE
How to use mixins?

### ISSUE THREAD

**Issue by ProgrammingLife** [TypeScriptToLua/TypeScriptToLua#1553]
I'm noticed that: `Object.getOwnPropertyNames is unsupported.` ( as well as Object.create() ) in TStoLua in case I wanna use mixins like this:
https://www.typescriptlang.org/docs/handbook/mixins.html

I need to use a multiple inheritance in my TS code. Is there any correct way of doing this without using composition or other hacks?

**Comment by Perryvw** [comment]
The main method as described on that typescript website seems to work fine: 

Here's it working on our playground: [Playgorund link](
https://typescripttolua.github.io/play/#code/MYGwhgzhAEDKAOAnAlgFwKbQN4ChrQDswBbTAXmgCJKBuPaAD2goAY78BPZ6Nve4APYEIqRAFdgqAYgAURUgC5oIlAQDmASmz18qABbIIAOnnlCJdO2gBfHLZwB6B9AAqA6GvSplqMIgwAJgA00ADumATo6AHQYNCoHPCYoQbAemHoAOQgINBiEJhS0OgMGAQBjs4C+uiI0KCQBTAAZogCxEauepjEYMgE0IjoEPBCEMgARsggaFyG8e4B6A1DlfF6YN418YmYE+j9atDwjdHQ-ecwcQ1QRnwJSdAAwmOiElJ1FJGh0DJG-341BAlGACBwANoAXS0ZAAfNhrHQHpgAOIvYRvSTSAA8Lm4WGs8K+6B+fwBiCBILBUJh8Jc7DWLgMMGIyAYFzAAQCV2UwDAIEwSAESX8HBCoTQ6U8qAwiCu5WUXllEDWzWk9Q26kO528Ev0sQG6AIfPgEDE4ECxxQADdNoK2iKEgocDhkdAAAoCcaoZBCMATAXcNGvcRYxDYrCK1Ce4G-BhKAhiYj7RAhDgJpMp2nQa0CZAxQlI3ZwJBof2BijBjGhj7YhAoDCwouPAAyAjUanLZirKneOMjpYIqCUMmzufzNibfBwzTExp9Qg9XrQvqIAfQuIAQpBMCUytzniG+4hYTJtwUlC5z+gtLh8PghqgxIgBjcYDGV3718VSkaD9ftHvIDjjEANkGARhuF4YD73gUCZggrhWDoHRgIKaMvRkeNCEzWo0wzZNalvVCYN0ZkjCYCgGCsUj730QwjCQ6AOBo4DbCA2x7FnedV2gAApJMTnXLcdx-fd32XBc1wFU9r0va9iIfLxn1fcAoH4wSuzEv8YAAu97wAK0E0dAOApwunmVl2QGCUcmgIQQC4UJpAAa3OZodUuY5ThiOIJh3EjoHMt8wlSdINhgdCY2gJZmn6M59j5fJMAEDyakC8yPykrTBGrPohzuGD6OMKLMJYEIACYWA0Vj2JsOh7HMl5iFGApYkIEl6jUlo2mIdZMHrNBMDfII1j1dJtgAWTZC5YD5QMwHgeAZlqZ1cpEaAAFFkDUPRUE3NBBowbgBJarsZCy1dzqOm8ar4dbvGacAlo4G7uG+Ladr2g7UBumRKAOxAAkoO6nsW+BXtLDAjFKiAZAqkIABY7vWgQBSMEB2xkMGXpuiiQhxiG8Y4UHnqJqH0CMIyWtHOhUfRzG1GxsnIYbSmGAJlniY0HAgA)

No hacks required
