### ISSUE TITLE
Support Transpilation to an Allowlisted Subset of Lua?

### ISSUE THREAD

**Issue by theguy-gay** [TypeScriptToLua/TypeScriptToLua#1557]
Hi, I am wanting to use this with a game that for security reasons only allowlists a subset of of Lua functions to be called. Is there a way to limit transpilation to only target a subset of the Lua API?

**Comment by Perryvw** [comment]
Best you can do is to not include lua-types, which will hide the lua standard library. If you want to allow specific files from lua-types, you can include those specific files.

i.e do NOT write `"types": ["lua-types/5.4"]`, but instead write `"types": ["lua-types/core/math"]`
