### ISSUE TITLE
Create a global lua function?

### ISSUE THREAD

**Issue by piscopancer** [TypeScriptToLua/TypeScriptToLua#1566]
## Reasoning

I need TSTL to generate global function because I am making a mod for a game and there is another mod that looks for **global function declaration with the name `on_mcm_load()`**

## Function declared without `export`

`mcm.ts`
```ts
function on_mcm_load(): McmOptionTree {
  return { ... }
}
```

`mcm.script`
```lua
local function on_mcm_load() -- I totally agree to it using `local` here, it is a good lua practice
    return { ... }
end
```

## If `export` used

`mcm.ts`
```ts
export function on_mcm_load(): McmOptionTree {
  return { ... }
}
```

`mcm.script`
```lua
function ____exports.on_mcm_load() -- i just need `function on_mcm_load()`
    return { ... }
end
return ____exports
 end,
}
``` 

https://github.com/user-attachments/assets/99d1b1b4-249f-4876-a760-da641960b3ca

## Current solution

Either works

- I have to manually remove `local` from the transpiled file
- 😞
```ts
export async function transpile() {
  const sourceMcmBuffer = await fs.readFile(process.cwd() + `/src/mcm.ts`)
  const sourceMcm = new TextDecoder().decode(sourceMcmBuffer)
  const res = tstl.transpileString(sourceMcm, {
    noImplicitSelf: true,
  })
  let lua = res.file?.lua
  if (lua) {
    lua = lua.replace('local function on_mcm_load', 'function on_mcm_load')
    await fs.writeFile(process.cwd() + `/build/gamedata/scripts/${addonId}_mcm.script`, lua)
  }
}
```

**Comment by Zamiell** [comment]
see [this playground](https://typescripttolua.github.io/play#code/PTAEDEHsCdQFwBYFNQAcCu1WQM5J6JAGbzJoA2AhgJ4Dm0k6AdgCYA0oA7iqtEnElahyASwDWKbqEp9QIgLbZocEU1qFYSAB5KVa0Dkjz+CVbQB0AKBCgA8oiTROIvB0rlyoIswDGKyEwEzh6gAEYocJhMSCxyTHCQoLTkkKHuoABuMiKUoeT4YdSgLEhElOjkcFY2ABQAmowGCIzkse6cNAToeKQoAERMkACSiqI+InAA4ilp5ABq2bn5OH2gPkaoIvmwRFTqqqDUjLB86esl8JDWYLxIGYJwpC5hSAiUGSIw5gCUltq6oAA3gBfADclmuoAAsiZILEAIygAC0oAA6ihKDgcCJaExpF5fP48QlekkZukcOtUEgrN4mH5PniiJBIOBfDVvkDgZZkql3AAVUw4ADafWZkD6AF1QABeLwstn08GQmGIOGgABMyNAQxIABl0JRiqVVBNGQQZChVD5yOgSuxDo0fJQ8Zjsbi5I8SQB9SbFER8PzkajVMA1QVIIqW0CDR7W232uKk1BUOgMZgOwyepIie4W+DUamgRwMaA-Sy+0XiqWy+Ws3zKmyq5qxADM2vRaxdxpt0YcBPpROkFvIpxYRW0Lj0FksJV7snyj3FAC5QBzZQA+TKQEQscHi2vixU+cFAA)

**Comment by piscopancer** [comment]
@Zamiell thank you for the playground, I see how it's working but I need specifically `function <name>()`

**Comment by Zamiell** [comment]
I don't understand the question. In the playground I linked, you can change `foo` to any arbitrary string you want.

**Comment by Venusta** [comment]
https://www.lua.org/pil/6.html

> If functions are values, are there any expressions that create functions? Yes. In fact, the usual way to write a function in Lua, like

    function foo (x) return 2*x end

> is just an instance of what we call syntactic sugar; in other words, it is just a pretty way to write

    foo = function (x) return 2*x end

**Comment by piscopancer** [comment]
@Zamiell the other mod which I write my code for looks in files and looks for `function on_mcm_load()`, not `on_mcm_load = function`, `local function on_mcm_load()`, `function ____exports.on_mcm_load()`. That's why I said here
```lua
function ____exports.on_mcm_load() -- i just need `function on_mcm_load()`
    return { ... }
end
return ____exports
 end,
}
```

**Comment by Zamiell** [comment]
How is it looking for it exactly? Once it is defined as a global variable, then the syntax that you used to create it in irrelevant. Unless you are saying that the game literally does a regex find and replace inside of your Lua code or some crazy stuff like that?

**Comment by piscopancer** [comment]
@Zamiell  yeah it just uses pretty narrow regex to find this function, this is what the other modder did in their code 

*shaking hands*

**Comment by Zamiell** [comment]
for this weird requirement, one solution is to use a plugin (like you show in the OP).
however, i think a better solution is to just use a static lua "main.lua" file, something like this:

```lua
local tstlBundle = require("tstlBundle")

function on_mcm_load()
  tstlBundle()
end
```

then you transpile your project with the compiler option of `luaBundle: tstlBundle.lua`.
this way you have a clear delineation between the weird lua crap and the pure typescript.

**Comment by Perryvw** [comment]
I like Zamiell's solution, having a lua entry point calling into the tstl bundle is probably cleanest. 

Alternatively you could do your string replacement in a tstl plugin in `beforeEmit` as described in https://typescripttolua.github.io/docs/api/plugins#beforeemit
