### ISSUE TITLE
Set default: self param only for class functions?  

### ISSUE THREAD

**Issue by piscopancer** [TypeScriptToLua/TypeScriptToLua#1570]
How can I set the default rule that prevents all non-class functions from having `self` as the first param? I only need this modification for functions in classes, standalone functions, functions declarations and arrow functions - no

I have many functions in my mod that must bot have self param, otherwise the game won't accept them. Because of that I have to add `/** @noSelf */` every time or `this: void` and it becomes annoying with more LoC
Ex 1
```ts
function on_game_load()
```
will have unwanted `self` injected
Ex 2
```ts
Register('on_save_load', (data) => {...})
```
will have unwanted `self` injected before `data`, causing crash

At the same time game uses `:` for functions on class instances. So I need to keep the colon for this specific case only

**Comment by Zamiell** [comment]
Does using the noImplicitSelf compiler flag solve your problem?

**Comment by piscopancer** [comment]
yes it does, turnss out, how did I not know about it, thanks
