### ISSUE TITLE
create file with decorator

### ISSUE THREAD

**Issue by mehah** [TypeScriptToLua/TypeScriptToLua#1578]
is there any way to use decorator that tells the transpiler to create a file when translating from ts to lua?

ex:
(xpto.ts)
```ts
@Controller({name: 'teste', files: ['any.text', 'test.jpg']})
class XPTO {}
```

output
xpto.lua
teste.ini

(teste.ini) content
```ini
name = test
files = any.text, test.jpg
```

**Comment by Z3rio** [comment]
Probably possible via tstl plugins, yeah.
Thats not really something tstl is responsible for though, you'd have to code that logic yourself.

TSTL is mainly just for converting TS to Lua, not other misc/niche stuff :)

**Comment by mehah** [comment]
Hmm, ok

thx. @Z3rio

**Comment by Perryvw** [comment]
I agree this seems out of scope of tstl
