### ISSUE TITLE
Type alias for Iterator of MultiReturn doesn't work as expected

### ISSUE THREAD

**Issue by Gudine** [TypeScriptToLua/TypeScriptToLua#1591]
Using a type alias for a LuaIterable that iterates through LuaMultiReturn makes the compiler not recognize it as a LuaMultiReturn.

The code:
```typescript
type IterableAlias = LuaIterable<LuaMultiReturn<[number, number]>>;
declare const iterable: IterableAlias;
for (const [a, b] of iterable) {}
```

Outputs:
```lua
for ____value in iterable do
    local a = ____value[1]
    local b = ____value[2]
end
```

When it should instead output:
```lua
for a, b in iterable do
end
```

Here's a [playground link](https://typescripttolua.github.io/play/#code/C4TwDgpgBAksECcCGAjANhAgmglkgzlALxQAyArknIqhgDwVICy5awOAShMOQgHZ0A2n3IBbFIgA0UEeMQBdAHyKA3AChQkWPGTosuAlx79iUI7z4AVcBDoAKAJTFFZStV31GLNp24WhshII0oEKyqpqagAmEADGaEgI0LEA9nz4wFA4OrQQAIwAXNo0eth4+Oox8YnJaRlZOXoATEWM7rkMlN7s5vwBYkEhA2ERVQlJUKnpmdklGADMRe2lBvi9fOpqAGYpCFB2U-WCSNIo8lApWw1z+U4A3gC+27v7h5nHp+eX1x4QTfdPHZ7A51d4nKBnC5XWa-eYAoA) with some examples.

**Comment by Z3rio** [comment]
It would be
```lua
for a, b in pairs(iterable) do
end
```

But yes, that does indeed sound like an issue.

**Comment by vitaliy-art** [comment]
I faced the same issue. In my case sources looks like that:
```ts
declare function iterator(): { a: string } & LuaIterable<
    LuaMultiReturn<[string, string]>
>;

for (const [a, b] of iterator()) {
}
```
And here is compiled Lua script:
```lua
for ____value in iterator(nil) do
    local a = ____value[1]
    local b = ____value[2]
end
```
