### ISSUE TITLE
not expect “_G” when working with generated code

### ISSUE THREAD

**Issue by blackSocial** [TypeScriptToLua/TypeScriptToLua#1593]
Hello author, I am developing a WoW plugin. <sub>CreateFrame</sub> is a global variable provided by WoW that will not appear in my library. How can I avoid tstl generating _G?
I look forward to your reply.

```
// fileA.ts
const options = CreateFrame("Frame");
```

```
// fileA.lua (generated file by tstl)
options = CreateFrame(_G, "Frame")
```

**Comment by Perryvw** [comment]
I guess the fact you closed this means you found the answer. For anyone that stumbles on this issue in the future, the anwer can be found in our docs here: https://typescripttolua.github.io/docs/the-self-parameter
