### ISSUE TITLE
How do I switch back to ts

### ISSUE THREAD

**Issue by huapis3** [TypeScriptToLua/TypeScriptToLua#1596]
I have a project where I can't find the source code, and I'm not familiar with Lua. How can I convert it to TypeScript?

**Comment by Zamiell** [comment]
If you want to recover the exact TypeScript source code, then the answer is that you can't - TSTL performs a one-way conversion process. Sorry!

However, for the more generic question of "how do I convert arbitrary Lua code to equivalent TypeScript code", you can check [my tutorial](https://isaacscript.github.io/main/converting-lua-code).

**Comment by huapis3** [comment]
All right. Thanks for the trouble. I'll go and have a look later.
