### ISSUE TITLE
String(any) doesn't map to tostring(any)

### ISSUE THREAD

**Issue by admiralnelson** [TypeScriptToLua/TypeScriptToLua#1597]
```ts
const points = 13.23
print("The point is" + String(points))
```
output
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
points = 13.23
print("The point is" .. String(nil, points))
```
expected
```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
points = 13.23
print("The point is" .. tostring(points))
```

Here's the playground thing
https://typescripttolua.github.io/play#code/MYewdgzgLgBADiAlmKEYF4YEYDMA6AJhwCg4AnZKACgCIAVACwFN4kUZEIaYBqGAZSgUwAcyoJKEAJRSgA

**Comment by Zamiell** [comment]
Workaround: Use `points.toString()` instead of `String(points)`.
I think that using the `String` constructor like that is typically discouraged in TypeScript, because it can lead to some weird issues.
See the warning on this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/String

**Comment by RGFTheCoder** [comment]
The warning on that page is about using `new String(...)`, specifically stating that you should not be using it as a class. It says nothing about the function usage as that is where you "should" be using it.

**Comment by Zamiell** [comment]
@RGFTheCoder See [this thread](https://github.com/typescript-eslint/typescript-eslint/issues/4314) from Brad Zacher, one of the core maintainers of typescript-eslint.

**Comment by admiralnelson** [comment]
> @RGFTheCoder See [this thread](https://github.com/typescript-eslint/typescript-eslint/issues/4314) from Brad Zacher, one of the core maintainers of typescript-eslint.

thanks for eslint hints, going to use this on prod and my modding hobby project

**Comment by Zamiell** [comment]
@admiralnelson No problem. If you want a more complete ESLint config, you might want to check out [eslint-config-complete](https://complete-ts.github.io/eslint-config-complete).

**Comment by Perryvw** [comment]
Added support for this in #1602 1602
