### ISSUE TITLE
Exclude files from build

### ISSUE THREAD

**Issue by musjj** [TypeScriptToLua/TypeScriptToLua#1599]
I have a `eslint.config.mjs` that I want to exclude from my build, but I still want it to be typechecked by TypeScript. If I exclude it in `exclude` in `tsconfig.json`, the file is no longer typechecked. Is there a way to tell `tstl` to exclude files from the build?

**Comment by Zamiell** [comment]
there's a few different solutions.
the one that i would recommend is to use the allowDefaultProject config option:
https://github.com/complete-ts/complete/blob/main/packages/eslint-config-complete/src/base/base-typescript-eslint.js#L22

it's documented here: https://typescript-eslint.io/packages/parser/#allowdefaultproject

another solution is to create tsconfig.json that includes everything and tsconfig.prod.json that contains only the files that should be put into the output.

**Comment by musjj** [comment]
Thanks. 

> another solution is to create tsconfig.json that includes everything and tsconfig.prod.json that contains only the files that should be put into the output.

Yeah, I decided to go with this route.
