### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by nucleartide** [TypeScriptToLua/TypeScriptToLua#170]
Thought it'd be nice to generate plain `for` loops as a special case. 😄 What do y'all think?

TypeScript:

```ts
for (let i = 1; i <= 10; i++) {
  // ...
}
```

Lua:

```lua
for i=1,10 do
  -- ...
end
```

**Comment by Perryvw** [comment]
We did this at first and that actually caused a lot of issues, why are the current while loops an issue for you?

**Comment by nucleartide** [comment]
Now that I think about it, it's not a huge issue. I'm coding in PICO-8 though, so I'll have to see if there's a token count difference between the `for` and `while`.

**Comment by Perryvw** [comment]
`for i = 1, 10 do` - 7 tokens, 16 characters
`local i = 1 while (i < 10) do i = i + 1` - 14 tokens, 39 characters.

Current translation seems to be about 2x larger, it kinda depends on how often you use for loops (I would generally recommend `for...of` where possible) what the impact is on your overall code size.

If this is an issue we could look at using a decorator that forces the plain `for`. The weird edge cases and corresponding bugs we had originally makes me a little hesitant there though.

**Comment by tomblind** [comment]
I was looking at implementing this until I realized there's a pretty big issue with how lua's numeric for works:
```ts
for (let i = 0; i < 4; ++i) {
    ++i;
    print(i);
}
```
In JS, this would produce: `1,3`, but in lua, the modification to `i` would be ignored and the result would be `1,2,3,4`. The only solution I can think of is to scan the loop body for assignments to the loop variable, but that would be pretty expensive to do (especially for large loops).

**Comment by tomblind** [comment]
I managed to get a working version that handles that issue, only to realize there's another, bigger one.

Probably the most common desired use case is this:
```ts
for (let i = 0; i < myArray.length; ++i) {
    ...
}
```
```lua
for i = 0, #myArray - 1 do
    ...
end
```
But these two are not the same. In lua, the stop condition in evaluated once, at the beginning. However, in TS/JS, it is re-evaluated every iteration. That means if the array's length changes, the loop will adapt in JS, but not in lua.

This difference can manifest problems in other ways as well. The only 'safe' loop that can be transpiled this way is one where the condition uses a hard-coded literal:
```ts
for (let i = 0; i < 10; ++i) {}
```

Given the amount of work the transpiler has to do to validate this one specific case, I believe it's just not worth implementing at this point.
