### ISSUE TITLE
Watch mode is only partially incremental

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#174]
The current watch mode is only partially incremental.

Typechecking handled by the ts compiler API is incremental (there is a small chance that this is not incremental aswell)

Emitting files (walking and transpiling the AST) is not incremental. Currently all files get reemitted on a file change.

This is kind of hard to fix because the compiler API implements incremental builds by hashing the emitted `.js` files. We don't generate those, so we either need to roll our own solution in the future or hack it.

**Comment by ark120202** [comment]
Resolved in #488
