### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#179]
Add support for plugins. Main use:
* Custom lua targets

**Comment by Janne252** [comment]
- Ability to override output file extension (probably allow modifying its name as well)

I will keep my list when new ideas arise.

**Comment by ark120202** [comment]
Now we do support this in a form of TypeScript transformers (for TS AST -> TS AST transformations) and a plugin system (which currently allows to tap into TS AST -> Lua AST transformation and provide own printer).

> Ability to override output file extension (probably allow modifying its name as well)

I'm planning to add a hook for that in the upcoming module support implementation. If you'd like to have a tracking issue, please open a new one.
