### ISSUE TITLE
Mixing typeof and parameters named type

### ISSUE THREAD

**Issue by gakada** [TypeScriptToLua/TypeScriptToLua#188]
`typeof` is translated to `type`, if there is parameter named `type` it is not renamed. For example
```ts
const f = (type: number | ((x: number) => number)): number => (typeof type === 'number' ? type : type(42))
```
gives
```lua
local f = function(type) return (__TS__Ternary((type(type) == "table" and "object" or type(type))=="number", function() return type end, function() return type(42) end)) end
```
which won't work.

**Comment by lolleko** [comment]
We should probably just disallow `type` as identifier and any lua standard lib/function name.

**Comment by lolleko** [comment]
A possible solution could be to disallow usage of names the Lua standard lib, but only for variable/parameter declarations. In other words prohibit shadowing or overwriting of those names.
That way we don't loose the ability to call std lib functions from typescript.

```Typescript
const table: string = "table"; // forbidden
const f = (type: any) => {} // forbidden
const pcall = (func: Function, params: ...any[]) => {func(params)} // forbidden
table.insert(x, y) // allowed
type("string") // allowed
pcall(()=>{}) // allowed
```
