### ISSUE TITLE
Source Maps

### ISSUE THREAD

**Issue by andreiradu** [TypeScriptToLua/TypeScriptToLua#237]
Right now error reporting for the generated lua files is pretty bad; you have to open the lua file, check the specific line and guess what generated it. Debugging also suffers from the same problem - you have to debug the generated lua files. 
When transpiling to js, the typescript compiler can also generate a .map file which would solve all this issues. I propose we do something similar but with a simplified .map format. The one ts uses([here](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?hl=en_US&pli=1&pli=1#heading=h.mofvlxcwqzej)) is aimed at minimizing file size, which I don't feel is as important here. 
I'm probably going to end up doing this anyway, but it's a very intrusive change, so I would prefer for it to be merged back.

**Comment by Perryvw** [comment]
The main issue with source maps in my opinion is that there is not really any support for it in whatever environment the lua output might be used. Could describe in broad strokes your idea on how the generated maps would be used to improve error reporting? Would you add some kind of wrapper around thrown functions?

**Comment by andreiradu** [comment]
Well, it obviously depends on what environment you're using. In my case, I control the runtime, so I can just load the source map and output the correct line number. It's trivial to do from the C side. As far a I can tell there's no way to change the error handler from lua. 
There are, however a bunch of open source VSCode debuggers - maybe they accept pull requests :) 
At the end of the day, this enables better tooling(in my case, for example, I can live with the wrong error numbers, bug debugging is vital). Weather that tooling is available right now, is secondary.

**Comment by tomblind** [comment]
I've been thinking about suggesting this myself. Since no tools will support them if they don't exist, it's kind of a chicken and egg problem. I think it would be best to provide them from tstl first, in the hopes that other tools will add support.

**Comment by tomblind** [comment]
I would recommend using a standard .map format however, so that existing tools can work with them.

**Comment by Perryvw** [comment]
I was thinking there might be a way to create some kind of wrapper around lua code with an xpcall that could then catch errors and use the source map. I would also prefer standard format indeed, and to make it toggleable (off by default) in tsconfig.

**Comment by dmarcuse** [comment]
I don't think `xpcall` is necessary, `pcall` should be fine. It could also be augmented to use `debug.traceback` in environments where the `debug` API is available.

**Comment by Benjamin-Dobell** [comment]
Just thought I'd chime in also vote for the "source map" rev 3 spec (https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.1ce2c87bpj24).

I'm implementing support for this spec in MoonSharp's VSCode debug server. It'd be great to be able to debug TypeScript directly from MoonSharp!

**Comment by Perryvw** [comment]
The current plan is to use [TypeScript's sourcemap.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sourcemap.ts) to generate the source map, which should follow the standard javascript v3 spec.

**Comment by hepiyellow** [comment]
> I don't think `xpcall` is necessary, `pcall` should be fine. It could also be augmented to use `debug.traceback` in environments where the `debug` API is available.

@dmarcuse When using `pcall`( and not `xpcall`) we are loosing part of the traceback. it shows a traceback only to where the error was caught, not to where the error originated.

I think `xpcall` should be considered.
