### ISSUE TITLE
Returning inside try block fails

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#252]
```ts
function foo() {
    try {
        return "foo";
    } finally {
        return "bar";
    }
}
print(foo());
```
```lua
function foo()
    xpcall(function()
        return "foo"
end,
function(e)
end)
    return "bar"
end
print(foo()); --Prints "bar"
```
The return statement only returns out of the function passed to xpcall. I'm not totally sure what a good way to deal with this would be.

**Comment by Perryvw** [comment]
We could add a `returned = false` and `returnValue: any` variable at the top and then transpile returns inside try-catch with setting returned = true and returnvalue = the thing returned. I'm not sure how else we could detect wether the return was hit or not.

**Comment by lolleko** [comment]
`pcall` does return the function results as second parameter:
```
function foo() {
    try {
        return "foo";
    } finally {
        return "bar";
    }
}
print(foo());
```
=>
```
function foo()
  do
      local ____TS_returned = false;
      local __TS_try, er = pcall(function()
          ____TS_returned = true -- add this before every returns statement.
          return "foo"
      end);
      if ____TS_returned then return er end -- er contains "foo" should probably be renamed to result to something 
      if not __TS_try then
          return "bar"
      end
  end
end
```

**Comment by lolleko** [comment]
We also have to check if __TS_try is set in addtion to ____TS_returned since a function could call a another fucntion in its return that throws.

```
function foo() {
    try {
        return functionThatCausesAnError();
    } finally {
        return "bar";
    }
}
print(foo());
```

Changing `if ____TS_returned then return er end` to `if ____TS_returned and __TS_try then return er end` should work.

**Comment by Perryvw** [comment]
> Something to keep in mind is that foo could be a TupleReturn function.
Ouch, will that table unpack work in all cases?

**Comment by tomblind** [comment]
Yes I believe that same code will work for non-TupleReturn functions as well. Since TupleReturn is an edge case, though, it might be worth having code paths for both.

**Comment by NetherGranite** [comment]
```
function foo() {
    try {
        return "foo";
    } finally {
        return "bar";
    }
}
print(foo());
```
```
function foo() {
    local ret
    e = pcall(function() ret = {(function() return "foo" end)()} end)
    if e then ret = {(function() return "bar" end)()} end
    return unpack(ret)
}
print(foo());
```
Would something like this be sufficient? Now that I think about it, it would probably be poor performance-wise.

**Comment by NetherGranite** [comment]
```ts
function foo() {
    try {
        return "foo";
    } finally {
        return "bar";
    }
}
print(foo());
```
```lua
function foo() {
    local ret
    e = pcall(function() ret = {(function() return "foo" end)()} end)
    if e then ret = {(function() return "bar" end)()} end
    return unpack(ret)
}
print(foo());
```
Would something like this be sufficient? Now that I think about it, it would probably be poor performance-wise.

**Comment by hazzard993** [comment]
In case someone is after specific test cases. I made a table of some try/catch results using Javascript and TypescriptToLua.

| Try          | Catch        | Finally         | JS Result | Lua Result (via tstl 0.11.1) |
|--------------|--------------|-----------------|-----------|------------------------------|
| return "foo" | return "bar" |                 | "foo"     | nil                          |
| return "foo" |              | return "foobar" | "foobar"  | "foobar"                     |
| return "foo" | return "bar" | return "foobar" | "foobar"  | "foobar"                     |

Some other trivia about try/catch:

- `try` **must** be followed by `catch`, `finally` or `catch` then `finally`
- Multiple catch statements are **not supported** in JavaScript and TypeScript

Implementation sure looks hard considering TupleReturn functions

**Comment by hazzard993** [comment]
I'll chip in an attempt too using those test cases above for testing and keeping tuple return in mind.

To keep try/catch statements functionally the same, this is the best I got. Returned values need to go somewhere and I can't do something like `local ... = 3, 4` to avoid a new table and `unpack`.

If we could scan for `return` statements and found none, this would be an easy `xpcall` but this covers all the edge cases I can think of.

```lua
-- template try/catch
-- 13 lines
-- 2 anonymous functions
-- 1-2 anonymous tables
local function try()
	-- {{ try block }}
end
local function catch(e)
	-- {{ catch block }}
end
local __result = { pcall(try) }
if not __result[1] then
	__result = { catch(__result[2]) }
else
	table.remove(__result, 1)
end
return unpack(__result)
```
or a more cramped version
```lua
-- template try/catch
-- 9 lines
-- 2 anonymous functions
-- 1-2 anonymous tables
local function try()
	-- {{ try block }}
end
local function catch(e)
	-- {{ catch block }}
end
local __try = { pcall(try) }
local __catch = __try[1] or { catch(__try[2]) }
return unpack(__try[1] and (table.remove(__try, 1) and __try) or __catch)
```

try/finally, super easy

```lua
-- template try/finally
-- 5 lines
-- 1 anonymous function
local function try()
	-- {{ try block }}
end
pcall(try)
-- {{ finally block }}
```

try/catch/finally is very easy too

```lua
-- template try/catch/finally
-- 8 lines
-- 2 anonymous functions
local function try()
	-- {{ try block }}
end
local function catch(e)
	-- {{ catch block }}
end
xpcall(try, catch)
-- {{ finally block }}
```

**Comment by tomblind** [comment]
Sorry, if I'm misunderstanding, but won't that always return from the main function even if there wasn't a return statement in the try/catch?

**Comment by hazzard993** [comment]
You're right 😞 looks like I'd have to scan for a return statement and compensate for that to get it to work
