### ISSUE TITLE
More js-compatible classes and support for decorators

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#269]
To implement decorator support classes should be constructed in the runtime

```typescript
class A {
  private a: number;
  private initializedField = Math.random();
  constructor(a: number) {
    this.a = a;
  }

  @DecoratedMethod
  foo() {
    return this.a + 1;
  }

  get bar() {
    return this.a * 2;
  }

  static staticMethod() {}
}
```

```lua
local A = ___TS_CreateClass({
  decorators = {Decorated},
  -- May be called with this = nil when used A() form
  constructor = function(this, a)
    this.a = a
  end,
  fields = {
    {
      kind = "field",
      key = "a",
      value = function() end
    },
    {
      kind = "field",
      key = "initializedField",
      value = function() return math:random() end
    },
    {
      kind = "method",
      decorators = {DecoratedMethod},
      key = "foo",
      value = function(this) return this.a + 1 end
    },
    {
      kind = "get",
      key = "bar",
      value = function(this) return this.a * 2 end
    },
    {
      kind = "method",
      static = true,
      key = "staticMethod",
      value = function() end
    }
  }
})
```

For more details and reasoning of using such a complex way to declare classes check out:

* [Decorators Proposal Repository](https://github.com/tc39/proposal-decorators)
* [Specification Stage 2 Draft](https://tc39.github.io/proposal-decorators/)
* [Short Description](https://github.com/tc39/proposal-decorators/blob/master/METAPROGRAMMING.md)
* [Babel REPL](https://babeljs.io/repl/build/8579/#?babili=false&browsers=chrome%2068&build=&builtIns=usage&spec=false&loose=false&code_lz=AIEQpgxg9gTghgFzAEwFAQDZwM7YAQCCeA3qnnnGXgJYB21C1cG1AXigGLVgZrnS1sCGAFcICWAAo4MAOYiAtmFoIAlCSrkEAC2rYAdHDwBeCnMXKEAbioBfVFVCRYiFAFkwOqHzwAzKFCS6qTk5DCeIjC0eDp6hngA1HgAjDbk9lSynngARjJBGqF44QiR0bEGRgBUeABMaXgZ5EKI1BB4LYwQHl7IBcT2tkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-0&prettier=false&targets=&version=7.0.0-beta.52%2Bpr.7976&envVersion=7.1.0)
* [Babel Transformation](https://github.com/babel/babel/tree/9d0dcedb2b42c95e51a7892b5139b752a98f6e20/packages/babel-plugin-proposal-decorators)
* [Babel Helpers](https://github.com/babel/babel/blob/9d0dcedb2b42c95e51a7892b5139b752a98f6e20/packages/babel-helpers/src/helpers.js#L1082) (it's quite big, but Babel implements all spec's features, it can be simplified in Lua)

Doing makes generated code further from what you'd write in Lua, but makes it match JS behavior more and gives a chance to solve #229 and #256.

**Comment by Perryvw** [comment]
I think for now this is not something we want to consider for this project (yet). Like discussed in other issues we do not necessarily want to recreate exact JavaScript behavior. I am not convinced yet this added complexity is worth it.

**Comment by ark120202** [comment]
I don't think there's any simple way to implement decorators, even if some of it's specifics would be dropped. So it's either some complicated way constructing classes or not supporting decorators at all.

**Comment by ark120202** [comment]
> The behavior bellow seems to be consistent to how typescript currently handles decorators.

TypeScript (and most of decorator-related things in JS now) implements a stage-0 decorators proposal. After that it changed a lot. Of course these decorators may be implemented, but stage-2 decorators may progress to stage-3, so they would be implemented in TypeScript (now there's only Babel support). No idea how TS team would handle migration, but in the end someday they will have to remove legacy proposal anyway.

**Comment by andreiradu** [comment]
Honestly, I have no idea how typescript will implement the stage-2 decorator proposal(and I don't fully understand the implications of it). It's not only a matter of migration(which would obviously be a pain), 
 it's also a matter of how they interact with the type system. You can read [this issue](https://github.com/Microsoft/TypeScript/issues/4881). 
From my point of view there is great value in decorators, and it would be a shame to put the perfect ahead of the good.

**Comment by ark120202** [comment]
Sure, I'm not saying that old decorators shouldn't be implemented. I assume that typescript would use different option for new proposal, so both proposals may be supported independently.

**Comment by ark120202** [comment]
Closing because of recent changes in the proposal
