### ISSUE TITLE
Data structure clear and garbage collection

### ISSUE THREAD

**Issue by ehemsley** [TypeScriptToLua/TypeScriptToLua#342]
I noticed that the clear functions transpile to the following:

```lua
function Map.clear(self)
    self.items = {};
    self.size = 0;
    return
end
```

This is fine from a computation performance perspective, however throwing away the table creates a huge amount of pressure when dealing with garbage collection. 

In contrast,
```lua
function Map.clear(self)
  for k in pairs(self.items)
    self.items[k] = nil
  end
  self.size = 0
  return
end
```
might be moderately slower, but creates no garbage from throwing away the table. 

Garbage collection is a huge issue when it comes to programming games, so perhaps there should be a way to specify which clear method is used?

**Comment by tomblind** [comment]
This was implemented as an external lib, so I'm closing it.
