### ISSUE TITLE
Assigning properties on functions

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#388]
Currently, this is allowed:
```ts
function foo() {}
foo.bar = "bar";
```
But it produces bad code since functions are not tables in lua.

A variant of this is namespace merging into a function:
```ts
function foo() {}
namespace foo {
    export let bar = "bar";
}
```

I'm not sure if there's a reasonable way to support this. It's probably just something that should be an error.

**Comment by ark120202** [comment]
> I'm not sure if there's a reasonable way to support this.

It's possible by using a backing table and `debug.setmetatable`:
```lua
local functionData = setmetatable({}, { __mode = 'k' })
debug.setmetatable(function() end, {
  __index = function(self, key)
    if functionData[self] ~= nil then
      return functionData[self][key]
    end
  end,
  __newindex = function(self, key, value)
    if functionData[self] == nil then
      functionData[self] = {}
    end
    functionData[self][key] = value
  end
})
```

Not sure how that affects performance and it won't work in sandboxed environments without `debug` (though it may be avoided by rewriting all property access to functions to a helper function)


I'm not sure if it's actually useful, to me it looks like an anti-pattern even in JS, but it's possible and shouldn't be hard to support.

**Comment by Perryvw** [comment]
I agree this looks like an anti-pattern, especially in TS where we have proper classes. My initial feeling is maybe we just disallow this and throw a nice error when we encounter it.

**Comment by tomblind** [comment]
I was thinking about this a bit, and a simpler solution could be to wrap the function in a table the first time a property is assigned to it (or when merged with a namespace).

```ts
function foo() {
    return "foo";
}
foo.bar = "bar";
```
=>
```lua
function foo(self)
    return "foo"
end
foo = setmetatable({}, {__call = foo})
foo.bar = "bar"
```

**Comment by pilaoda** [comment]
This only support the write behavior, but what if the read behavior happened before write?
