### ISSUE TITLE
Remove deprecated root-level options

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#397]
This removes the need to add `lua` before option names and would look better if more options would be added.

```js
{
	"lua": { // or tstl
	 	"target": "5.3",
	    "libImport": "inline"
	}
}
```

Another module that extends tsconfig, [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader#tsconfigjson), is doing the same.

**Comment by Perryvw** [comment]
Looks like an interesting idea, but why not create a luaconfig.json instead then?

**Comment by lolleko** [comment]
I don't think it matters much if its in its own object or just in the config root. Might be slightly nicer to have them grouped. But such a change would break all existing projects, which kinda sucks.

Im absolutely against having another config file, that will just make things more messy and harder to maintain imo.

**Comment by ark120202** [comment]
> But such a change would break all existing projects

Can't it be the same as with old compiler directives? Deprecate old names, use them as a fallback and remove in 1.0.0 (#365).

> Im absolutely against having another config file

+1 on this, most projects already have quite a number of config files.

**Comment by Perryvw** [comment]
I think indeed a path forward would be to support both for a while and eventually get rid of the global settings. I also agree another setting file might just end up cluttering the root of the project (look at the stuff in this project alone).

**Comment by ark120202** [comment]
Supported since #463 and root-level options were deprecated in #511.
