### ISSUE TITLE
Math.round isn't transpiled properly

### ISSUE THREAD

**Issue by enchantinggg4** [TypeScriptToLua/TypeScriptToLua#438]
dunno is there any lua's version, but currently transpiled to math.round, which doesn't exist

**Comment by Perryvw** [comment]
Lua only supports math.floor and math.ceil. If we want to add support for math.round we should decide on what rounding convention to take. The obvious choice here is to just follow JS's implementation, which always rounds up (round(0.5) = 1, round(-0.5) = 0).

**Comment by tomblind** [comment]
so maybe:
```ts
Math.round(x);
```
=>
```lua
math.floor(x + 0.5)
```

**Comment by Perryvw** [comment]
I think that is a good way of transpiling that. Next question: Do we want to just transform to this or do we want to add it to lualib?

My personal preference is probably the first, but from a clarity standpoint adding it to lualib might also be nice.

**Comment by tomblind** [comment]
For something this simple I'd just do a direct transform
