### ISSUE TITLE
Array types are not inferred properly sometimes

### ISSUE THREAD

**Issue by endel** [TypeScriptToLua/TypeScriptToLua#459]
This doesn't generate `#block.left` (lua equivalent for length)

```typescript
const block = {left: [[0, 1], [1, 2], [3, 4]]};
const blockLen = block.left.length;
```

This apparently works fine using latest version from `master` branch:

```typescript
const blockLeft: number[][] = block.left;
const blockLeftLen = blockLeft.length;
```

**Playground link:**

https://typescripttolua.github.io/play.html#src=const%20block%20%3D%20%7Bleft%3A%20%5B%5B0%2C%201%5D%2C%20%5B1%2C%202%5D%2C%20%5B3%2C%204%5D%5D%7D%3B%0Aconst%20blockLen%20%3D%20block.left.length%3B%0A%0Aconst%20blockLeft%3A%20number%5B%5D%5B%5D%20%3D%20block.left%3B%0Aconst%20blockLeftLen%20%3D%20blockLeft.length%3B%0A

**Comment by endel** [comment]
Updated playground usage case:

https://typescripttolua.github.io/play.html#src=interface%20ModuleBlock%20%7B%0A%20%20%20%20left%3A%20number%5B%5D%5B%5D%3B%0A%20%20%20%20top%3A%20number%5B%5D%5B%5D%3B%0A%20%20%20%20right%3F%3A%20number%5B%5D%5B%5D%3B%0A%7D%0A%0Aconst%20moduleBlocks%3A%20%7B%5Bid%3A%20string%5D%3A%20ModuleBlock%7D%20%3D%20%7B%0A%20%20%20%20square%3A%20%7B%0A%20%20%20%20%20%20%20%20left%3A%20%5B%5B0%2C%200%5D%2C%20%5B0%2C%2090%5D%5D%2C%0A%20%20%20%20%20%20%20%20top%3A%20%5B%5B0%2C%2090%5D%2C%20%5B120%2C%2090%5D%5D%2C%0A%20%20%20%20%20%20%20%20right%3A%20%5B%5B120%2C%2090%5D%2C%20%5B120%2C%200%5D%5D%2C%0A%20%20%20%20%7D%2C%0A%7D%0A%0Aconst%20moduleBlock%20%3D%20moduleBlocks.square%3B%0A%0Afor%20(const%20name%20in%20moduleBlock)%20%7B%0A%20%20%20%20const%20side%20%3D%20moduleBlock%5Bname%5D%3B%0A%0A%20%20%20%20for%20(let%20j%20%3D%200%3B%20j%20%3C%20side.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20const%20lineX%20%3D%20side%5Bj%5D%5B0%5D%0A%20%20%20%20%20%20%20%20const%20lineY%20%3D%20side%5Bj%5D%5B1%5D%3B%0A%20%20%20%20%7D%0A%7D

**Comment by tomblind** [comment]
The issue with this example is that TS infers the type of `moduleBlock[name]` as `any`, so all type info is lost. You can see this if you enable `noImplicitAny` in the config - the line where `side` is assigned becomes an error.

Unfortunately, I'm not sure much can be done about this. Once the type has changed, there's no way for TSTL to know the value is an array.

**Comment by lolleko** [comment]
We could force `noImplicitAny` as setting.

**Comment by tomblind** [comment]
I'm not requiring noImplicitAny is a good idea - it's useful to have off when converting existing code to TS.

**Comment by Perryvw** [comment]
The original issue is fixed, the second one is a typing issue in the example.
