### ISSUE TITLE
Wiki proposal: Differences between Lua and Javascript

### ISSUE THREAD

**Issue by endel** [TypeScriptToLua/TypeScriptToLua#462]
I propose to add this new section to the page [Differences between Lua and Javascript](https://github.com/TypeScriptToLua/TypeScriptToLua/wiki/Differences-between-Lua-and-Javascript):

## Traversal order of object properties

In JavaScript, property keys are traversed in the following order: 

First, the keys that are integer indices, in ascending numeric order. Then, all other string keys, in the order in which they were added to the object. Lastly, all symbol keys, in the order in which they were added to the object.

In Lua there is no order guarantee. See example below.

**JavaScript**

```javascript
var obj = { one: 1, two: 2, three: 3, four: 4, five: 5 };
for (key in obj) {
    console.log(k)
}
// one, two, three, four, five
```

**LUA**

```lua
local obj = { one = 1, two = 2, three = 3, four = 4, five = 5 }
for key, num in pairs(obj) do
    print(key)
end
-- four, one, three, five, two
```

**Comment by Perryvw** [comment]
Added a section for this https://github.com/TypeScriptToLua/TypeScriptToLua/wiki/Differences-between-Lua-and-Javascript#key-iteration-order
