### ISSUE TITLE
Expression as statements produce invalid lua

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#503]
```ts
"foobar";
1;

declare function foo(): number;
foo() + foo();
```
TS allows arbitrary expressions to be used as statements, but this is invalid in Lua. Lua only allows call expressions to be used as statements.

**Comment by ark120202** [comment]
From Lua AST standpoint the whole `ExpressionStatement` doesn't make much sense, it should be just `CallStatement: { expression: CallExpression }`.

**Comment by tomblind** [comment]
Yeah, I was thinking the same thing - although, in theory, future versions of lua could have other expressions that are allowed as statements.
