### ISSUE TITLE
How to make `local exports = exports or {};` into `local exports = {};` ?

### ISSUE THREAD

**Issue by zaoqi** [TypeScriptToLua/TypeScriptToLua#509]
How to make `local exports = exports or {};` into `local exports = {};` ?

**Comment by Perryvw** [comment]
That is not possible right now, why do you need this?

**Comment by zaoqi-unsafe** [comment]
@Perryvw 
I don't want it to have this feature that might produce unexpected results.

**Comment by Perryvw** [comment]
Do you have a concrete example where it produces unexpected results?

**Comment by tomblind** [comment]
A small downside to this is that it prevents luacheck from passing. Ideally generated code should be able to pass a basic lint, although in cases like this, that goal conflicts with full JS/TS compatibility.

**Comment by lolleko** [comment]
Since `local exports = exports or{}` is the first line in a file O doubt there will be any issues if we change it
to `local exports = {}`. It's probably even better because if someone defined `_G.exports` our current solution might break/cause issues.
The question is if this change would break reload systems?

**Comment by ark120202** [comment]
I actually think it also should be `local ____exports = {}`. ES Modules can't be modified dynamically by user, and `exports` looks very commonjs-like.

---

@lolleko it shouldn't break it. Local scope is separated from file scope, so unless there is some strange environment that defines `exports` on the module scope right after returning a value it shouldn't affect anything.

**Comment by Perryvw** [comment]
I don't think this actually interacts with the reload system since it's local. Sounds like this doesn't really serve a purpose and can be removed?
