### ISSUE TITLE
Runtime crash if a class extends Error

### ISSUE THREAD

**Issue by thatcosmonaut** [TypeScriptToLua/TypeScriptToLua#533]
If you define a class that extends Error and then construct it at runtime, Lua crashes with

```attempt to index field '____super' (a nil value)```

**Comment by ark120202** [comment]
Since Error class isn't implemented it's expected behavior.
For runtime it's the same as `class Foo extends undefined {}`

**Comment by ark120202** [comment]
Resolved in #724.
