### ISSUE TITLE
Arrays initialized with a spread operator on an iterator are empty

### ISSUE THREAD

**Issue by ehemsley** [TypeScriptToLua/TypeScriptToLua#534]
```ts
  const items = new Map<number, string>();
  items.set(2, "hello");
  items.set(5, "howdy");
  const new_array = [...items.entries()];
``` 
new_array will be empty in Lua.

I understand if this is not planned to be supported, but it would be nice to at least have the transpiler yell at me instead of having to debug an obscure issue in the transpiled code due to the empty array.

**Comment by ark120202** [comment]
I think we should support it, especially since we know that it's an iterator
