### ISSUE TITLE
Declaring a variable "error" and then throwing it causes a crash

### ISSUE THREAD

**Issue by ehemsley** [TypeScriptToLua/TypeScriptToLua#536]
```ts
const error = new MyError()
throw error.toString()
```
transpiles to

```lua
        local error = MyError.new()
        error(tostring(error))
```
which throws the error
`attempt to call local 'error' (a table value)`

**Comment by Perryvw** [comment]
It overrides the existing error. We have a similar issue in https://github.com/TypeScriptToLua/TypeScriptToLua/issues/188 where a user-declared variable overrides a lua environment variable without warning.

I'm not sure we have a decision on how to handle this yet, either silently fixing this by prepending some `__`'s or just throwing a TranspileError.

**Comment by ark120202** [comment]
Related to #429
