### ISSUE TITLE
 Property 'codePointAt' does not exist on type 'string'.

### ISSUE THREAD

**Issue by zaoqi** [TypeScriptToLua/TypeScriptToLua#539]
```
 Property 'codePointAt' does not exist on type 'string'.
Property 'fromCodePoint' does not exist on type 'StringConstructor'.
```

**Comment by ark120202** [comment]
We already support `fromCharCode` and `charCodeAt`. The only difference between char code and code point is full unicode support, which was decided against in #540.

I'm planning to refactor lualib, so maybe in future it would be possible to customize it with plugins (and it's already possible by extending transformer).
