### ISSUE TITLE
Feature request: unicode support

### ISSUE THREAD

**Issue by zaoqi** [TypeScriptToLua/TypeScriptToLua#540]
```
$ node
> "x你好啊"[0]
'x'
> "x你好啊"[1]
'你'
$ lua
> x="x你好啊"
> print(string.sub(x,1,1))
x
> print(string.sub(x,2,2))
�
```

**Comment by Perryvw** [comment]
This is out of scope for this project. We have no influence over the encoding Lua supports, and adding a workaround for this would be extremely impractical.

**Comment by zaoqi** [comment]
@Perryvw 

https://github.com/alexander-yakushev/awesompd/blob/master/utf8.lua

Maybe it can be an optional option.

**Comment by Perryvw** [comment]
You can write some `.d.ts` files for this one and just include it in your project!

**Comment by zaoqi** [comment]
@Perryvw How to replace string[...], string.length with this ?

**Comment by Perryvw** [comment]
You can not do that unfortunately, however, if you create a 'utf8.d.ts' and add `require("utf8")` to your code, that should work fine.

The file `utf8.d.ts` would look like this:
```ts
declare interface utf8 {
    /** Returns the number of characters in a UTF-8 string */
    len(this: void, s: string): number;

    /** Returns the substring of s from start to end (including end).   */
    sub(this: void, s: string, start?: number, end?: number): string;
}
```

And then you can just do:
```ts
declare function require(path: string): any;

const utf8: utf8 = require("utf8");

const myString = "abc";
const substr = utf8.sub(myString);
```

[Playground link](https://typescripttolua.github.io/play.html#src=declare%20interface%20utf8%20%7B%0A%20%20%20%20%2F**%20Returns%20the%20number%20of%20characters%20in%20a%20UTF-8%20string%20*%2F%0A%20%20%20%20len(this%3A%20void%2C%20s%3A%20string)%3A%20number%3B%0A%0A%20%20%20%20%2F**%20Returns%20the%20substring%20of%20s%20from%20start%20to%20end%20(including%20end).%20%20%20*%2F%0A%20%20%20%20sub(this%3A%20void%2C%20s%3A%20string%2C%20start%3F%3A%20number%2C%20end%3F%3A%20number)%3A%20string%3B%0A%7D%0A%0A%2F%2F%20%3D%3D%3D%3D%0A%0Adeclare%20function%20require(path%3A%20string)%3A%20any%3B%0A%0Aconst%20utf8%3A%20utf8%20%3D%20require(%22utf8%22)%3B%0A%0Aconst%20myString%20%3D%20%22abc%22%3B%0Aconst%20substr%20%3D%20utf8.sub(myString)%3B)
