### ISSUE TITLE
request: translate String.length to string.len instead of #...

### ISSUE THREAD

**Issue by zaoqi** [TypeScriptToLua/TypeScriptToLua#541]

**Comment by zaoqi** [comment]
If use `string.len`, I can implement https://github.com/TypeScriptToLua/TypeScriptToLua/issues/540 with `$ sed`.

**Comment by ark120202** [comment]
There are better ways to customize transpiler output: first one is extending `LuaTransformer` class and overriding any related methods there, and second one is using transformers (#433), which would be simpler, but isn't implemented yet.
