### ISSUE TITLE
Tuple/ Array bug

### ISSUE THREAD

**Issue by zaoqi-unsafe** [TypeScriptToLua/TypeScriptToLua#544]
https://gitlab.com/the-language/the-language/blob/cb8acab436254a0945828206ea6c085506af2992/core/pure/typescript/lang.ts#L223

https://gitlab.com/the-language/the-language/blob/cb8acab436254a0945828206ea6c085506af2992/core/pure/lua/lang.lua#L182

**Comment by zaoqi-unsafe** [comment]
needs `+1`

**Comment by ark120202** [comment]
Duplicate of #489
