### ISSUE TITLE
request: translate a.push(x) to a[#a+1]=x

### ISSUE THREAD

**Issue by zaoqi-unsafe** [TypeScriptToLua/TypeScriptToLua#546]

**Comment by lolleko** [comment]
Wee need that helper function. Because Array.push allows you to push  multiple items `arr.push(x, y, z)`.


You can write ` a[a.length]=x` which should transpile to `a[#a+1]=x`

**Comment by ark120202** [comment]
We could do it when it's a single argument as an optimization. Though not sure if the difference is really important there

**Comment by lolleko** [comment]
Still need to return the new length of the array according to specs.
We might be able to do that inline aswell. But I don't think that would be too easy.
