### ISSUE TITLE
Consider all files as modules

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#564]
TSTL target environment is closer to node/bundler, where each module is isolated even if it doesn't contain any imports/exports. Even though in TypeScript the following code declares a global `onEvent` symbol (mostly because of legacy environments support) in runtime you usually won't expect `_G.onEvent` to be defined.

```ts
function onEvent() {}
listenToEvent(onEvent);
```

**Comment by tomblind** [comment]
The issue with this is that a lot of lua environments (like games which use lua for scripting) do expect things to be declared globally. Probably not the best design decision on their part, but it is very common.

**Comment by ark120202** [comment]
What makes it even worse is that some environments expect it not being defined globally, but in a module environment (accessible with `_ENV` or `getfenv`) which could be `_G` in some cases or a separate object. Still, I think we should follow JS rules there, since that's too implicit.

There are few workarounds for this. We could just let user do it explicitly by assigning a value to env (what's done for dota entities today). Once we'll have module support we could provide an utility for that (like `defineEnvExport("Activate", Activate)`). We also could add a directive for that, but I think it's better to avoid adding new directives for something that can be easily done in runtime.

**Comment by Perryvw** [comment]
Maybe we could add a module types tsconfig option like TypeScript has to resolve this. I am not sure we should throw up such a barrier to usage. I think the current way we transpile modules makes sense to people using Lua. I am not convinsed we should change this unless we have a solid reason to do so.

**Comment by ark120202** [comment]
I think that at least we should change module detection logic to match TypeScript (module is a file that contains any imports/exports). These symbols are marked as unused anyway now.

I still think it would be nice to make everything local, but matching type checker behavior might be nice and that would break namespace-based organization (which is kind of considered deprecated, but it might be more familiar to some lua users). Hopefully someday TS would have an option for that.
