### ISSUE TITLE
Compiler errors are output to lua file

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#567]
If there is a tstl error when transpiling a file, the error itself is output to the resulting lua file. For example:
```ts
// main.ts
declare const a: { [k: string]: string; };
const o = {...a};
```
=>
```lua
-- main.lua
error("Unsupported object literal element kind: SpreadAssignment")
```

**Comment by ark120202** [comment]
It's expected since now diagnostics are returned by catching TranspileErrors and we always have to emit a file. Once #412 would be fixed these errors would become diagnostics and it always would emit some sensible output.
