### ISSUE TITLE
Class properties should override parent class accessors

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#576]

**Comment by tomblind** [comment]
Can you give an example of this not working? This seems to do the correct thing:
```ts
class A {
    get foo() { return "foo"; }
}

class B {
    foo = "bar";
}

const b = new B();
console.log(b.foo); // prints "bar"
```

**Comment by ark120202** [comment]
Oh, haven't expected it to work. However it works only because internally helper priorities property over accessor, so that would fail:

```ts
class A {
    get foo() { return "foo"; }
}

class B extends A {
    foo = undefined;
}

const b = new B();
console.log(b.foo); // prints "foo", expected nil
```

It also fails for setters

```ts
class A {
    set foo(value) { console.log(value); }
}

class B extends A {
    foo = "foo";
}

const b = new B();
b.foo = "bar";
// Prints: foo\nbar, expected no output
```

**Comment by tomblind** [comment]
Hmmm. When I try both of those examples in the TS playground, I get the same output as lua. That actually surprises me since I would think assigning `undefined` to `foo` would assign it as a value and override the accessor, but that doesn't seem to be the case.

**Comment by ark120202** [comment]
Looks like it's a relatively recent change in proposal: https://github.com/tc39/proposal-class-fields#public-fields-created-with-objectdefineproperty

**Comment by ark120202** [comment]
Related issue: https://github.com/microsoft/TypeScript/issues/31225

---

> prints "foo" in JS

![image](https://user-images.githubusercontent.com/11750369/57624451-62442000-75ab-11e9-96bd-c2da29cecd51.png)

> it's just a matter of assigning those properties with rawset in the constructor instead of using assignment

It also should remove all parent's accessors, like `[[Define]]` does

**Comment by tomblind** [comment]
Removing it isn't really viable since it's part of the prototype, but overriding it fully would probably work.

So, basically,
```ts
class B extends A {
    foo = "bar";
}
```
could be transpiled as something like:
```ts
class B extends A {
    _foo = "foo";
    set foo(value) { this._foo = value; }
    get foo() { return this._foo; }
}
```

**Comment by tomblind** [comment]
We could actually avoid the extra property with a little creativity:
```lua
function B.prototype.____constructor(self, ...)
    A.prototype.____constructor(self, ...)
    rawset(self, "foo", "foo")
end
function B.prototype.____getters.foo(self)
    return rawget(self, "foo")
end
function B.prototype.____setters.foo(self, value)
    rawset(self, "foo", value)
end
```

**Comment by ark120202** [comment]
Something like `B.prototype.____setters.foo = false` and a check in helpers might have a bit better performance, but not sure how it would affect overall helper perofrmance

**Comment by tomblind** [comment]
That's a good idea. Although to be honest, accessors are bad for performance in general and should be avoided in critical code 😄

**Comment by tomblind** [comment]
One issue with adhering to define semantics is that it will produce inconsistent results with the JS that TS would normally output.

Right now, TS outputs fields as assignments in the constructor. It's not clear when TS will update to support fields properly as laid out in that proposal. And even once it does, TSTL will need to update it's TS version.

I think there's an argument to be made to keep the current functionality in line with how the output JS works today, and update later when we upgrade TS to a version that supports the new way.
