### ISSUE TITLE
Unsupported Statement kind: ImportEqualsDeclaration

### ISSUE THREAD

**Issue by frank256** [TypeScriptToLua/TypeScriptToLua#587]
I get this error when I try to pull a Lua function that is found somewhere down a global table hierarchy, e.g. GlobalLuaTable.Graphics.draw, into the file scope:

```typescript
// Somewhere in .d.ts
declare namespace GlobalLuaTable {
  namespace Graphics {
    function draw(): void;
 }
}

// Then at the start of some .ts:
import draw = GlobalLuaTable.Graphics.draw;
```
This leads to the error `Unsupported Statement kind: ImportEqualsDeclaration`.

Of course, I might as well do 
```typescript
const draw = GlobalLuaTable.Graphics.draw;
```
but my IDE likes to insert these `import = ...` style imports instead. 

Any chance these will be supported? 

Thank you for a great project!

**Comment by Perryvw** [comment]
This looks like something we should be able to add without too much trouble. I'll mark it as a feature request and someone can pick it up.
