### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#597]
There should be some Lua environments with UI features where it would be useful. A simple solution would be just to use `transformJsx`, but it may have issues with factory function context.

**Comment by webD97** [comment]
This is an important feature to me. What would we need to do to implement this? I'd like to help with this if you guys do not have time

**Comment by Perryvw** [comment]
I've looked at this and the simplest method of doing this is to require the jsxFactory compiler option, and require react (if any) jsx (not preserve or react native). Then we need to just implement transformers for the different Jsx nodes to Lua and a bunch of tests ofcourse. JsxElement will be transformed to a call to the jsxFactory and its contents will be arguments.

Would this cover your use case? I think this is the simplest initial solution without really having to do any magic.

**Comment by Perryvw** [comment]
Only issue I'm slightly concerned about is how does the user supply the factory implementation, and how do we make sure it's in scope when used.

**Comment by webD97** [comment]
I will take a look at the code and see if I can contribute this. Might take a bit though.

**Comment by ark120202** [comment]
@tstirrat had a branch with some progress: https://github.com/tstirrat/TypeScriptToLua/commit/d1f1840e7a54dd6dd051c2fd8a9a424bbd599d96

**Comment by chrisd08** [comment]
FWIW, I made a lua plugin based on tstirrat's work: https://gist.github.com/chrisd08/f8af91c8ae51d30364605c00e323c9f7

It would be awesome if someone figured out how to use React's actual reconciler, haven't had the time or patience to look into it myself.
