### ISSUE TITLE
Iteration stops at first nil

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#600]
[Playground](https://typescripttolua.github.io/play.html#src=function*%20foo()%20%7B%0A%20%20%20%20yield%201%3B%0A%20%20%20%20yield%20null%3B%0A%20%20%20%20yield%203%3B%0A%7D%0A%0Afor%20(const%20value%20of%20foo())%20%7B%0A%20%20%20%20console.log(value)%3B%0A%7D%0A)

**Comment by tomblind** [comment]
A simple (but not optimal) solution would be to box the value in a table and extract it in the for loop.
```lua
for ____TS_boxedValue in __TS__Iterator(foo(_G)) do
    local value = ____TS_boxedValue[1]
    print(value)
end
```

**Comment by ark120202** [comment]
Iteration in lua stops when first value is `nil`, so it just should always pass `true` first and actual value second (see #601).

**Comment by tomblind** [comment]
Yeah, if we have a completely custom iterator function for generators instead of using `__TS__Iterator`, that would be a better solution.
