### ISSUE TITLE
Generator optimization

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#601]
Now we have two kinds of iterators - lua-like (functions) and js-like (objects with `next` method). The idea is to make generated js-like iterators contain data to make lua iteration faster. Additionally, all iterator functions are extracted to helpers to avoid extra allocations.

[Input on Playground](https://typescripttolua.github.io/play.html#src=function*%20foo(argument)%20%7B%0A%20%20%20%20yield%201%3B%0A%20%20%20%20yield%20argument%3B%0A%20%20%20%20return%203%0A%7D%0A%0Aconst%20it%20%3D%20foo(2)%3B%0Aconst%20x1%20%3D%20it.next()%3B%20console.log(x1.value%2C%20x1.done)%0Aconst%20x2%20%3D%20it.next()%3B%20console.log(x2.value%2C%20x2.done)%0Aconst%20x3%20%3D%20it.next()%3B%20console.log(x3.value%2C%20x3.done)%0A%0Afor%20(const%20v%20of%20foo(2))%20%7B%0A%20%20%20%20console.log(v)%20%2F%2F%201%2C%202%2C%203%0A%7D)

```lua
local ____symbolMetatable = {__tostring = function(self)
  if self.description == nil then
    return "Symbol()"
  else
    return "Symbol(" .. tostring(self.description) .. ")"
  end
end}
function __TS__Symbol(self, description)
  return setmetatable({description = description}, ____symbolMetatable)
end
Symbol = {iterator = __TS__Symbol(_G, "Symbol.iterator")}

-- New helpers:

local __TS__IterableCoroutine = {}
local __TS__IterableArguments = {}

function __TS__IterateStep(self)
  local co = self[__TS__IterableCoroutine]
  local args = self[__TS__IterableArguments]
  local status, value
  if args then
    status, value = coroutine.resume(co, unpack(args))
    self[__TS__IterableArguments] = nil
  else
    status, value = coroutine.resume(co, self)
  end

  if coroutine.status(co) == "dead" then
    return
  end

  if not status then
    error(value)
  end

  -- Fix for #600
  return true, value
end

function __TS__Iterate(result)
  if not result[__TS__IterableCoroutine] then
    -- TODO: Fallback for manually constructed iterators
  end

  return __TS__IterateStep, result
end

function __TS__GeneratorNext(self, ...)
  local co = self[__TS__IterableCoroutine]
  local args = self[__TS__IterableArguments]
  local status, value
  if args then
    status, value = coroutine.resume(co, unpack(args))
    self[__TS__IterableArguments] = nil
  else
    status, value = coroutine.resume(co, ...)
  end

  return {
    done = coroutine.status(co) == "dead",
    value = value,
  }
end

function __TS__GeneratorIterator(self)
  return self
end

function __TS__Generator(fn)
  return function (...)
    local args = {...}
    return {
      [__TS__IterableCoroutine] = coroutine.create(fn),
      [__TS__IterableArguments] = args,
      next = __TS__GeneratorNext,
      [Symbol.iterator] = __TS__GeneratorIterator,
    }
  end
end

-------------------------------------------------------------------------------

local foo = __TS__Generator(function(self, argument)
  local ____ = coroutine.yield(1)
  local ____ = coroutine.yield(argument)

  return 3
end)

local it = foo(_G, 2)
local x1 = it:next()
print(x1.value, x1.done) -- 1 false
local x2 = it:next()
print(x2.value, x2.done) -- 2 false
local x3 = it:next()
print(x3.value, x3.done) -- 3 true

for ____, value in __TS__Iterate(foo(_G, 2)) do
  print(value) -- 1, 2
end
```

**Comment by tomblind** [comment]
This looks like a really good direction for these. A couple thoughts:

Handling the initial arguments could be simplified a lot by wrapping the function passed to coroutine.create:
```lua
[__TS__IterableCoroutine] = coroutine.create(function() return fn(unpack(args)) end),
```
Then, you won't need to track it and check for it every iteration. Of course, the trade-off is an extra piece of garbage.

When transforming `for (const v of foo(2))` to `for ____, value in __TS__Iterate(foo(_G, 2))`, how will you know to add the initial dummy parameter? In this particular example, you could probably check that foo is a generator, but what if foo is called outside of the for...of loop?
```ts
const bar = foo(2);
for (const v of bar) {
    ...
}
```

**Comment by ark120202** [comment]
> Handling the initial arguments could be simplified a lot by wrapping the function passed to coroutine.create

Yeah, I have thought about that, but assumed it would be more performant that way. I probably should benchmark both solutions.

> how will you know to add the initial dummy parameter

Well, when `__TS__Iterate` is used we always can safely assume it.

**Comment by tomblind** [comment]
Ok, so I assume the standard iterator fallback will return this initial value as well.

Regarding performance, I suspect the answer will be: it depends. Functions that only yield a couple times like the example will benefit more from avoiding the extra lambda. But heavy functions that yield a lot will perform better without the per-iteration checks.
