### ISSUE TITLE
Unsupported OmittedExpression in array

### ISSUE THREAD

**Issue by hazzard993** [TypeScriptToLua/TypeScriptToLua#603]
```ts
let x = [0, , 2];
```

`src/main.ts:10:12 - error TSTL0: Unsupported expression kind: OmittedExpression`

**Comment by Perryvw** [comment]
What would you expect to happen here? The tricky issue here is that if you simply translate this to `{0, nil, 2}`, your array will appear to only have one element (the 0) in lua.

**Comment by ark120202** [comment]
> your array will appear to only have one element (the 0) in lua

It's possible to have same result with `[0, undefined, 2]` anyway, so nothing to do there differently. I think for now `{0, nil, 2}` is fine, it's possible to iterate over such arrays with a custom iterator and `nil`s is a separate issue.
