### ISSUE TITLE
Pluggable transformer design

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#615]
`LuaTransformer` class now has a number of issues:
* Ability to extend it isn't a plugin system - you can do it only once, you can override things you aren't meant to, we are limited with public/protected/private when designing visitor API
* If you want to extend it, you always have to use it with API, so you also have to re-implement `tstl` even when you don't want to change anything there
* 5500 lines is too much

The idea is to make whole transformation be composed of plugins. A plugin is a function that receives `context: TranspilerContext` and returns an object. Context is an object with some state that may be passed to utility functions.

Project structure:
- src/transformers
  - utils
    - index.ts
    - type-checks.ts
    - lua-ast-utils.ts
    - ...
  - class.ts
  - call.ts
  - try.ts
  - ...

Example transformer:

```ts
import { escapeString, isTupleReturnCall, isArrayType, createUnpackCall, transformLuaLibFunction } from "./utils";

export const someTransformer = (context: TranspilerContext): TranspilerPlugin => ({
    visitors: {
        [ts.SyntaxKind.StringLiteral]: node => escapeString(node.text),
        [ts.SyntaxKind.SpreadElement](node) {
            const innerExpression = context.transformExpression(node.expression);
            if (isTupleReturnCall(context, node.expression)) {
                return innerExpression;
            }

            const type = context.checker.getTypeAtLocation(node.expression);
            if (isArrayType(context, type)) {
                return createUnpackCall(innerExpression, node);
            }

            return transformLuaLibFunction(context, LuaLibFeature.Spread, node, innerExpression);
        },
    },
});
```

**Comment by Perryvw** [comment]
I'm archiving some of the discussion related to this issue on discord:

A possible way to achieve this design with mixins:
[TypeScript playground demo](http://www.typescriptlang.org/play/index.html#code/MYGwhgzhAEAqBOYB2EBmB7eBbApvaAllgA4g65IAuMAypWJeTlQsmprvADTQCiAHsXg4oBdElZIM2PNADeAWABQ0VdGIBXAEYgCwaJUQppWOgyZUAFAEoAXNAiGCSAObzowyhvhJoAIj8AbmgAX2U1dW1dfUM2EwEhEQgxJBt7R3hnNzkPHC8ffyDQ8LVNHT0DI3ZsACFnMHgATwThUXE0hydXd09vXwDgsKUh5VBIWnpGCkpJas5oHH5GJAATGFmTWUUVUqiK2OMOMynmSg6MrPkSiNVegsoACwIIADoDuZaklJtA6+Lh5SjcBQPiCVrJcSSTb4RbLNZwKrQwgkMjTGB1JANZpgr6QxEcLaAnaqMrRSpxDgYrGfNqpOydTLdHJ3fpFEbEyLlGL47A0iF09JdbJ-CIsgxPV7vExUpp877WX4cobssYgmXYxK0jYEmFLZjwuV45BI7YRUn7HlYdWGgUMy6mm63PJ9fwPHAgEDoIJ-ZVEsDEUiNACyBH4zgglhtUJ1PAA2tacVrLXgALoK5T+wMhsMoSzamTcaCx44WGbJwtRozQtOK5SoDRIYCUFLQTMgYOh8OWFZ4AgANxwKwAwpRMPZkI0eFpIDgR5gIOOkI1Y2mrhzpxBZ6P4K9pLwwMAHpYN1vMNAALwAPjXjtUAHktAArHBNl4uPJ3gDuSAACvB0MQeCUI0AByYC4BGJ5zvALxCOgo7AYB1gvHuB5HpiuAXteDq3moD7Pq+PaoM4OB-gBQGNN2vYDsO26wf+CGNIBPAYTgPD4S+lBvh+35kYB8DAQAIiIwCZMQ27HjO0H0fB8FMWx0CsdYACE6YchEIRqRpansn2DTkocBYXopOCfgiFIFj8GZkAJlhSjqbyWiW0w2GpQLjNAQ4aI46BWvUsqJvy+bzLC+rov5GrgikwWEhy5rchZfmYgFmr8ucQo3reYp+Fo6BeoqGnKOybYdjmEYxYWsZeT5SXUoF0XljWyh6fg9kFgATMZSCmeZhmcFZShgDZZxtZw7WOYlzmnK5tZKEAA)

I still have to figure out what exactly are the pros and cons of this approach relative to the already suggested setup.

We also looked at a slightly different version to the code @ark120202 already provided above:
[TypeScript playground demo](http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgIIGUAqA5A9gExQG8BYAKGUuQGtR8AuZPQgaToG5yBfciEAVwC2TAhDYh8yUhSoAhUHCgBPAKIAPAA5QIAZx3BcIADTdy5MEo0pMUOCB0xcUQXDAGQAJV38ANmGQAvMg6YFCgAObIAD7I-BIQMKAQ+JxkFlbINnYOTsJBABQgoowYOKJGyAiGkGpgjFn2js6u7gDC1RC1AJSBAHyZto25LYZeOr7+MXGEiSDJqeQIPnB6A9lNLm6G7eCd-tJUyBr8AEY+wAjIoeu5zBCFxWhYd131gznNW57eflLkh4cAG6KK7vDbQQJXAAWwB0ADpwhAwA0PoJoA9CHDaBIugsZADkMAYMh8tchs5oD0DgSAdowPwoCBQTcKVAMRAKmAYTpcf8aTwyHyCXSGUzpgkkikhcgBdKtMBgZBmeS0VAdJC5gB3ZAAWTgGgAPHdxPgKiiNr18rzBfijmFFShEciwbl0diGCJWHRXmsVdFYvFZsk-rbDiLGdDYXCyajoPCnfl3dbDrLbcczhdgkjza62e7GMa6JyXZ93G8WYIfVzYSGaZH4THwWq4TokYmi8rUSMQMmaeGmdWdKkU6YbVV7P4ND5+OFQJD8uOanVfV2vjslz0Av1qZQYHEEF9Oxt0GBXBA0eB2SVnqIfTnS6MfvtpWGkaLKh1atGS4I7uze5QqaHHuIAHu4R65OoWi6PohhXk8ZSEHeP7dmMEy1n2b4RouezfhWf5FEhw5UEBVAgWBhgQc48ggIoqiaNoejuPBpQvOWKqoU+GHClhTIAERQhAPg+LgfHEYBZi2jhX6ts6FbooWEhwjRdFQYxsHGFRggqcoakwe41qpuQwJQB+uy1BqEDavemxtJ+YBWqkU4zqAC72dacA+NADnSWAeEqn+RD5p6Yh0MpCi6Qx+mGFwXTWkAA)

Personally I am not decided yet if I am happy with all transformation methods in a plugin hard-coupled to the same context. An alternative would be to pass the context to every transformation method as follows:
[TypeScript playground demo](http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgIIGUAqA5A9gExQG8BYAKGUuQGtR8AuZPQgaToG5yBfciEAVwC2TAhDYh8yUhSoAhUHCgBPAKIAPAA5QIAZx3BcIADTdy5MEo0pMUOCB0xcUQXDAGQAJV38ANmGQAvMg6YFCgAObIAD7I-BIQMKAQ+JxkFlbINnYOTsJBABQgoowYOKJGyAiGkGpgjFn2js6u7gDC1RC1AJSBAHyZto25LYZeOr7+MXGEiSDJqeQIPnB6A9lNLm6G7eCd-tLkVMga-ABGPsAIyKHrucwQhcVoWPdd9YM5zVue3n5Sh0cqAA3RTXD4baCBa4AC2AOgAdOEIGAGp9BNBHoR4bQJF0FjJAchgDBkPkbkNnNAetJCYTtGB+FAQGDbpSoJiIBUwLCdHiAYSeGR+YD6YzmdMEkkUsLBcKtMAQZAWRT0VAdFC5gB3ZAAWTgGgAPPdxPgKqiNr18nyhQTjmFFSgkSjwbkMTiGCJWHQ3msVdFYvFZsl-rajqKmTC4fDyWjoAinfl3dajrLbSdzpdgsjza72e7GMa6FyXV93O9WYIfdy4SHaZGETGIWr4TpkYmi8q0SMQMnaeHmdWdKkU6YbTA4ghvp2NugwK4IOjwBySi9ypUOrVyyruzsamAfTnS6Nfvthf317tatGS4J7hzranxyBJ+5p7l1FpdPpDMvnmVCBUVSXnUvpdt8u57AeN7dmMEy1lQ55AXu14VneRSEA+ZhkE+L6GG+zjyCAiiqJo2h6O4v6lPcgEbiBh6bG0tFQRWMEnvBlDngARNCEA+D4uCcakqYglAF57hqEDavRO60VaqRIXsLbZjeGKFhI8KEcRH5kd+xj4YImnKNpX7uNa5BwD40BgPkClXo2dyiPkRD5p6Yh0BpChGaRJmGFwXTWkAA)

Further opinions/suggestions are always welcome!
