### ISSUE TITLE
Declared function is different in output

### ISSUE THREAD

**Issue by pawel-miczka** [TypeScriptToLua/TypeScriptToLua#632]
Hi, today i wrote something like this in TS:

```
declare function output(message: String): Boolean;

output("fdsa");
```

then i compiled this into:

```
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
output(nil, "fdsa")
```

Why is there first parametr to "nil"?

My tsconfig.json:

```
{
  "compilerOptions": {
      "strict": true,
      "target": "es6",
  },
  "tstl": {
      "luaTarget": "5.2",
      "luaLibImport": "inline",
  }
}
```

**Comment by tomblind** [comment]
By default, all transpiled functions receive an initial 'context' parameter. This is for compatibility with how Typescript/Javascript work. There's a Wiki page that discusses the issue, although it needs some work: https://github.com/TypeScriptToLua/TypeScriptToLua/wiki/Functions-and-the-%60self%60-Parameter

**Comment by pawel-miczka** [comment]
```
/** @noSelfInFile */
```

This thing above helped 👍. Is there any way to disable it by default because I don't want to write this comment for every function i declare?

**Comment by tomblind** [comment]
Currently, that's the simplest way to do it. Perhaps a tsconfig option to do it project-wide could be added.

**Comment by ark120202** [comment]
Why would you need to add it for every function? `@noSelfInFile` enables it on all functions in file.

**Comment by pawel-miczka** [comment]
Ok, good. I read that i don't need to add it to every function which is nice. I can write it only once which is nice. Thanks for anything ✌
