### ISSUE TITLE
Use TupleTypes to produce tupleReturn behaviour

### ISSUE THREAD

**Issue by hazzard993** [TypeScriptToLua/TypeScriptToLua#649]
TypeScript can identify TupleTypes (`[...]`) and I think they can be used to tell TypeScriptToLua that a callable function returns multiple values instead of an array without the use of `@tupleReturn`.

```ts
let a: () => [number, string];                // ✔ Tuple
let b: () => [...number[]];                   // ✔ Tuple
let c: () => string[];                        // ❌ Array
let d: () => Array<string>;                   // ❌ TypeReference
let e: () => [number, string] | [number];     // ❌ UnionType (this could still count)
```

I think by adding this feature it makes TypeScriptToLua more generic and compatible with existing TypeScript declarations for Lua environments and modules as it puts less of a requirement on TypeScriptToLua specific directives.

It would also only improve existing code written for TypeScriptToLua as tuple return functions without the `@tupleReturn` directive would no longer generate and return a table.

A new directive named `@tableReturn` can be used if a user specifically wants to define a function that returns a table array which they want to represent by using a tuple instead of _Array<T>_ or _any[]_ (seems unlikely but this directive keeps it possible).

```ts
/**
 * Returns two numbers.
 */
function tuple(): [number, number] {
    return [3, 4];
}

/**
 * Returns a table with two numbers.
 * @tableReturn
 */
function table(): [number, number] {
    return [3, 4];
}

/**
 * Also returns a table with two numbers.
 */
function table2(): number[] {
    return [3, 4];
}

// TypeScriptToLua needs to prevent this because tuple and array types are incompatible.
const returnArray1: () => number[] = tuple;

// This is okay because table has @tableReturn
const returnArray2: () => number[] = table;

// tuple2 is still [number, number]
declare const tuple2: () => ReturnType<typeof tuple>;
```

**TypeScript can see TupleTypes and array types as compatible types** which can create issues.

One that I can think of not mentioned in the code above is this:

```ts
declare let a: () => [number, number] | number[];
let [x, y] = a();   // c() could return a tuple or an array of numbers. What happens here???
```

In this case a LuaLib can be used.

```lua
local x, y = __TS_TupleOrTableAssignment(a())
```

**Comment by Perryvw** [comment]
I don't think this would work. We looked at dealing with tuple types like this initially, but there are several problems that make it not worth it imo.

First there is the issue you noted where TypeScript will thtink tuple and array types can be compatible, even though in lua they are not.

Secondly, there is no reason lua functions could not `return { item1, item2 }`  instead of `return item1, item2`. Without the  directive you would lose the ability to make a distinction between these two cases.

The main difficulty is that we do not control external API and need to accomodate for all cases, if there was no external API or declarations this could work.

**Comment by hazzard993** [comment]
This isn't a solution to handle all tuple return cases. `@tupleReturn` would still exist alongside `@tableReturn` to give users control over what they want to return.

Both these directives contradict what the transpiler would assume from an array signature if a directive was not available.

```ts
declare function ab(): [number, number];    // Tuple return
/** @tableReturn */
declare function cd(): [number, number];    // Table return

declare function ef(): number[];            // Table return
/** @tupleReturn */
declare function gh(): number[];            // Tuple return
```

This is for scenarios like if lua-types never got its `@tupleReturn` directives and someone wanted to use what was defined there with TypeScriptToLua. Atm someone would need to clone lua-types and add `@tupleReturn`s to most functions to make it work with TypeScriptToLua specifically.

Users of any TypeScript to Lua transpiler will run into the same issues TypeScriptToLua resolved with `@tupleReturn`. So this is more a step towards making TypeScriptToLua more generic and work with other existing Lua declarations.

On the contrary it could help those declarations be used in other TypeScript to Lua transpilers at long as the transpiler considers the same tuple/table rules which will be more likely than both transpilers using directives with the same name.

This doesn't benefit #580 or #579. Its more an additional default rule to follow if a directive isn't used.

**Comment by ark120202** [comment]
* TS tuples, [by definition](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple), are just a more strict version of array type, not something specific. At least for me it'd be very surprising to get different result for something that has same meaning in TS. Also `[number, number]` and `number[] & { length: 2 }`.
* TS types generally should be interpreted consistently everywhere, but that way a tuple used in function return position would have a different meaning from tuple used anywhere else.
* `<T extends any[]>(): T` - could be a tuple or an array depending on call site. Similar problems with tuple mapping.
* > In this case a LuaLib can be used.
  > local x, y = __TS_TupleOrTableAssignment(a())

  What about `[number[]] | number[][]`?

* > This doesn't benefit #580 or #579. Its more an additional default rule to follow if a directive isn't used.

  #580 basically means adding a strict dependency on tstl declaration library, which makes it incompatible with your main point.

---

> Other TypeScript to Lua transpilers

Are there any (not taking non-generic ones into account)? I personally don't think it makes sense to pursue something like that. It's impossible to write a spec for generic conversion of 2 different languages, declaration interpretation is a major part of transpiler design itself. We still would have a lot of different points, like iterables, classes and context handling.

**Comment by ark120202** [comment]
@hazzard993 since you have opened #821, which is pretty much opposite to this proposal, do you think it can be closed?

**Comment by hazzard993** [comment]
Yeah doesn't seem like the best idea, always appreciate the discussions though 🙂
