### ISSUE TITLE
Compiler directive @membersOnly remove namespace info

### ISSUE THREAD

**Issue by lightrabbit** [TypeScriptToLua/TypeScriptToLua#659]
Soucre code:
```TypeScript
declare namespace wifi {
  /** @compileMembersOnly */
  enum WifiMode {
    NULLMODE = 0,
    STATION = 1,
    SOFTAP = 2,
    STATIONAP = 3
  }
}
console.log(wifi.WifiMode.STATION);
```

Expected output
```lua
print(wifi.STATION);
```

Actual output
```lua
print(STATION);
```

I am trying to write a TypeScript declaration file for [NodeMCU](https://www.nodemcu.com/index_en.html)'s Lua environment.

There are many different modules under this environment. For example, the [Wifi module](https://nodemcu.readthedocs.io/en/master/modules/wifi/) has a lot of constants used in different functions.
For example [`wifi.setmode()`](https://nodemcu.readthedocs.io/en/master/modules/wifi/#wifisetmode) uses `wifi.STATION`, `wifi.SOFTAP`, `wifi.STATIONAP`, `wifi.NULLMODE` 
[`wifi.setphymode()`](https://nodemcu.readthedocs.io/en/master/modules/wifi/#wifisetphymode) uses `wifi.PHYMODE_B`, `wifi.PHYMODE_G`, `wifi.PHYMODE_N`

In order to better group these constants, I need to write a declaration file like this:
```TypeScript
declare namespace wifi {
  /** @compileMembersOnly */
  enum WifiMode {
    NULLMODE = 0,
    STATION = 1,
    SOFTAP = 2,
    STATIONAP = 3
  }

  /** @compileMembersOnly */
  enum PhyMode {
    PHYMODE_B = 1,
    PHYMODE_G = 2,
    PHYMODE_N = 3
  }

  function setmode(mode: WifiMode, save?: boolean): WifiMode;
  function setphymode(mode: PhyMode): PhyMode;
}
```
However, when I use this declaration file, the compiler removes the information about the namespace in which these enumerated types are located. As mentioned at the beginning.

**Comment by Perryvw** [comment]
That seems like a bug indeed.
