### ISSUE TITLE
Readonly tuples aren't considered arrays

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#664]
[Playground](https://typescripttolua.github.io/play.html#src=const%20foo%20%3D%20%5B1%2C%202%5D%20as%20const%3B%0Afoo%5B0%5D%3B%0A)

**Comment by tomblind** [comment]
It seems like we're not using a new enough version of TS to support this?
```ts
const foo = [1, 2] as const; // error TS2304: Cannot find name 'const'.
foo[0];
```

It looks like we're using 3.5.2 which does support `as const`, but TSTL still throws this error when I try to compile.

**Comment by ark120202** [comment]
It's really weird:
- Errors in editor on playground are expected, because monaco TS version isn't guaranteed to match our one
- It works fine in our code
- Somehow while `as const` doesn't work in tests, readonly tuple syntax that was added in the same version works:

```ts
// Syntax from #609
util.testFunction`
    const foo: readonly [number, number, number] = [1, 2, 3];
    return foo[1];
`.debug();
```

```
    Lua Code:
        local ____exports = {}
        function ____exports.__main(self)
            local foo = {1, 2, 3}
            return foo[1]
        end
        return ____exports
    Value: 1
```

I also have reproduced it in a simple project that uses tstl from npm:

![image](https://user-images.githubusercontent.com/11750369/61187143-a32de300-a687-11e9-8e1f-d9c153f1943a.png)
