### ISSUE TITLE
Bad destructuring of nested alias arrays in objects

### ISSUE THREAD

**Issue by Validark** [TypeScriptToLua/TypeScriptToLua#678]
Problem code:
```ts
const obj = {
    y: [new Map([["a", 1]])]
};

let d: string;
let e: number;

({
    y: [[[d, e]]]
} = obj);

console.log(d, e); // a 1
```
Mirrors https://github.com/roblox-ts/roblox-ts/pull/568

Playground: https://typescripttolua.github.io/play.html#src=const%20obj%20%3D%20%7B%0A%20%20%20%20y%3A%20%5Bnew%20Map(%5B%5B%22a%22%2C%201%5D%5D)%5D%0A%7D%3B%0A%0Alet%20d%3A%20string%3B%0Alet%20e%3A%20number%3B%0A%0A(%7B%0A%20%20%20%20y%3A%20%5B%5B%5Bd%2C%20e%5D%5D%5D%0A%7D%20%3D%20obj)%3B%0A%0Aconsole.log(d%2C%20e)%3B%20%2F%2F%20a%201

**Comment by ark120202** [comment]
By the time this issue was created we didn't support assignment destructuring, but now the only missing feature for it to work is #590
