### ISSUE TITLE
Enums as array index

### ISSUE THREAD

**Issue by triggerhappy187** [TypeScriptToLua/TypeScriptToLua#687]
In 0.23.0 the following code seemed to work properly.

```typescript
let swapItm = equipment.item[itm.slot];
```

It would compile to:

```lua
local swapItm = equipment.item[itm.slot + 1]
```

After updating to 0.24.0 or higher I noticed all my code using enums for array indicies stopped working. I realized the code was now compiling to the following:

```lua
local swapItm = equipment.item[itm.slot]
```

Another interesting thing to note in 0.24.0+ is that the +1 gets added in some situations.

```typescript
let swapItm = equipment.item[itm.slot + 0];
```

compiles to 

```lua
local swapItm = equipment.item[(itm.slot + 0) + 1]
```

**Comment by ark120202** [comment]
Sounds like #650. What is the type of `itm.slot`? I wouldn't expect current `isNumberType` implementation to handle all cases, but it should work for a simple enum type.

**Comment by tomblind** [comment]
I'm having trouble reproducing this - can you show me the enum declaration?

**Comment by triggerhappy187** [comment]
I was able to reproduce it with the code below

```typescript
enum EquipmentSlot {
    NONE,
    HEAD,
    NECK,
    SHOULDER,
    CHEST,
    BACK,
    WRISTS,
    HANDS,
    WAIST,
    EARRING,
    RINGA,
    RINGB,
    FEET,
    MAINHAND,
    OFFHAND
}


class CustomItem {
    slot=EquipmentSlot.CHEST;
}

class UnitEquipment {
    public item: CustomItem[] = [];
}

function tsMain(){
    const itm = new CustomItem();
    const equipment = new UnitEquipment();
    const swapItm = equipment.item[itm.slot];
}
```

and for my tsconfig.json

```json
{
    "compilerOptions": {
      "target": "es6",
      "lib": ["es6"],
      "strict": true,
      "noImplicitAny" : true,
      "noImplicitThis" : true,
      "alwaysStrict" : true,
      "strictNullChecks" : true,
      "outDir": "src",
    },
    "include": ["src-ts"],
    "tstl": {
      "luaTarget": "5.3",
      "noHeader": true,
      "luaLibImport": "require",
    }
  }
```

**Comment by Perryvw** [comment]
One idea I suspect is that it is typing slot as EquipmentSlot.CHEST instead of EquipmentSlot which might be messing up the enum detection. I'd be curious what would happen if the class was:
```ts
class CustomItem {
    slot: EquipmentSlot = EquipmentSlot.CHEST;
}
```
That could give a hint as to what is goinog on.

**Comment by tomblind** [comment]
It looks like the issue is that an enum type is seen by TS as a union of all the possible values. `isNumberType` doesn't recurse into unions so it never sees that it is numerical.
