### ISSUE TITLE
Unwrap parenthesis around expressions before doing syntactical checks

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#704]
Few examples of issues it causes:
https://typescripttolua.github.io/play.html#src=const%20%5Bx%2C%20y%5D%20%3D%20(%5B1%2C%202%5D)%3B%0A%0A%2F**%20%40tupleReturn%20*%2F%0Afunction%20foo()%20%7B%20return%20(%5B1%2C%202%5D)%3B%20%7D%0A%0A(%5B%5D.length)%20%3D%201%3B%0A%0Aclass%20A%20%7B%7D%0Aclass%20B%20extends%20(A)%20%7B%7D%0A%0A(Object.keys)(%7B%7D)%3B%0A

**Comment by Perryvw** [comment]
Fixed in 1.13.2
