### ISSUE TITLE
Cannot declare a global variable named 'this'

### ISSUE THREAD

**Issue by Grafu** [TypeScriptToLua/TypeScriptToLua#712]
![image](https://user-images.githubusercontent.com/11540828/64079918-b14ac800-ccf6-11e9-93af-41be0e604dad.png)

This happens when declaring a variable 'this' and it's type in .d.ts file.

**Comment by Perryvw** [comment]
This sounds like a tricky situation, since essentially you want to redefine an existing JS keyword. Which environment is this for?

**Comment by ark120202** [comment]
Even if you'd be able to somehow declare it globally (which is likely impossible), it would be impossible to access it just with `this`, since it's a keyword at usage position as well.

One workaround would be declaring it as a part of `_G`:
```ts
declare const _G: typeof globalThis & { this: Type };
_G.this; // => Type
```

Alternatively you can rename it at runtime:
```ts
const self: Type = (_G as any).this;
self // => Type
```

**Comment by Perryvw** [comment]
@ark120202 what about at runtime doing something like `const _this = globalThis.this`?

**Comment by ark120202** [comment]
Yeah, that also works. Though it would require a cast to `any` as well.

**Comment by Grafu** [comment]
Multi Theft Auto. It is using hidden local variable injecting pattern into callback functions. One of those variables is named 'this' and it's scope is only the callback function scope.

https://wiki.multitheftauto.com/wiki/AddEventHandler

**Comment by ark120202** [comment]
You can do `getfenv(1).this` or `_ENV.this`, but generally declaring scope-specific variables as global isn't a good idea. I'd make a small wrapper that would pass env as an argument, like

```ts
interface EventContext {
	this: ...;
	// all other scope elements
}

function addEventHandlerWrapper(eventName: string, attachedTo: element, handler: (event: EventData) => void) {
	addEventHandler(eventName, element, () => handler(getfenv(1) /* or _ENV for Lua 5.3 */))
}

addEventHandlerWrapper('name', ..., (context) => {
	context.this;
});
```

**Comment by Perryvw** [comment]
Closing as we cannot do anything about this for now.
