### ISSUE TITLE
TypeScript 3.6 breaks how JSDoc comments work

### ISSUE THREAD

**Issue by TheLartians** [TypeScriptToLua/TypeScriptToLua#713]
## source

```typescript
/** @noSelfInFile */

/**
 * This is the require docstring
 */
declare function require(modname: string): any;

require("test")
```

## compiled
```lua
require(nil, "test")
```

## expected
```lua
require("test")
```

**Comment by tomblind** [comment]
I can't seem to reproduce this. Can you show your tsconfig?

**Comment by Perryvw** [comment]
The TS version (both local/global verions) might also be relevant.

**Comment by TheLartians** [comment]
@tomblind sure, the minimum tsconfig that reproduces the error for me is:

```json
{
  "include": ["."],
}
```

In this case it gets compiled to `require(_G, "test")`, as strict mode is not enabled. I'm also using npm to download the most recent version of tstl (0.27.0).

**Comment by TheLartians** [comment]
@Perryvw the local version according to the `package-lock.json` is 3.6.2. My global version is 3.3.3.

**Comment by tomblind** [comment]
I had a local ts version of 3.5.2 - I just updated to 3.6.2 and now I'm getting the broken behavior.

**Comment by Perryvw** [comment]
This seems to be as a result of https://github.com/microsoft/TypeScript/issues/32062, for now I have pushed a patch version that locks TS to version 3.5.x until we figure out how to deal with this. We can use this issue to track progress.
