### ISSUE TITLE
@noSelfInFile does not work for non-namespaced function declarations

### ISSUE THREAD

**Issue by Grafu** [TypeScriptToLua/TypeScriptToLua#717]
Declaration file:
![image](https://user-images.githubusercontent.com/11540828/64370306-ddcc5000-d026-11e9-973e-99406d13c659.png)

Source: 
![image](https://user-images.githubusercontent.com/11540828/64370349-f472a700-d026-11e9-8daa-0cff60b7de21.png)

Output:
![image](https://user-images.githubusercontent.com/11540828/64370385-02c0c300-d027-11e9-8d53-b08f2df223f4.png)

**Comment by ark120202** [comment]
It should be supported, you're likely hitting #713. Make sure you're using latest tstl version.

**Comment by Grafu** [comment]
![image](https://user-images.githubusercontent.com/11540828/64375822-6cdd6600-d02f-11e9-966a-1588faaf3100.png)

**Comment by tomblind** [comment]
It's possible you ran `npm install` before we restricted the TS version to 3.5. Will you try running `npm install` again and see if that fixes it?

**Comment by Grafu** [comment]
Ran 'npm install' and 'npm install -g', but still no success.

**Comment by ark120202** [comment]
`npm view` queries information from npm registry, so it's not the state of your local installation.
Try `npm ls typescript-to-lua` and `npm ls typescript`.

**Comment by Grafu** [comment]
Fixed, thx.
