### ISSUE TITLE
Inherited accessors break when base is type-erased

### ISSUE THREAD

**Issue by TheLartians** [TypeScriptToLua/TypeScriptToLua#725]
When extending type-erased bases with accessors, the accessors are called with incorrect `this`. 

## Example

```typescript
const A = class {
    get value(): this {
        return this;
    }
} as any;

class B extends A {
    
}

const b = new B();
console.assert(b.value === b); // boom
```

**Comment by ark120202** [comment]
In general I don't think can give any guarantees that code would work after being casted, but in this case it's possible to reproduce it without cast: [Playground](https://typescripttolua.github.io/play.html#src=function%20wrap(c%3A%20new%20()%20%3D%3E%20%7B%20value%3A%20object%20%7D)%3A%20new%20()%20%3D%3E%20%7B%20value%3A%20object%20%7D%20%7B%0A%20%20%20%20return%20class%20extends%20c%20%7B%7D%0A%7D%0A%0Aconst%20Wrapped%20%3D%20wrap(class%20%7B%20get%20value()%20%7B%20return%20this%20%7D%20%7D)%3B%0Aconst%20foo%20%3D%20new%20Wrapped()%3B%0Aconsole.assert(foo.value%20%3D%3D%3D%20foo)%3B)

**Comment by TheLartians** [comment]
We could simply always set `prototype.__index = __TS__Index(prototype)` for all inherited classes, but that would probably impact performance for inherited members. 
Perhaps we should always check the base class for an existing `__index` metafunction of and forward it to the outer metatable when necessary.
