### ISSUE TITLE
forEach doesn't parse full array when indexes have gaps.

### ISSUE THREAD

**Issue by CrashLemon** [TypeScriptToLua/TypeScriptToLua#742]
__TS__ForEach does not necessarily parse the full arrays if the keys do not represent the array count. The function does not take into consideration gaps between index keys and will attempt to loop through an array only using its count.

Ex: 
```let testArray: boolean[] = []
testArray[0] = true
testArray[1] = true
testArray[3] = true

testArray.forEach((bool: boolean) => {
    print(bool);
})
```

Will output: 
```
true
true
```

**Comment by lolleko** [comment]
This is a known limitation and is also the case if you iterate via `for ... of` 
https://github.com/TypeScriptToLua/TypeScriptToLua/wiki/Differences-between-Lua-and-Javascript#list-length

Discussion on this topic is tracked in https://github.com/TypeScriptToLua/TypeScriptToLua/issues/262
