### ISSUE TITLE
Transpiling Math.atan2 to math.atan2

### ISSUE THREAD

**Issue by Sanjo** [TypeScriptToLua/TypeScriptToLua#746]
Currently `Math.atan2(y, x)` is transpiled to `math.atan(y / x)`.

`math.atan2` is available in [Lua 5](https://www.lua.org/manual/5.1/manual.html#pdf-math.atan2).

> math.atan2 (y, x)
Returns the arc tangent of y/x (in radians), but uses the signs of both parameters to find the quadrant of the result. (It also handles correctly the case of x being zero.)

Therefore `Math.atan2(y, x)` can be transpiled to `math.atan2(y, x)` for the extra functionality of quadrant checking and handling the case of x being zero.

**Comment by Perryvw** [comment]
It is a little more complicated: Lua 5.1, 5.2 and I'm assuming lua JIT (should be checked) do support `math.atan2`. Lua 5.3 however does not have `math.atan2`, but instead takes an optional second argument to `math.atan`, which allows it to function as `atan2` https://www.lua.org/manual/5.3/manual.html#pdf-math.atan

**Comment by Sanjo** [comment]
The `math.atan2` function is labelled as deprecated but still available in Lua 5.3. See https://www.lua.org/manual/5.3/manual.html#8.2 and I have tested if the math.atan2 function exists in Lua 5.3.5. So until the function is removed in a future version of Lua, it could be just transpiled directly to `math.atan2`. I have also verified that `math.atan2` is available in LuaJIT 2.1.0-beta3.

**Comment by ark120202** [comment]
> I have tested if the math.atan2 function exists in Lua 5.3.5

Are you sure about that? I don't have it in a standard 5.3.5 build, maybe you had some compatibility flags enabled?
