### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#785]
The first thing I suggest is moving documentation from GitHub Wiki to the website:
  - It's properly versioned
  - It's easier to modify it for contributors
  - It can be edited locally, with a proper code editor
  - It would have more user-friendly interface
  - We would be able to add some interactive features, like embedding playground to docs (see https://github.com/microsoft/TypeScript-Website/issues/130 for more examples)

One thing that has to be decided is a static site generator we're going to use. I've checked out most of popular JS generator, and I think the best ones we can choose would be either [Gatsby](https://www.gatsbyjs.org/) or [Docusaurus](https://v2.docusaurus.io/). Docusaurus supports more things out of the box, but Gatsby has a rich plugin system, making it easier to customize.

Another thing I propose is moving website/documentation to this repo. That's a more controversial change (though that's a [quite](https://github.com/facebook/create-react-app/tree/master/docusaurus) [common](https://github.com/facebook/jest/tree/master/website) [practice](https://github.com/yarnpkg/berry/tree/master/packages/gatsby)), and it has it's tradeoffs, but there are a bunch of advantages as well:
  - It makes it even more easier to modify it, because adding a feature and documenting it can be done in one PR
  - It's much easier to do playground deployment previews for PRs, which is very useful for previewing changes without local checkout (we would be able to do it like [Prettier](https://github.com/prettier/prettier/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) does, otherwise we'll have to write a bot to do that)
  - It has full access to raw code, so it would be easier to generate API documentation from JSDoc

**Comment by Perryvw** [comment]
I think it makes sense to look at alternatives to the wiki. Having docs in this repo makes sense. We still want to deploy to typescript-to-lua.github.io though, which has to be done through the GitHub pages of the other repository. How are you planning on doing the deployment? I would VERY much prefer if we could restrict the docs in this repo to just markdown.
