### ISSUE TITLE
noSelfInFile / noImplicitSelf not working for callbacks

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#816]
**Playground:**

https://typescripttolua.github.io/play.html#src=%2F**%20%40noSelfInFile%20*%2F%0A%0Afunction%20cb(param%3A%20any)%3A%20string%20%7C%20number%0A%7B%0A%20%20%20%20return%20%22%22%0A%7D%0A%0A%5B%5D.map(cb)%3B%0A

**Current Behaviour:**  TSTL Error

**Expected Behavior:** No Error

**Current Workaround:**

https://typescripttolua.github.io/play.html#src=%2F**%20%40noSelfInFile%20*%2F%0A%0Afunction%20cb(param%3A%20any)%3A%20string%20%7C%20number%0A%7B%0A%20%20%20%20return%20%22%22%0A%7D%0A%0A%5B%5D.map(v%20%3D%3E%20cb(v))%3B%0A

**Comment by ark120202** [comment]
It looks like a valid error for me

**Comment by ark120202** [comment]
Related discussion in Discord: https://discordapp.com/channels/515854149821267971/600291243523702805/671454018106687544
