### ISSUE TITLE
Binding patterns are assigning values to global variables

### ISSUE THREAD

**Issue by hazzard993** [TypeScriptToLua/TypeScriptToLua#822]
```ts
// 0.30.1

const [a, b] = [1, 2];
// a, b = 1, 2

const [a, [b]] = [0, [1]];
// local ____ = {0, {1}}
// a = ____[1]
// b = ____[2][1]

const { a } = { a: 3 };
// local ____ = {a = 3}
// a = ____.a
```

[Playground](https://typescripttolua.github.io/play.html#src=const%20%5Ba%2C%20b%5D%20%3D%20%5B0%2C%201%5D%3B)

**Comment by ark120202** [comment]
Could you give some more context? It's expected to happen in top level scope of non-module files, matching TS logic

**Comment by hazzard993** [comment]
I see, I misunderstood the output. In that case it is working as intended!
