### ISSUE TITLE
`for...of` loop over `LuaTupleIterable` doesn't correctly transform complex binding patterns

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#840]
[Playground](https://typescripttolua.github.io/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoBKALngBlkoAVZABwhAEkMQYoAjZgHgG1UyALZcOAXQB8AbgBQoSLAQp02PPC6xSFanUbM2Hbn36CRYmOKlyA9DfiHOa-DgBuHeLE4BPAM7wGKF9fEH8oCAh4HER4DAALUIQwINDZO3gFaDgkNExcfERCbXgzUQl+cVt7TKUc1XyNLXIS0osrCrk0+wBhFPgARlkwPF8MTxgfeABeEv6AGngAJgWAZkrZQph4In4vKG8AOmZUAHN48SiYwuISEngAbwBfWS74XpCl2WYxgA85EB+DBwMDG93gP3gz02234Pwu0QINzuTxe6XeCBWXxAY28cmhO343isl0aMFIyOeQA)

```ts
declare function foo(): LuaTupleIterable<[number]>;
declare function bar(): LuaTupleIterable<[[number]]>;
// Iteration over arrays passes all of these cases
// declare function foo(): [number][];
// declare function bar(): [[number]][];

// Case 1
const array = [1, 2, 3];
for ([array.length] of foo()) {}

// Case 2
let x;
export { x }
for ([x] of foo()) {}

// Case 3
let y;
for ([[y]] of bar()) {}
```

**Comment by Perryvw** [comment]
LuaTupleIterable no longer exists
