### ISSUE TITLE
Error: Unsupported node kind: VoidExpression.

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#844]
`void function test () {}`;

Playground (check console for error.):

https://typescripttolua.github.io/play#code/G4ewlgJgBAZgrgOwMYBcwgVFBTAziqACgEooBvAXyA

More information on void expressions/operator:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

I am not sure why you would need that operator (maybe useful for iife?), just stumbled upon it by accident.
But I think this should be properly handled by tstl. 
Either transpile it somehow or return a proper diagnostic.

**Comment by lolleko** [comment]
A usecase for void expressions: They can be used to supress unused parameter warnings/errors:

```
function test (param1: string) {
    void param1;
}
```

**Comment by Perryvw** [comment]
This has been implemented a while ago

**Comment by Zamiell** [comment]
> A usecase for void expressions: They can be used to supress unused parameter warnings/errors:

for posterity, I think it is much more idiomatic in typescript to prefix the unused param with an underscore, which makes it ignored from typescript and/or the eslint rule
