### ISSUE TITLE
Class getter issues

### ISSUE THREAD

**Issue by cipherxof** [TypeScriptToLua/TypeScriptToLua#845]
I have something similar to the following:

```typescript
const test = new TestCase();
console.log(test.name);

const itm = new TestItem();
console.log(itm.name);
```

The problem is `test.name` actually calls `TestItem`'s getter method. The same code works properly with standard TypeScript. You can see it running properly with a full test case on the [TypeScript Playground](https://www.typescriptlang.org/play/?ssl=32&ssc=23&pln=30&pc=1#code/C4TwDgpgBMEM7ABYEMB2ATANtAvFA3gL4DcAUKJDPMAO4CW6A5hMFHkWQMabJxxQAVagAk0WCAB4BUCAA9YGfrAQoM2AHwEohUt178hCAOoNmrOQvQGRY7BOW1TLTflJQoYAK4AjTHU5QZlB+AGYQABQAlARu7lAATiye8ahQAAxk7jo6ujx8gtQAwrzQFhCKBcZOrK7uYPF0AG7IsFAA+qjIALa4UABEAIJ9ZLFBnT1RMXFQnAD2qHCz2AB0mLOM4X2GwMVwEG0A4iwAct0QfZGZcYnAyalIdHDLHWdX2aS5+pXAAJKwXTJ5OUrN8TEwWFMPA1mq0Xj02P0AELDD51Hx+AJjM6TWpxOYLJYQVbrTbbP4QLqHE5nC5Xdw3O4wRCPZ7jCBvUg5fEIKg8vCoCA0b67CKXXTzRYrNYbBzLNmXKAAekVULoqGA-C21HJlKOwFOPT6UDVCAgyHQUFmIX62xFVP1NI+3NYdGAAP5gu+OqiXAlhOJG1dXTlZ0uQA).

I am using TSTL 0.32.0 with TypeScript 3.8.3. The code works fine with 0.31.0.

**Comment by ark120202** [comment]
[Playground](https://typescripttolua.github.io/play/#code/BTCUAIF4D5wbwL6gHQGMCGAbTwB2BXbUAbgChTVN0Bna8AIRoFN5TxwBzJgF3AH0wrduwBOPfCNzgADGXYJSCilVrgAguCYAPbk1wATOo2os4bTj3C50AWyaCzw8GO4SpAcnTu54BUso0Rpo6eoYMzEIWvNZ2Duai4pLg7gBG3uZ+5AAOIgCWuNx4TADu6mDIMUwkpDn5hbglDOWV1bUFIA2lxvYQNODouACeKC3EQA)
