### ISSUE TITLE
Incorrect paths in source maps in subfolders

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#855]
When a ts file in a subfolder is transpiled with a source map and output to another folder (using `outDir`), the source map does not contain the correct relative path information to find the original source.

Example:

*tsconfig.json*
```json
{
    "compilerOptions": {
        "sourceMap": true,
        "rootDir": "ts",
        "outDir": "lua"
    },
    "include": [
        "ts/sub/foobar.ts"
    ]
}
```

*lua/sub/foobar.lua.map*
```
{"version":3,"sources":["foobar.ts"],"names":[],"mappings":";MAAY","file":"foobar.lua","sourceRoot":"..\\ts"}
```

In this example, the map would point to `lua/ts/foobar.ts` instead of `ts/sub/foobar.ts`.

The obvious thing to do would be to fix sourceRoot in these situations:
```
{"version":3,"sources":["foobar.ts"],"names":[],"mappings":";MAAY","file":"foobar.lua","sourceRoot":"..\\..\\ts\\sub"}
```

But, looking at typescript's output for the same project, it seems they opt to include the path information in `sources`:
```
{"version":3,"file":"foobar.js","sourceRoot":"","sources":["../../ts/sub/foobar.ts"],"names":[],"mappings":"AAAA,OAAO,CAAC,GAAG,CAAC,QAAQ,CAAC,CAAC"}
```

TS only uses `sourceRoot` when it's explicitly declared in `tsconfig.json`:
```
{
    "compilerOptions": {
        ...
        "sourceRoot": "ts"
    },
    ...
}
```
```
{"version":3,"file":"foobar.js","sourceRoot":"ts/","sources":["sub/foobar.ts"],"names":[],"mappings":"AAAA,OAAO,CAAC,GAAG,CAAC,QAAQ,CAAC,CAAC"}
```
Perhaps emulating that would be the ideal solution.

**Comment by dainkaplan** [comment]
Taking a quick look at the source code, it looks like the transpilation is only taking the the file name, not the full path:

https://github.com/TypeScriptToLua/TypeScriptToLua/blob/9bef35de6544dac67bc60a34e5074149bba57d48/src/transpilation/transpile.ts#L102
```typescript
            const { code, sourceMap, sourceMapNode } = printer(
                program,
                emitHost,
                sourceFile.fileName, // Look here
                luaAst,
                luaLibFeatures
            );
```

However, the `LuaPrinter` class is expecting a full path based on the code in the constructor:

```typescript
    public constructor(private options: CompilerOptions, private emitHost: EmitHost, fileName: string) {
        this.sourceFile = path.basename(fileName);
    }
```

It seems like this might be fixed by a one line change to `transpile.ts`:

```
            const { code, sourceMap, sourceMapNode } = printer(
                program,
                emitHost,
                sourceFile.fileName, // change this to sourceFile.fullFileName
                luaAst,
                luaLibFeatures
            );
```

All untested, though!
