### ISSUE TITLE
Can't use additional command line options when using --project

### ISSUE THREAD

**Issue by lolleko** [TypeScriptToLua/TypeScriptToLua#863]
```
➜ npx typescript-to-lua -lt JIT -p tsconfig.json 
npx: installed 5 in 3.62s
error TSTL: Option 'project' cannot be mixed with source files on a command line.
```

**Comment by lolleko** [comment]
Okay the problem is that the TS parser identifies JIT as file name so this check https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/src/cli/tsconfig.ts#L19 will always fire if any tstl specific option is specified.

I think it would be okay to just remove that check
the only problem that would lead to is that `tstl -p tsconfig.json file.ts` would be allowed and would just transpile the project ignoring the additional file.ts

It seems like TS hasn't figured out what do in that case either https://github.com/microsoft/TypeScript/issues/27379

**Comment by ark120202** [comment]
We might try to remove mistakenly parsed filenames, just like we do with `parsedCommandLine.errors` https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/src/cli/parse.ts#L126-L131
