### ISSUE TITLE
Statements before import

### ISSUE THREAD

**Issue by pilaoda** [TypeScriptToLua/TypeScriptToLua#877]
The import statements are always hoisted to the top of the lua code, but I need to execute some other code to implement something like decryption according to the environment.
```
if IsClient() then
  return {}
end

local A = require("A")
-- run some server code
```

**Comment by ark120202** [comment]
EcmaScript modules have to be hoisted according to the specification. If you want to avoid this behavior you can just not use ESM for this case, for example:

```ts
print("Executed before imported file");
const A: typeof import("A") = require("A");
```

Though your example has an another issue - ESM also have to be static. In this case you could do something like this:

```ts
// module.ts
const moduleServer: typeof import("./module-server") | undefined = IsClient() ? undefined : require("module-server");
const notImplementedOnClient = () => {
	throw 'module cannot be used on client';
};
export const doSomethingOnServer = moduleServer?.doSomethingOnServer ?? notImplementedOnClient;

// module-server.ts
export function doSomethingOnServer() {}
```

**Comment by pilaoda** [comment]
@ark120202 Thanks your reply!
The import statement may be too complicated, but it is amazing.

I also want to share the solution I came up with recently and see if there is any problem.
I use a custom [printer](https://typescripttolua.github.io/docs/api/plugins#printer) plugin to insert my lua code during the compilation.
```typescript
// test.ts
Pre(`
print("before import") -- inserted lua code
`)

import { a } from "./moduleA";
a();
```
compile to

```lua
-- test.lua
print("before import") -- inserted lua code

local ____exports = {}
local ____a = require("moduleA")
____a()
```

The function `Pre(code:string)` will be detect in my printer plugin and insert the lua code string before import statements.

**Comment by ark120202** [comment]
> I also want to share the solution I came up with recently and see if there is any problem

If it works well for your use case it's fine. Though personally I'd go with something like that:

```ts
prepend(() => {
	print("before import");
});
```

Because writing code in literals means no tooling (formatting, linting, type check) support. Repositioning AST nodes shouldn't be much more complex than whatever you're already doing in printer plugin.
