### ISSUE TITLE
Using for without ipair

### ISSUE THREAD

**Issue by colmugx** [TypeScriptToLua/TypeScriptToLua#879]
input
```
for (const item of list) {}
```

get
```
for ____, item in ipairs(list) do
end
```

But I got `db:urows`, you can see this: [http://lua.sqlite.org/index.cgi/doc/tip/doc/lsqlite3.wiki#db_urows](http://lua.sqlite.org/index.cgi/doc/tip/doc/lsqlite3.wiki#db_urows)

so expected result
```
for title, date in `list` do
end
```

so how can I do?

**Comment by ark120202** [comment]
You could do this by annotating a declaration with `@luaIterator`. Check out https://typescripttolua.github.io/docs/advanced/compiler-annotations#luaiterator for more details

**Comment by colmugx** [comment]
Oops.. 
Thanks for your help.
