### ISSUE TITLE
Auto-update `typescript-to-lua` package in first-class dependent projects

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#886]
We have a bunch of projects that directly depend on tstl package:
- https://github.com/TypeScriptToLua/TypeScriptToLua.github.io
- https://github.com/TypeScriptToLua/typescript-tstl-plugin
- https://github.com/TypeScriptToLua/lua-types

Right now any a release of `typescript-to-lua` package can break these projects, and it can go unnoticed for a long time. As a part of our release workflow we send a webhook to run an action in these repos, to update a version in package.json, run tests, and either open a pull request or make a commit to master.

**Comment by lolleko** [comment]
Website now has a dependant configuration that (hopefully) should open a PR if tstl gets updated on npm
see: https://github.com/TypeScriptToLua/TypeScriptToLua.github.io/commit/64b681517d30fed0545dc8e7ea63745f4ce09536

**Comment by lolleko** [comment]
https://github.com/TypeScriptToLua/typescript-tstl-plugin/commit/a17551d817c6477f89ed8612dce628f1eab0532f
https://github.com/TypeScriptToLua/lua-types/commit/651ab444f71d40d491eb9ab1bd19b0e1993573f3
