### ISSUE TITLE
const assertion on tupleReturn causes pack+unpack on return value

### ISSUE THREAD

**Issue by tomblind** [TypeScriptToLua/TypeScriptToLua#893]
[playground](https://typescripttolua.github.io/play#code/PQKhAIAEBcFcAcA2BTASsuAnAduEwAoAM1mwGNoBLAe1yOuoAoBKcAbwPC-Ew1h3ABtAET1qwgDThhAIwCGmYQF1wcgM7gytNdADcBAL5A)

**Comment by Perryvw** [comment]
tupleReturn is removed in favor of LuaMultiReturn, so I'm closing this
