### ISSUE TITLE
VScode Types validation hints don't work when "tstl" key is added to tsconfig.json

### ISSUE THREAD

**Issue by Claudiohbsantos** [TypeScriptToLua/TypeScriptToLua#900]
I have come across a weird quirk of vscode + typescript + tstl that I'm not sure how to debug properly. Admittedly I am very new to the typescript world so it's possible it has nothing to do with TypescriptTLua

## The Problem

When I add the "tstl" key to my tsconfig, vscode stops displaying live .ts errors on the problems such as *"Type '32' is not assignable to type 'string'."*. As soon as I remove the tstl key it works as expected again.

tsconfig.json
```json
{
  "exclude": ["node_modules"],
  "tstl": {}
}
```

example.ts
```typescript
const a: number = "string";
const b: string = 32;
```

**Expected**:  Vscode should show *"Type '32' is not assignable to type 'string'."*
**Result**: No validation errors are shown

### Notes:
- I have tried populating the tstl options in tsconfig.json with their defaults, and got the same result
- if I delete the tstl key from tsconfig vscode immediately starts recognizing validation errors

### Versions:
- vscode: 1.46.1
- vscode typescript (shown in status bar): 3.9.4
- tstl: 0.34.0

### Reproduction:
repo: https://github.com/Claudiohbsantos/tstl_issue_vscodevalidation_reproduction

**Comment by Perryvw** [comment]
Hmm, very strange bug. I cloned your reproduction repo and everything seems to be working as intended. Your tsconfig is not really what I would expect for a TypeScript project, but I am using the same TS version (the vscode one 3.9.4) and it works for me, so seems like that is not the issue?

There are a couple things I am curious about:
In your project root, what happens if you run:
```
tsc
```
And what about?
```
npx tsc
```

For reference, here is a tstl project that is part of our dota 2 template, maybe the example is useful to you: https://github.com/ModDota/TypeScriptAddonTemplate/tree/master/game/scripts/vscripts

**Comment by ark120202** [comment]
Do you have [TypeScriptToLua VSCode extension](https://marketplace.visualstudio.com/items?itemName=ark120202.vscode-typescript-to-lua) installed? It's a bit outdated so it might cause such issues

**Comment by Claudiohbsantos** [comment]
> Do you have [TypeScriptToLua VSCode extension](https://marketplace.visualstudio.com/items?itemName=ark120202.vscode-typescript-to-lua) installed? It's a bit outdated so it might cause such issues

That was exactly it, I forgot I had it installed when putting up the issue. Thanks for the tip. As soon as I uninstalled the extension vscode started behaving as expected again. 

> Hmm, very strange bug. I cloned your reproduction repo and everything seems to be working as intended. Your tsconfig is not really what I would expect for a TypeScript project, but I am using the same TS version (the vscode one 3.9.4) and it works for me, so seems like that is not the issue?

Thanks for the quick answer. That tsconfig was just the bare minimum I could get to to make sure it wasn't somehow a conflict between a compilerOption and tstl.
