### ISSUE TITLE
Structurally to array assignable Parameters<T> are not transpiled to unpack() when using rest operator

### ISSUE THREAD

**Issue by Grafu** [TypeScriptToLua/TypeScriptToLua#902]
```
declare function test<TEvent extends keyof Events>(...arguments: Parameters<Events[TEvent]>): boolean;

interface Events {
    hmm: (a: boolean, b: number, c: string) => void,
}

function triggerSeparatedClientEvent<TEvent extends keyof Events>(localArguments: Parameters<Events["hmm"]>, remoteArguments: Parameters<Events[TEvent]>) {
  test(...localArguments);
  test(...remoteArguments);
}
```
https://typescripttolua.github.io/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAeAFQFEA3EVDeEAD0NWCPgGsQBPHReDToYiAPgAUAOmmwA5sgC2wogC54ABVhQlhGEVJD6RANpVa9ALqiAlGoBGOHBBBRUAbgBQHrPRAxEUGAIhiLwAN4e8FHwABYKCmriUPaOzq4ANPB2aqiKdn6ZYGokMD6y1vAAvKLw1DhYwOkeAL5eKOjYeASlsrJ+AMogAA5ahMAAwhBYwiEUIYwsdOxcvPyC5iISEDhgUBAAgjDySkZqmjDaILr6ISYARHEKd1aZcAo4hIfHymdaOn43DYmMzCKwVCJRQgkKTSba7A5HRTKayeSHEDAwyRvD4gL5IowolpAA

`...remoteArguments`  is not transpiled to unpack(remoteArguments) when using rest operator on it, even though its type `Parameters<Events[TEvent]>` is structurally assignable to array

**Comment by Perryvw** [comment]
This seems to be fixed
