### ISSUE TITLE
Custom inherit model 

### ISSUE THREAD

**Issue by ZhaoXiangXML** [TypeScriptToLua/TypeScriptToLua#918]
I’ve an existing lua project which has a class model that one lua “class” can inherit form a C# class.

When porting this project to typescript, my plan is to write declaration class for that C# class, and have a ts class inherit from that one.

So my problem is, instead of `__TS__ClassExtends `, can I call a custom function in this case.

**Comment by ark120202** [comment]
You can do it at runtime by reversing what `__TS__ClassExtends` does and adding you own logic: [Playground](https://typescripttolua.github.io/play#code/MYGwhgzhAECC0G8C+AoFABYBXCAXA9gLYCSAdgBYCmATgJa5inCUqiQwBC0lAHrpaQAmMeMjQAzLE1y18paNjxEyVOgyaUAFA2oBzSrgBc0AGJTgMuQEpEKaPYVy80AEaRKAYXBRoAXmjaYHoG0JChpACeVgB0APrxsRBYAA40ANx2DhAGhAZgDC4gWjr6uAA00FKClOK0pJSCVhkO0Nm4uQwFRYHBuNHJ1PgEuBGpFVU1dQ1WmfYA9HPQAKJ8AoLQJSEA7vTkru5e7ChIQA)

**Comment by ZhaoXiangXML** [comment]
Good idea, thanks!

**Comment by ZhaoXiangXML** [comment]
Well this does not work for me.

The base class has no `prototype` field, so things when wrong at this line in `__TS__ClassExtends`:

```lua
setmetatable(target.prototype, base.prototype)
```

**Comment by ZhaoXiangXML** [comment]
I think the best thing I can do is implement my own `__TS__ClassExtends` method and replace the default one

**Comment by ark120202** [comment]
In that case I'd recommend to create a plugin. Overriding lualib methods wouldn't be possible after #653

**Comment by ZhaoXiangXML** [comment]
I did something like this in a lua file and require it before everything else:

```lua
require("lualib_bundle")
local vanilla__TS__ClassExtends = __TS__ClassExtends

local function __TS__ClassExtends(target, base)
	if base.prototype then
		vanilla__TS__ClassExtends(target, base)
	else
		// custom inheritance logic here
	end
end

_G.__TS__ClassExtends = __TS__ClassExtends
```

It looks like working as expected.

**Comment by ZhaoXiangXML** [comment]
I'll see what I can do with plugins...

**Comment by ZhaoXiangXML** [comment]
OK I've things up and running with a plugin now. It solves this problem and #921 for me.

I'll use the plugin in real projects, and open source it later once it's mature enough.

Thanks for all the help.
