### ISSUE TITLE
problems with @customConstructor

### ISSUE THREAD

**Issue by ZhaoXiangXML** [TypeScriptToLua/TypeScriptToLua#921]
I'm trying to write TS bindings for a third party lua lib.

This lib constructs class in the following way: 

```lua
CS.Namespace.Class()
```

There could be special characters in class names in some cases, so it could be:

```lua
CS.Namespace.['Dictionary`2']()
```

I've come up with some workarounds:

```TypeScript
declare namespace CS.System {
    /**
     * @customConstructor CS.System.Test
     */
    class Test {
        constructor()
    }

    namespace Generic {
        /**
         * @customConstructor CS.System.Generic["Dictionary`2"]
         */
        class Dictionary {
            instance(): void
            static stat(): void
        }
    }

    class Generic {
        /**
         * @customConstructor CS.System.Generic["Dictionary`2"]
         */
        static "Dictionary`2": typeof CS.System.Generic
    }
}

const Test = CS.System.Test

const a = new Test()

const b = new CS.System.Generic.Dictionary()

const c = new CS.System.Generic["Dictionary`2"]()
```

The translated lua is:

```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
-- Lua Library inline imports
function __TS__New(target, ...)
    local instance = setmetatable({}, target.prototype)
    instance:____constructor(...)
    return instance
end

Test = CS.System.Test
a = CS.System.Test()
b = CS.System.Generic["Dictionary`2"]()
c = __TS__New(CS.System.Generic["Dictionary`2"])
```

See this [playground](https://typescripttolua.github.io/play#code/CYUwxgNghgTiAEA7KBbEBnADlMCDCAygHQECe6ALiCvAN4BQ8T8A9AFRuPPxvwACYAK6UA9ijwjElGILAURMeIRLkqKIgBUMFLszYtd8SFHTp4WynUPcwk6bPkwAFAEpDAX3qHkaLDgQA4iCIIDAAlmBW3NzsnNHcvALC8uJ2FDJyCkrEZJTUREEh4WAA2gBEACIRFGGSsKQABgBMZQC61gkG8UzGpvBVcrXIMKRR3dxhUhRQiLiuAFzwAG4iYcAd8ZRQNZFbFAvLq+vjntyehr1mhaERY-GxG0yJQqKpUxmO2Sp56tfF5QManURs02o8eF1untbpVqkN6qDFhRSJgQCIAGZfXJqArBG5gDz0c62KbmbTwAC8WNU+QsOnoJMsUEpSBAAHcyZRXF5GRR4AAjFkhDnKbH5P4RIiA+EjbkMtJGIXs6k-XFFCIAuHAxotVquIA)

However there are too problems:

1) It would be better if `a` is translated to
```lua
Test = CS.System.Test
a = Test()
```
But I've found no way to do so.

2) `c` should be translated to
```lua
c = CS.System.Generic["Dictionary`2"]()
```
It should not call `__TS__New`

It's there any solution or workaround for these two cases? especially the second one

**Comment by ZhaoXiangXML** [comment]
I've come up with an solution for both problems:

```TypeScript
declare namespace CS.System {

    namespace Generic {
        interface Dictionary {
            instance(): void
        }

        interface DictionaryConstructor {
            (this: void): Dictionary
        }

        const Dictionary: DictionaryConstructor
    }

    abstract class Generic {
        static "Dictionary`2": CS.System.Generic.DictionaryConstructor
    }
}

const b = CS.System.Generic.Dictionary()

const c = CS.System.Generic["Dictionary`2"]()

const Dictionary = CS.System.Generic["Dictionary`2"]

const d = Dictionary()
```

But that would lead to another problem: I can't inherit this `Dictionary` class

**Comment by ark120202** [comment]
Personally I'd recommend to avoid `@customConstructor` and go with interfaces, but there is indeed no good solution for interitance.
One option is to stop using `extends` syntax altogether and let your inheritance decorator handle it:

```ts
// Using declaration merging to let type system know about members from base class
// This might become unnecessary if typescript would provide a way to make decorators modify class type
interface A extends CS.System.Generic.Dictionary {}
@customInheritance(CS.System.Generic.Dictionary)
class A {

}
```

Alternatively you can add a construct signature to your constructor interface, but make it harder to use somehow, for example using `@deprecated` jsdoc annotation

```ts
        interface DictionaryConstructor {
            (this: void): Dictionary

            /** @deprecated */
            new(): Dictionary;
        }
```

**Comment by ZhaoXiangXML** [comment]
I've tried both approaches, and I don't think plan A would work, at least not in this [playground](https://typescripttolua.github.io/play/#code/GYVwdgxgLglg9mABBEBnKcC2BJMALAUwCcYoBDSAgCnKIHMCoAuRAMXGnjAEpEBvAFCJhiAPSjEAUQAeUAmAAmiWgyiIA7qTyIARmVQEAwgBt9qAQF8BAhQQimiBRGDKYCqAA5kITwwGUAOj8AT3QCTH5rEWdXdy8fRABxeWIYCEjo6JgwOSJgbycAETTYBDIiYIzM6uz0Ch8qbhYANzgYBSFqxCtOmpzifITizjKKwwR0IhBoOCIqrpEaPBhUFraFJsRh0pcKqIWRUQAqI8QAAVsPRwgyOSUj0V6DsAJ1RpZtrnLggG4n6J6CwgEzUn1GwQ+JS+YxBUxmRCegJEZB0k28ansZiSKRI6UECzqsHSACIwbtggADABMxJY-iCoTkmACyReuICZO+4zAk2mGARAMs1mBPLUOkQAF5EPSQmFmazUhAOVDwY1hSDkJLpYFZUyWTi0gBtUkq8nU4kAXTVAhF6C2pu+WpljPC+rZRpNIzNNIt6tFiCUUs5FWt4kQAFVUNk6AG7A5blxEG56NHlHBEMZGMpgh4nKgXREANZgODqRAouAgNRuTA6YioRDAIhYXT6JyY1DmMMAFWWDcwMDoeDFdiwTnALx8ncdMGA2dzqAgJA8anUleMSiucGa7ScZA0ZEqGCTZELTlswKIt1m-bgClnlQ7DagOYIAmyuUGTgAgogCLJ5AUBtnTlN1FWVL1HT4KwzhQdAsFwQgSHISgqBAvUFVxY1g0pH1uBtUxO0QX9BCFARYLQDAcHwVIUJ8AisQAIT-ADFGAnUCzArDPR2b5zQtSJLCAA)

It seems to me that this line is not right:

```lua
A = __TS__Decorate(
    {
        customInheritance(nil, CS.System.Generic["Dictionary`2"])
    },
    A
)
```

Maybe there's a bug in decorator implementation?

Plan B looks promising though. I'll try it later in actual code and come back with result.

Thanks

**Comment by ark120202** [comment]
For the first option your code should look like that: [Playground](https://typescripttolua.github.io/play/#code/GYVwdgxgLglg9mABBEBnKcC2BJMALAUwCcYoBDSAgHgBUA+ACgCMzUCBhAG1dQC5EGASkQBeOohrCA3gChE8xEQJQQRJA3JEA5sv5gCAdwHCxEk+NkKriAPQ3EAUQAeUAmAAmiTTqiIDpPEQWNi4eOQUAXxkomXcCCG4lRDAyTAJUAAcyCAJEdgBlADp8gE90AkxESwUUtMzs3IBxN2IYCCrw60QYMFciYAbEABE22AQyIhKOrq6e9AocoX4ANzgYd07rGJnu3uIBnOHR+BTJ9gR0IhBoOCJpnYUNPBg+RFX1wX4R6BOJks2rNsZhALr5vmNTiUvsdxmdQVcbkRNlEYjIen0DrkAIKIAguNzuVB5IqlcqYQrNfQkCCFcG-SZVKIAARQ6CwuEIJHIlAYBWKZVc5MprRpdNhJUEMgSPEQONk0RkQA)

**Comment by ZhaoXiangXML** [comment]
That works however there's a compile error if `@noSelfInFile` or `this: void` was used:

```
error TSTL0: Decorator function cannot have 'this: void'.
```

I think I can just call this `customInheritance` function instead of using decorators: (Playground)[https://typescripttolua.github.io/play/#code/PQKhCgAIUgBA7A9gZQKYBsBmBJeAxAS3VShGHABNUBjdAQwCdVJ46BbVAZwAc7rmAwsgB0yAJ6cALqjaQA3uCiRlrDjz7MA4qnioGBavKXKTkAvGkNMGyABEDkgolYMxR0x5PmpdePwAUAJQAXJAAbogEFMYeAL6Knsrmltb8dg5OLmICzlIMAK7UkogM7omm-pIAFgScoRFRIelFmYxiCeUmoDCwVNxM1HTSFNDknSa6AO5BofYtzm0A3DGm8Ssm1LmSzY4LrrMZe9lbBUUlMWumdABGeXzbtHScnJDauvqGCuU+joYARHNdlkAAYAJj+oSEogk0jYwjeegMwkBrVcOXgeUKxQYF3A8Uw+T8QMg1HyUkQbFwVURkl8AVpDAA5qhJKE8IT5vAADSQa5PVBsjlAwJGPGKZJ6VLMACCkFQAA9pPAKC8oeIpDJ4TpEdRkYcsvJIPFHs9ILKFGLwKTyZT4NT9LS-Kh-NKeWqYZqER8ANoA-VtMF-AC6gUU4CAA]

**Comment by ZhaoXiangXML** [comment]
Another downside of plan A is I can't call methods in `DictionaryConstructor` with `SubClass.DictionaryConstructorMethod()`.

**Comment by ZhaoXiangXML** [comment]
I end up bringing in a new annotation and implement it with a tstl plugin.

**Comment by lolleko** [comment]
Closed as this question has been answered/ a solution has been found.
