### ISSUE TITLE
`delete` operator doesn't work on objects with a metatable

### ISSUE THREAD

**Issue by ark120202** [TypeScriptToLua/TypeScriptToLua#933]
[Playground](https://typescripttolua.github.io/play#code/MYewdgzgLgBAZiEAuGBvGAjAhgJwPwpgCuAthgKY4wC+MAvGprigAw0DcAUBOVCb1ihYMAG3IAKBCAA0aagEouAE3Jio5eIgB02HOyA)

**Comment by GlassBricks** [comment]
Seems to work now

https://typescripttolua.github.io/play/#code/MYewdgzgLgBAZiEAuGBvGAjAhgJwPwpgCuAthgKY4wC+MAvGprigAw0DcAUBOVCb1ihYMAG3IAKBCAA0aagEounAA44AlmCiTEAOmw55K9ZvEATcmKjl4u-YqMatUvbnlA
