### ISSUE TITLE
Optional Chaining support

### ISSUE THREAD

**Issue by felixhirt** [TypeScriptToLua/TypeScriptToLua#938]
Is my assumption correct that Optional chaining does not work / is not supported? Some examples:

let task: IRunnable | undefined;
task?.Execute() ?? error("No Task found to execute");
compiles to
local task
local ____ = task:Execute() or error("No Task found to execute")

let task: IRunnable | undefined;
task?.Execute();
compiles to
local task
task:Execute()

shouldn't it be something like
local _ = task and task:Execute() or error("No Task found to execute")
if task then task:Execute() else error("No Task found to execute") end

Are there plans to support this?

**Comment by Perryvw** [comment]
Correct, it is currently not supported. We do want to support it eventually, but it is very complicated because of possible chaining of multiple ?. and avoiding any unwanted side effects. I cannot give an estimate of when we can support this right now.

**Comment by felixhirt** [comment]
@Perryvw thanks for the info, just wanted to be sure im not doing it wrong. Its not that big of an issue as it can be worked around easily

**Comment by wd40bomber7** [comment]
This was quite a surprise for me too! Maybe TSTL could throw an error if it detects optional chaining? Its a shame its not supported but could we at least get an error? That way folks like me will just know its not supported and not scratch my head for a few hours thinking I'm doing something wrong.

**Comment by GavinRay97** [comment]
(Just my $0.02, would be good info to throw somewhere prominent in the docs because I didn't realize this either)

**Comment by lolleko** [comment]
Error/Diagnostic (optional chaining unsupported) is added in #966

Adding optional chaining support is blocked by #654.
