### ISSUE TITLE
Embed into a browser

### ISSUE THREAD

**Issue by librehome** [TypeScriptToLua/TypeScriptToLua#942]
Hi, nice work! Very impressive!
Can you opensource the src code for your playground demo?
I tried to embed it into a web browser but transpileString throws out an exception, which backtraced to util.ts function formatPathToLuaPath.

**Comment by Perryvw** [comment]
The entire website already is open source, you can find the playground demo files here: https://github.com/TypeScriptToLua/TypeScriptToLua.github.io/tree/source/src/pages/play

**Comment by librehome** [comment]
Thank you so much. It was a dumb question from me.
