### ISSUE TITLE
Representing functions with a name that is a JavaScript reserved word

### ISSUE THREAD

**Issue by LoganDark** [TypeScriptToLua/TypeScriptToLua#945]
Currently I am using namespaces to represent Lua globals with functions inside of them- that is okay, but this is not okay:

```ts
/** @noSelf */
declare namespace fs {
	...

	/** Deletes a file or directory. */
	function delete(path: string): void // <---- delete is a reserved word that cannot be used here

	...
}
```

This is a problem - the function is named `delete` but TypeScript does not have the capability to represent this!

Merging is not allowed:

![image](https://user-images.githubusercontent.com/4723091/102579555-8504b780-40b1-11eb-9488-91da3faf736e.png)

And even without type checking, the transpilation only recognizes the namespace declaration above so it doesn't even work correctly:

![image](https://user-images.githubusercontent.com/4723091/102579714-da40c900-40b1-11eb-85c0-f0d57702c308.png)

My only option is to include the function definition inside the namespace, but since function identifiers cannot be strings there is no way to name the function `delete`, so there needs to be a way to communicate to TypeScriptToLua that the function on the Lua side is named that way.

The issue? There _isn't_ yet such a feature.

I propose an `@luaName` annotation, which will allow you to specify a Lua name for the function. This would allow me to name the function something different like `_delete` and then in the transpilation step it is turned back to `delete`.

Example:

```ts
/** @luaName bar */
declare function foo(x: string): void

foo('Hi!')
```

would transpile to

```lua
bar('Hi!')
```

Likewise,

```ts
/** @noSelf */
declare namespace fs {
	/** Deletes a file or directory.
	 * @luaName delete */
	function _delete(path: string): void
}

fs._delete('some path')
```

would transpile to

```lua
fs.delete('some path')
```

**Comment by hazzard993** [comment]
TypeScript supports the following syntax to allow exports with such names as `delete`

```ts
/** @noSelf */
declare namespace fs {
  function _delete(path: string): void;
  export { _delete as delete };
}
```

Would this work for you?

**Comment by LoganDark** [comment]
> TypeScript supports the following syntax to allow exports with such names as `delete`
> 
> ```ts
> /** @noSelf */
> declare namespace fs {
>   function _delete(path: string): void;
>   export { _delete as delete };
> }
> ```
> 
> Would this work for you?

I mean... kind of? It's not a very elegant solution and it's also probably undefined/unintended behavior.

I'm actually working on a PR to add the luaName attribute but it could take a while because I'm not familiar with your codebase. It already works for method calls though.

**Comment by lolleko** [comment]
Hi, thanks for the issue and the PR.

I am pretty sure we had discussions about a "rename" directive (or something similar: #65, #45, and probably on discord aswell) a couple of times and we always decided against it.
The solutions @hazzard993 mentions seems to be the correct method to handle such cases (it is endorsed by the TS team https://github.com/microsoft/TypeScript/issues/14815)

Compiler annotations/directions are hacks we added, to support Lua functionality that is impossible to support otherwise.
So a directive should only be added as a last resort, ideally we would not need any.
> I mean... kind of? It's not a very elegant solution and it's also probably undefined/unintended behavior.

Personally I find, that using regular TS is more elegant than having to resort to an directive.

In addition, maintaining a directive is pretty costly, because every time we make changes to part of the transpiler that can be influenced by a directive, we have to make sure the directive still works correctly.
Take `@extension` for example, which broke (#492) when we refactored our class translation and is still broken, because fixing it requires us to write a completely different class translation code for classes with that annotation.

I feel that something like `@luaName` would also influence many parts of the transpilation process and may have unwanted sideffects.

**Comment by LoganDark** [comment]
An issue with the export hack is that the function becomes available twice, i.e. once under the "bad" name and once under the "good" name. The reason I avoid it is similar to the reason I use `declare const somelib: {...}` instead of declaring a type/interface and then declaring that the variable is of that type.

With `@luaName` your calls to the function would be translated to the correct name, even if it's impossible to use that correct name within TS. There will be no extra function floating around, only the one you call which then works correctly on the Lua side.

> I feel that something like @luaName would also influence many parts of the transpilation process and may have unwanted sideffects.

Not necessarily. Take a look at the PR; it's already mostly functional (but not fully) and all I've had to do is add a couple checks for that annotation. Thanks to transformIdentifier I got a lot of stuff for free, but I do have an issue with `getTypeAtLocation` that affects other annotations as well (any annotations on variables aren't detected).

Once the work is done you're definitely invited to go take a look. It's not _that_ invasive, it's about the normal level of invasive that adding a new feature is. I do need more test cases though.

I also agree with you on the fact that, in general, TS is more elegant than sprinkling `@whatever`s all over the place. I experienced this first-hand when I had to add over _three hundred_ `@noSelf`s to my project because of the `getTypeAtLocation` bug which caused `@noSelf` to not be detected on the variable (which I'm not sure how to fix yet).

**Comment by lolleko** [comment]
> An issue with the export hack is that the function becomes available twice, i.e. once under the "bad" name and once under the "good" name. The reason I avoid it is similar to the reason I use declare const somelib: {...} instead of declaring a type/interface and then declaring that the variable is of that type.
With @luaName your calls to the function would be translated to the correct name, even if it's impossible to use that correct name within TS. There will be no extra function floating around, only the one you call which then works correctly on the Lua side.

I agree that `@luaname` is a convenient solution, but In my opinion we have to rule out every possible vanilla TS solution first.
For me the I can only access the exported function, so for me the function is only available under the "good name". Or does that not work for declarations files?

![Screenshot 2020-12-19 at 12 30 04](https://user-images.githubusercontent.com/4759511/102688269-fe0d2780-41f5-11eb-86f8-a4c50ca14def.png)

Also `@luaname` can also cause similar issues and break type safety.

```ts
/** @luaName bar */
let foo = "hi";

let bar = "bye"

print (bar)
```

> I highly doubt @luaName will have a huge effect on your transpilation process. Plus, I'm doing most of the work for you, that's what a PR is after all 😛.

Yeah it is very nice that you are willing to work on your own issue. However maintaining this might create more work in the long run e.g. TS API changes, Our API changes, our symbol handling changes... But you are very welcome to continue on the PR, just keep in mind that there is a chance we might end up rejecting it.

**Comment by LoganDark** [comment]
> Also `@luaname` can also cause similar issues and break type safety.

That is a good point. Any solution to that problem would make this that much harder to maintain. Since you're already on the fence about how this could create more work in the long run, I don't think it would be a very smart idea to try to detect this. Not to mention the initial complexity of trying to do that anyway.. Besides, the translation from TS -> Lua already breaks down type safety, and since this is one of those things, I think it's just something that can't be solved effectively. It could be worth it to warn against this in the docs, though.

> However maintaining this might create more work in the long run e.g. TS API changes, Our API changes, our symbol handling changes...

Yes, that is the unfortunate reality of adding new features. Even if each feature is tiny on its own, it piles up over time. No amount of "but the feature is so simple!" can deny that reality. My only hope is to effectively communicate that the pros outweigh the cons.

Still, even though I've managed to fix the problem in my particular case (by switching from namespaces to `declare const`), it also comes with the compromise of losing annotation support on the const variable itself. I've decided that instead of relying on `noSelf` I'd add `this: void` to all functions without a self. It doesn't make much of a difference when it comes to declared functions, but it's also portable to functions in other contexts as well as arrow functions and stuff, so it's good.

Also, I doubt it will help my case much but let me just say this: Refactoring code in general tends to involve rewriting parts of it. You can totally change symbol handling, or your API, or have to change your code to conform to TS API changes. In all of these cases you probably still want to preserve the features that you had before the refactor. Yes, refactors happen, and yes they can be hard (less so with modern tools like WebStorm). I don't think this feature is complex enough to warrant "but the refactors!", since it's kind of negligible in comparison to other parts of your architecture. Things do pile up, but this one is not too bad.

At least, the current situation is not. Tests are still failing, there are a lot of things I need to implement and after all this is done you're likely to have more than a couple nitpicks about where I chose to place my checks because I don't know your codebase. Things may become slightly more hacky if I have to implement a solution for that getTypeAtLocation problem (which should really be replaced by a utility function that handles this correctly - probably a task for a different PR than mine).

**Comment by hazzard993** [comment]
> I mean... kind of? It's not a very elegant solution and it's also probably undefined/unintended behavior.

> An issue with the export hack is that the function becomes available twice, i.e. once under the "bad" name and once under the "good" name.

Ah I see why you think it is a hack

```ts
/** @noSelf */
declare namespace fs {
  function _delete(path: string): void;
  export { _delete as delete };
}

fs._delete; // inaccessible
fs.delete; // accessible
```

Using `export` in a namespace means all other members that don't use `export` don't get exported. They are just scoped to that namespace and are inaccessible from outside of it

Not using `export` at all means all declarations become available when accessing that namespace

This issue isn't unique for TSTL, this is one of the design intentions of `export { ... }`. To represent functions with reserved JS names

**Comment by LoganDark** [comment]
> Using export in a namespace means all other members that don't use export don't get exported. They are just scoped to that namespace and are inaccessible from outside of it
> 
> Not using export at all means all declarations become available when accessing that namespace

Oh... I didn't know using export made everything else inaccessible. But then a different problem emerges, I'd have to re-export every single other function..

**Comment by hazzard993** [comment]
If you have defined more functions you can also put that `export` keyword in front of them

```ts
declare namespace fs {
    export function create(): void;
    function _delete(): void;
    export { _delete as delete };
}

fs.create();
fs._delete(); // no, inaccessible
fs.delete();
```

**Comment by LoganDark** [comment]
Alright, well if that's the case then I guess my only reason to support `@luaName` is gone. The vanilla TypeScript way seems to be the way to go. Thank you @hazzard993
