### ISSUE TITLE
Functions like pcall

### ISSUE THREAD

**Issue by LoganDark** [TypeScriptToLua/TypeScriptToLua#947]
pcall prepends its own success value to the values returned by a function. Unfortunately this is probably impossible to represent in TypeScript.

Since functions that return multiple values use an array you can use the spread operator like so:

```ts
declare function pcall<F extends (...args: any) => any>(this: void, f: F, ...args: Parameters<F>): [true, ...ReturnType<F>] | [false, string]
```

But functions that return an indexed table will have their return values erroneously spread.

Likewise this works for functions that do not return multiple values:

```ts
declare function pcall<F extends (...args: any) => any>(this: void, f: F, args: Parameters<F>): [true, ...ReturnType<F>] | [false, string]
```

but breaks for functions that do:

```ts
function returnsMultipleValues() {
	return [4, 5, 6]
}

const [success, message, two, three] = pcall(returnsMultipleValues)
```
transpiles to
```lua
success, message, two, three = pcall(returnsMultipleValues)
```
which is correct, however:

```
main.ts(5,26): error TS2339: Property '2' does not exist on type '[false, string] | [true, number[]]'.
main.ts(5,31): error TS2339: Property '3' does not exist on type '[false, string] | [true, number[]]'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cc-path-tracer@0.0.1 build: `tstl`
npm ERR! Exit status 2
```

Since the `@tupleReturn` does not look like anything to TypeScript, it can't detect that annotation on its own.

Perhaps some type could be introduced by TypeScriptToLua to help this.

```ts
declare function pcall<F extends (...args: any) => any>(this: void, f: F, args: Parameters<F>): [true, ...TuplifyReturnType<F>] | [false, string]
```

Which would act like `ReturnType`, but wrap the return type in a tuple if the function does not have the `@tupleReturn` annotation.

However I am not sure how this would work because the goal of these types is for IDE support and reading it at the transpilation step is too late.

**Comment by Perryvw** [comment]
Indeed there is no way to distinguish between a function returning a tuple type with tupleReturn, and one returning a tuple type without tupleReturn.

Related to #821 which would introduce a special type for tuple return functions that would make it possible to distinguish this case in the type system.

**Comment by lolleko** [comment]
Is this accomplishable with MultiReturn?
In that case we can close the issue.

**Comment by tomblind** [comment]
pcall can be typed like this:
```ts
declare function pcall<A extends any[], R extends any[]>(f: (...args: A) => MultiReturn<R>, ...args: A): MultiReturn<[true, ...R]> | MultiReturn<[false, string]>;
declare function pcall<A extends any[], R>(f: (...args: A) => R, ...args: A): MultiReturn<[true, R]> | MultiReturn<[false, string]>;
```

But, the resulting types are not quite correct, due to a bug in TS itself triggered by how we declare MultiReturn (see microsoft/TypeScript#42557):

```ts
declare function foo(): [number, number];
declare function bar(): MultiReturn<[number, number]>;

const [successA, resultA] = pcall(foo); // resultA = string | [number, number]
const [successB, resultB1, resultB2] = pcall(bar); // resultB1 = string | number, resultB2 = string | number | false !?
```
