### ISSUE TITLE
Cannot place source files in 'src' directory because it breaks imports

### ISSUE THREAD

**Issue by LoganDark** [TypeScriptToLua/TypeScriptToLua#951]
For some reason, even though all `require` calls look like this:

```lua
local ____something = require("src.something")
```

the corresponding definition in the generated bundle is this:

```lua
["something"] = function() ... end
```

I heard it maybe has something to do with missing `@noResolution` in #917, but I'm not using `declare module` at all, and `@noResolution` doesn't seem to do anything no matter where I put it.

Repro: https://github.com/LoganDark/tstl-require-thing

I do not think slapping `@noResolution` everywhere is a good solution anyway. I believe that TSTL should be including the `src.` here like so:

```lua
["src.something"] = function() ... end
```

**Comment by Perryvw** [comment]
Try adding `"rootDir": "src"` to your tsconfig when bundling.

**Comment by LoganDark** [comment]
> Try adding `"rootDir": "src"` to your tsconfig when bundling.

That worked! Is it a bug that this happens when rootDir is not specified like that? I sure hope it is.

**Comment by Perryvw** [comment]
Yeah this is a problem with the module path resolution in bundling tracked by #823.

**Comment by LoganDark** [comment]
Might want to pin stuff like that so you get less duplicate issues...
