### ISSUE TITLE
Standard library check

### ISSUE THREAD

**Issue by librehome** [TypeScriptToLua/TypeScriptToLua#954]
I built a test app with a custom LanguageServiceHost.
However, the result is different than that of the playground.

For example, the code below
for (const enemy of enemies) {} 

It should be transpiled to an "pair()", but it resulted in "__TS__Iterator(enemies)"

I think it is a standard library check issue. And I know there is something wrong with my code but I couldn't figure out.

Any help is appreciated.
Thanks in advance.

**Comment by lolleko** [comment]
Can you share your code?

**Comment by Perryvw** [comment]
That sounds like it is not able to determine `enemies` is an array type, which depends on your other code and declarations of course. Indeed we would need to see the full code.

**Comment by librehome** [comment]
Below is the link to the code. I copied a script from Microsoft monaco plugin to generate the standard library.
However, it appears the result is the same whether or not the library is loaded.

https://github.com/librehome/TestTstl

**Comment by Perryvw** [comment]
Hard to say, it might be that indeed it cannot find filter in the standard library and therefore cannot understand what the type is. I think it is the type of enemies that is the problem, though I could not tell you why from looking at this code. You could try just manually inspecting the AST and types TS produces (in the sourceFile variable).

Also make sure you check all diagnostics to see if there is any indication in there what the problem is. I see you do output the tstl diagnostics, but maybe `ts.getPreEmitDiagnostics(program)` also gives some information.

**Comment by librehome** [comment]
@Perry,
Thank you for your response. Actually using the same source in the playground results in a different Lua result (with both the filter and pair() correctly handled).

By looking at the source code, I think the function "isStandardLibraryDeclaration" is behaving differently in my environment.

The typescript environment is a myth!

**Comment by librehome** [comment]
Some Progress

The problem is not in Standard library check!
It is in the AST of expression signature.

The declaration below:
declare function findUnitsInRadius(this: void, center: Vector, radius: number): Unit[];

Got an AST like below:
(this: void, center: Vector, radius: number) => {}

As far as I can tell, the return signature is not an array.

Can anybody confirm?
I tried typescript 4.0.3 and 4.0.5, same problem.
Can't get latest 4.1.3 working because of compile error.

**Comment by Perryvw** [comment]
That does seem incorrect, here is a tool you can use to compare: [ts-ast-viewer.com](https://ts-ast-viewer.com/#code/PTAEBEFMGMBsEMBOlSQB4AcD2BnSATUAQQAUBJAKABcBPDFANRiq0VAF5QBtAOwFcAtgCNIiADSh+w0RKkjEAXQDcFSFIgBLZNCoasPUAG8KoUAFUMYkxCwB3HldMAZSADMqj0ACUNAcwAWHhQAvhT4MAjIoK58PDp6Bq4aPPhmPBpUOGQ8XvD4Gnw4ABRU-ho4AFygAG5YGvgS0GpUolVMOqwSiHkFlZKC8gCUVWkZXMphEUgoyS2IrvBN5ulURtam5QCiPJACNEVYpa3LGcOgQlhYsJDwPCqmpgDWGrCwRWe19fcP+dq6+lVwFpmAkVKEQOY8KBwnBpoRSGRQMlQNAsOEKDE4v8DPoiEIXhkaABheA4KglMp9T4NFGkuYjFYSKhIXyQKhOLDQeDYtrMViDNYPFH6MmgWIZHAcaLJVIrLI5HqFEostkcrnYiQAVgADNrBt9TKieKK1LsNJBJZxxZkAHRJWBzIrWjgAPlpZNENq2Oz2TpWAoAZAH3XMbb8QfoOJwgX8EjaLPr1tFWKAikaTT6aKAsK5UD7zTgBcYhULTXsbc9Xu8DaBQsEgA)

As far as I can tell the types on findUnitsInRadius and enemies look correct there, you might be able to learn something by comparing this to your AST.

**Comment by librehome** [comment]
> 
> 
> That does seem incorrect, here is a tool you can use to compare: [ts-ast-viewer.com](https://ts-ast-viewer.com/#code/PTAEBEFMGMBsEMBOlSQB4AcD2BnSATUAQQAUBJAKABcBPDFANRiq0VAF5QBtAOwFcAtgCNIiADSh+w0RKkjEAXQDcFSFIgBLZNCoasPUAG8KoUAFUMYkxCwB3HldMAZSADMqj0ACUNAcwAWHhQAvhT4MAjIoK58PDp6Bq4aPPhmPBpUOGQ8XvD4Gnw4ABRU-ho4AFygAG5YGvgS0GpUolVMOqwSiHkFlZKC8gCUVWkZXMphEUgoyS2IrvBN5ulURtam5QCiPJACNEVYpa3LGcOgQlhYsJDwPCqmpgDWGrCwRWe19fcP+dq6+lVwFpmAkVKEQOY8KBwnBpoRSGRQMlQNAsOEKDE4v8DPoiEIXhkaABheA4KglMp9T4NFGkuYjFYSKhIXyQKhOLDQeDYtrMViDNYPFH6MmgWIZHAcaLJVIrLI5HqFEostkcrnYiQAVgADNrBt9TKieKK1LsNJBJZxxZkAHRJWBzIrWjgAPlpZNENq2Oz2TpWAoAZAH3XMbb8QfoOJwgX8EjaLPr1tFWKAikaTT6aKAsK5UD7zTgBcYhULTXsbc9Xu8DaBQsEgA)
> 
> As far as I can tell the types on findUnitsInRadius and enemies look correct there, you might be able to learn something by comparing this to your AST.

Yes, they look correct in that viewer! But just not correct on my machine! That is the problem.
If you clone my repo and test run you will find out that the AST is wrong!

**Comment by librehome** [comment]
Finally found out the cause of the problem.
I have to use ts.createProgram(); otherwise the compiler is broken!
