### ISSUE TITLE
Indexing MultiReturn return value leads to incorrect Lua

### ISSUE THREAD

**Issue by Perryvw** [TypeScriptToLua/TypeScriptToLua#960]
For example:
```ts
function func() {
    return $multi(1,2,3);
}

print(func()[1])
```
Causes `func()[1]` to be translated to `func()[2]`, which is not correct, instead it should be something like `({ func() })[2]`.

Reported here: https://github.com/TypeScriptToLua/TypeScriptToLua/pull/821#issuecomment-753604417

**Comment by LoganDark** [comment]
Since this has to be special-cased, you could also use `select` to avoid table stuff: `(select(2, func()))`
