### ISSUE TITLE
Add comment node to Lua AST

### ISSUE THREAD

**Issue by Perryvw** [TypeScriptToLua/TypeScriptToLua#965]
Currently we don't need any comments in our printed Lua, but some users have a need for emitting some comments (for instance documentation comments on functions) from their tstl plugins.

Easiest proposal:
```ts
export interface CommentStatement extends Statement {
    kind: SyntaxKind.Comment;
    text: string;
}
```
Printing simply as a statement to:
```lua
--${comment.text}
```

Comments/suggestions welcome

**Comment by lolleko** [comment]
Adding Discussion from Discord:

> While we are at it we could also try to preserve existing comments.
> TS has ts.getLeadingCommentRanges and ts.getTrailingCommentRanges, I am not sure if the contents are stored on the TS AST or within the tokenizer. But for us it will probably be the easiest to store them on the AST. Every node could have a trailing/leading comment field:
> 
> ```ts
> export interface Comment extends TextRange {
>     multiline: boolean;
>     content: string;
> }
> export interface Node extends TextRange {
>     kind: SyntaxKind;
>     leadingComment?: Comment;
>     trailingComment?: Comment;
> }
> ```
> 
> As for the comment type (multi/single) I think we can get that information from the TS API as well and use the same type in the emitted Lua. Since TS and Lua comments are pretty similar in their syntax. Plugin creators could decide to add the multiline flag or not on custom/modified nodes.
> 
> If we want to support all kinds of comments even some exotic cases like this: `let x = a /** test */ + 3;` we should add the comment fields to all `Nodes` if not it might be enough to add the comment fields to `StatementNodes` only.

**Comment by Perryvw** [comment]
Done in 0fba69b06767811f554f21fa8f3d20cb51d5b25c
