### ISSUE TITLE
default should be last case in switch statement

### ISSUE THREAD

**Issue by SupinePandora43** [TypeScriptToLua/TypeScriptToLua#967]
errored:
[default as first case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtykCmAZhgK4A2EAFyMAkCIAOAJzA4ICAEQdu-CPIKiRAI0nsM5ZqyhZ2cAIzCxUmXPkA5APK2Aomo3bd+kUeAmATBYlpWQVUABkAQQBlSNcxdz1RbxMAZgCrYPknAA0ABVD7SIBJADUXdVYKuHj9AF8gA)
[default as addition to first case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtykCmAZhgK4A2EAFzNWULOzgBGYQEgZABwBOYHBAQAiAHIB5TQFF1BRnIBGi9hnLGxwCQCZZC5ao2oAMgEEAyl8PGZZhZWMjYSAMyOSipq6noAGgAKbtpeAJIAagZGrDlwgZaMAL5AA)
[default as middle case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg0hwBmGAK4AbCPyFiJU6QePmIq9Vp16B7YFwBMVkeKSMqgAMgCCAMoRLkJuuoJeXADM-jZB0koAGgAKIfIRAJIAaipqrOVwcXoAvkA)
[default as addition to middle case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg0hwBmGAK4AbCPwHtgXAExWR4yTNQAZAIIBlL6vVadPWtOOABmRzEJKWklAA0ABTd5LwBJADUVNVZsuADdRgBfIA)
[default with addition](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg9sC4AmfkLESp01ABkAggGV7q9Vp16BBrgGZTI8ZJklAA0ABWt5ewBJADUVNVYEuFddQVIOADMMAFcAGwhTTzgAFl9zAOk0zNyIZyFkvQBfIA)
working:
[default as last case](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg9sC4AmfkLESp01ABkAggGV7q9Vp16BBrgGZTI8ZJklAA0ABWt5ewBJADUVNVYEuFddQVIOADMMAFcAGwhfcwDpNMzciGchZL0AXyA)
[`case 5:\ndefault:`](https://typescripttolua.github.io/play/#code/M4dwlgLgxgFgBACgQfQOJwIbEwOwJ4CUAdGACYDWIMGEBcA3gFBwtxRYCmcAjAFyMBIAQAcATmBwQEAIgByAeVkBRaQUECARqI4Zyg9sC4AmfkLESp01ABkAggGV7q9Vp16BBrgGZTI8ZJklAA0ABWt5ewBJADUVNVYEuFddfU44ABZTUg4AMwwAVwAbCF9zAOlsvKKIZyFkvQBfIA)

**Comment by Perryvw** [comment]
Looks like we can fix this by reordering the cases before translating, so that default is the final case.
