### ISSUE TITLE
Inline enumerations

### ISSUE THREAD

**Issue by saksmt** [TypeScriptToLua/TypeScriptToLua#974]
Would be nice to have a way to type lua enums which aren't actual enums and just rely on some restricted set of values. For example imagine following lua function:

```lua
function sayHello(language)
  if language == 'en' then
    print('Hello')
  elseif language == 'ru' then
    print('Привет')
  end
end
```

Of course we can provide simple typing like following:
```typescript
declare function sayHello(language: 'en' | 'ru'): void
```

But it would be nice to be able to define something like this:
```typescript
/** @inlineValues */
export enum Language {
  English = 'en',
  Russian = 'ru',
}

declare function sayHello(language: Language): void
```

**Comment by lolleko** [comment]
https://typescripttolua.github.io/docs/advanced/compiler-annotations#compilemembersonly

**Comment by saksmt** [comment]
That's not it if I understand correctly. My example should emit following code:
```lua
sayHello('en')
```
when used as:
```typescript
sayHello(Language.English)
```
but `compileMembersOnly` will result in:
```lua
English = 'en'
sayHello(English)
```

That's critical difference given the fact that currently there is no way to depend on external typescript libraries (#432) and all external typings must be fully abstract

**Comment by Perryvw** [comment]
Sounds like you are looking for const enums, see the following example on the playground: https://typescripttolua.github.io/play#code/MYewdgzgLgBApmArgWxgGQIZgOaI9uGAbwCgYYBRHAGwEsIALGAXhgHIE2AaMmAJUQQItLC3YAnRNxIBfEiQAmcYNQzjCAM0RhgUWuBgQMATwAScatRAAKVTjwEAXOiy58cAJTOAbiFoL5IzMLK2tMe3cAOipsOkYPAG4gA

**Comment by saksmt** [comment]
@Perryvw :bow: my bad, not really familiar with typescript :smile:
