### ISSUE TITLE
`declare module` in separate package

### ISSUE THREAD

**Issue by saksmt** [TypeScriptToLua/TypeScriptToLua#975]
When using `declare module 'myModule'` locally it works as expected generating `require('myModule')` and correctly resolving types, but when placed in separate npm package to be used in `types` resolution fails

version: 0.37.1

## works:

`index.d.ts`:
```typescript
declare module 'myModule' {
  export const sample: string;
}
```

`main.ts`:
```typescript
import { sample } from 'myModule'

print(sample);
```

## fails:

`myModuleTypes/index.d.ts`:
```typescript
declare module 'myModule' {
  export const sample: string;
}
```

`myModuleTypes/package.json`:
```json5
{
  // ...
  "name": "myModuleTypes",
  "types": "index.d.ts",
  // ...
}
```

`usage/package.json`:
```json5
{
  // ...
  "dependencies": {
    "myModuleTypes": "file:../myModuleTypes",
  },
  // ...
}
```

`usage/tsconfig.json`:
```json5
{
  // ...
  "compilerOptions": {
    "moduleResolution": "node",
    "types": [ "myModuleTypes" ],
  },
  // ...
}
```

`usage/main.ts`:
```typescript
import { sample } from 'myModule'

print(sample);
```

error: `Cannot find module 'myModule' or its corresponding type declarations.`

---

I don't know typescript well so I'm not sure if this behavior related to tstl or not, but for me it looks like something is broken or am I missing something?

P.S. If I declare my types like following:

`myModuleTypes/myModule.d.ts`:
```typescript
export const sample: string;
```

and use:
`usage/main.ts`:
```typescript
import { sample } from 'myModuleTypes/myModule'
```

it fails with `File 'myModuleTypes/myModule.d.ts' is not a module.`

**Comment by Perryvw** [comment]
Sorry for the late reply, this completely escaped my attention. This is not TSTL related but TypeScript. `declare module` declares the existence of an external package from  your project sources, so it should only be used as part of your project. A package itself should simply contain .d.ts files that export functions and vars, without using `declare module`. For some examples of package declarations see:

Package with module code (not global): https://github.com/TypeScriptToLua/TypeScriptToLua/tree/master/test/transpile/module-resolution/project-with-node-modules/node_modules/lua-module-with-decls

Package with globals:
https://github.com/TypeScriptToLua/TypeScriptToLua/tree/master/test/transpile/module-resolution/project-with-node-modules/node_modules/lua-global-with-decls
