### ISSUE TITLE
Enum merging doesn't work properly

### ISSUE THREAD

**Issue by Nibuja05** [TypeScriptToLua/TypeScriptToLua#977]
Normally Enums can be merged as seen here: [TS Playground](https://www.typescriptlang.org/play?#code/FAUwdgrgtgBAKiAzgFwKKVgb2DXMCCyyAhgMYDWAksiLALwwAMANDngCIgBm4iI1tGAwCMrAL7BQGeEjTTseGAFliAcwCWpAfRgAmcZK4B7AE4wAFABsQyGOGhLaAIxBn1YGSnTQAlDAW4pEZgiEbWAHSWRqrmAET2sFDOrgBcMLHMdhiOUC4mPgDcwBLAQSFhIJHRcQC0dfUNNbE+QA)
But it doesn't work in Tstl: [TSTL Playground](https://typescripttolua.github.io/play/#code/LAKFFMDsFcFsAIAq4DOAXAojBBvU8D4BBNNAQwGMBrASTXAQF54AGAGn0IBFwAzKFODoN4zAIwcQAX1ARsSVJnl4QheAFkyAcwCWFYU3gAmSTLAheAewBO8ABQAbcGnhQ46hgCNwtnZAXoWHAAlPAqhAAO1n5odgBEbgiwXj4AXPBxbK7YHrDe1sEA3KBSQA)

The second `TestEnum = {}` should actually be `TestEnum = TestEnum or {}`

**Comment by Perryvw** [comment]
Resolved in #980
