### ISSUE TITLE
[Docs] MultiReturn or LuaMultiReturn?

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/TypeScriptToLua#986]
**Description** 
[Wiki](https://typescripttolua.github.io/docs/advanced/language-extensions/#multireturn-type) says, that there is `MultiReturn` type, however, in [the declaration file at the latest commit](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/eae12b6c96fc15418d3373b2b51718bf7490fbcd/language-extensions/index.d.ts) there is no `MultiReturn`, only `LuaMultiReturn`

Maybe I missed something?

**Version** 
"typescript-to-lua": "^0.38.0"

**Comment by lolleko** [comment]
the name was changed in the latest version: https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/CHANGELOG.md#0380

seems like we haven't updated the website yet

**Comment by lolleko** [comment]
Updated the docs, thanks for the report!
