### ISSUE TITLE
[Question] Manually set "should lua file be module or not"

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/TypeScriptToLua#990]
**Introduction**

I'm developing resources for MTASA on typescript. MTASA does not support Lua's `require`, therefore, I cannot use Lua Modules. Only global-scoped variables/classes/functions can be used.

However, I would like to use imports in my typescript files (because, for example, there are different function signatures for client and server side), therefore, my typescript files are modules.

**At the current moment**

[There is the visitor](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/0fba69b06767811f554f21fa8f3d20cb51d5b25c/src/transformation/visitors/sourceFile.ts#L29), that provides Lua Moduleness for Lua file. It depends on context's `isModule`.

`isModule` detects from `ts.isExternalModule` [here](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/0fba69b06767811f554f21fa8f3d20cb51d5b25c/src/transformation/context/context.ts#L36), hence, TypeScript module will be converted to Lua Module (with `____exports` and local-scoped classes and variables).

**My workarounds**

I can get rid of `require` by removing `import` ts.nodes with [transformer](https://gitlab.toliak.ru/mtasa/typescript/lua-transformer/-/blob/master/src/index.ts#L26)

Also I can get rid of all `import` and `export` lines in the whole file with the transformer, however, `ts.isExternalModule` still detects the file as module

I have tried dirty hack and set `externalModuleIndicator` to `undefined` [here](https://gitlab.toliak.ru/mtasa/typescript/lua-transformer/-/blob/master/src/index.ts#L34). But this way crashes TypeScript compilation (imported types are undefined).

**Illustration**

Example TypeScript file:

```typescript
import {outputChatBox} from 'mtasa-lua-types/types/mtasa/client/function';

const awesomeGlobalVariable: number = 13;
outputChatBox('Sample text here');
```

Compilation (with my transformer) result:

```lua
local ____exports = {}
local awesomeGlobalVariable = 13
outputChatBox(nil, "Sample text here")
return ____exports
```

Expected result:

```lua
awesomeGlobalVariable = 13
outputChatBox(nil, "Sample text here")
```

**Conclusion**

Is there any ideas/workarounds, how can I provide that ~(without regexes replacements please)~?
I can try to make enhancement Pull Request with new config property, it that's allowed :)

**Comment by Perryvw** [comment]
We support bundling which compiles all your code into a single file. See `luaBundle` and `luaBundleEntry` here https://typescripttolua.github.io/docs/configuration.

To make functions or variables global so the engine can read them you can directly assign them to _G or globalThis (which is translated to _G). Here is an example of a class decorator that assigns stuff to _G https://github.com/Shushishtok/dota-reimagined/blob/master/game/scripts/vscripts/lib/tstl-utils.ts

**Comment by Toliak** [comment]
Sure, I forgot about `_G` and `globalThis` :)
Thank you!

**Comment by Toliak** [comment]
Well, I wrote [the transformer](https://github.com/mtasa-typescript/mtasa-lua-utils/blob/master/src/remove_export_modifier.ts), that [replaces export by _G assignment](https://github.com/mtasa-typescript/mtasa-lua-utils/blob/master/docs/export.md)

So, if someone is concerned with that issue, can try to use that...
